### ISSUE TITLE
OAuth2::Error usageLimits accessNotConfigured

### ISSUE THREAD

**Issue by davidbella** [zquestz/omniauth-google-oauth2#111]
I'm having an issue using this gem within a Rails app. Starting from a fresh Rails app, adding this gem and configuring the OAuth builder for my Google app, I receive this error upon callback from Google:

OAuth2::Error
{"errors"=>[{"domain"=>"usageLimits", "reason"=>"accessNotConfigured", "message"=>"Access Not Configured. Please use Google Developers Console to activate the API for your project."}], "code"=>403, "message"=>"Access Not Configured. Please use Google Developers Console to activate the API for your project."}: { "error": { "errors": [ { "domain": "usageLimits", "reason": "accessNotConfigured", "message": "Access Not Configured. Please use Google Developers Console to activate the API for your project." } ], "code": 403, "message": "Access Not Configured. Please use Google Developers Console to activate the API for your project." } }

I have verified that this gem works in a similar Sinatra app, using the same Google app. Any insight would be appreciated. Thanks.

**Comment by Developerdjax** [comment]
i have enabled all the api's .since, access not configured error is displaying . I m checking the authorization in https://developers.google.com/oauthplayground/. here itself error has been displaying. {
  "error": {
    "code": 403, 
    "message": "Access Not Configured. Ad Exchange Seller API has not been used in project 407408718192 before or it is disabled.
}
}.
  Can you suggest me any oauth authorization without using google login ?

**Comment by zquestz** [comment]
@Developerdjax I am not sure what you are trying to do. What are you trying to access? Also how do you expect to get a valid google token without using the google oauth? I am confused.

**Comment by pramodshinde** [comment]
@Developerdjax Looking at your message I could guess your passing some scope in you authorization request related to `Ad Exchange Seller API` and its not enabled at project settings OR If you are enabled `Ad Exchange Seller API` then you have to give some time to reflect changes.

**Comment by Developerdjax** [comment]
@ zquestz : Thanks for your response. I need some other authorization technique without google login.  Because, corresponding api file will be given as cron file. It should run automatically for every day , i cant authorize for each and every request . So can you suggest some other technique to use Google Adseller Api.

**Comment by Developerdjax** [comment]
@pramodshinde: Thank You for your response. I have enabled the Google Adseller Api since 3 days ago .  I have checked the request api in https://developers.google.com/oauthplayground/ , here itself the scope has been passed in step 1, finally i have got the error message as " _"code": 403, 
    "message": "Access Not Configured. Ad Exchange Seller API has not been used in project 407408718192 before or it is disabled". "domain": "usageLimits", 
        "message": "Access Not Configured. Ad Exchange Seller API has not been used in project 407408718192 before or it is disabled"_ " . Can you suggest me any other authentication technique?

**Comment by zquestz** [comment]
@Developerdjax you shouldn't need to auth on every crond api call. You should be requesting an access token, then using that token when you make your api calls. That token can have a long expiry, and you can enable offline_access, which should allow you to do what you need. With regards to the error your seeing, can you include the EXACT scope you are using with the gem?

**Comment by Developerdjax** [comment]
@zquestz: Thank you for your valuable response. Url request will be as, https://accounts.google.com/o/oauth2/v2/auth?redirect_uri=https%3A%2F%2Fdevelopers.google.com%2Foauthplayground&response_type=code&client_id=xxxxxx.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadexchange.seller&approval_prompt=force&access_type=offline.  I need to request access token and validate response in json using php file extension, because i m using codeigniter adx seller api library.Can you suggest any method to proceed for google authentication ?

**Comment by mrutyunjayamsrit** [comment]
Hi,

I am trying to access "https://cloudcontactcenter.googleapis.com/v1alpha1/{parent=projects/*}/agentAssistants". I got access token and then sent request to above URL getting the following error. I have enabled the "Cloud Contact Center" in my project. but still getting the error:

"status": "PERMISSION_DENIED", 
    "message": "Cloud Contact Center has not been used in project 407408718192 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudcontactcenter.googleapis.com/overview?project=407408718192 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.", 
    "code": 403,

**Comment by ederrafo** [comment]
> I'm having an issue using this gem within a Rails app. Starting from a fresh Rails app, adding this gem and configuring the OAuth builder for my Google app, I receive this error upon callback from Google:
> 
> OAuth2::Error
> {"errors"=>[{"domain"=>"usageLimits", "reason"=>"accessNotConfigured", "message"=>"Access Not Configured. Please use Google Developers Console to activate the API for your project."}], "code"=>403, "message"=>"Access Not Configured. Please use Google Developers Console to activate the API for your project."}: { "error": { "errors": [ { "domain": "usageLimits", "reason": "accessNotConfigured", "message": "Access Not Configured. Please use Google Developers Console to activate the API for your project." } ], "code": 403, "message": "Access Not Configured. Please use Google Developers Console to activate the API for your project." } }
> 
> I have verified that this gem works in a similar Sinatra app, using the same Google app. Any insight would be appreciated. Thanks.

Thanks broder!!!
