### ISSUE TITLE
"Authentication failure! invalid_credentials"

### ISSUE THREAD

**Issue by djoos** [zquestz/omniauth-google-oauth2#118]
Hi there,

I'm making use of v0.2.4, but keep on getting "Authentication failure! invalid_credentials"...

The credentials I provided (Client ID + Client secret) are _definitely_ correct, though I keep on running into the following error after "Request phase initiated" and "Callback phase initiated":

```
omniauth: (google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, {"errors"=>[{"domain"=>"global", "reason"=>"insufficientPermissions", "message"=>"Insufficient Permission"}], "code"=>403, "message"=>"Insufficient Permission"}
```

Hoping you could point me in the right direction...
Thanks in advance for your feedback!

Kind regards,
David

**Comment by PandaWhisperer** [comment]
+1. This is what finally made it work for me too. Didn't find this information in the README. Maybe it needs to be highlighted?

**Comment by PandaWhisperer** [comment]
Oh damn, it's right there at the top, but I still missed it. Maybe make it bigger? Or how about a Troubleshooting section?

**Comment by subimage** [comment]
FWIW, I was also having this issue and the only way I could solve it was by changing this...

```
gem 'omniauth-google-oauth2'
```

...to this...

```
gem 'omniauth-google-oauth2', github: 'zquestz/omniauth-google-oauth2', branch: 'v0.2.10'
```

...Which had the following effects on my Gemfile.lock

+  remote: git://github.com/zquestz/omniauth-google-oauth2.git
    +  revision: 80f8bb509f9675a4f0b6827e097fd2b2f0558df8
    +  branch: v0.2.10
    +  specs:
    +    omniauth-google-oauth2 (0.2.10)
    +      addressable (~> 2.3)
    +      jwt (~> 1.0)
    +      multi_json (~> 1.3)
    +      omniauth (>= 1.1.1)
    +      omniauth-oauth2 (~> 1.3.1)
    +
     GEM
       remote: http://rubygems.org/
       specs:
    @@ -138,7 +150,7 @@ GEM
           multi_json (~> 1.3)
           thread_safe (~> 0.1)
           tzinfo (~> 0.3.37)
    -    addressable (2.3.6)
    +    addressable (2.3.8)
         amazon-ecs (2.2.5)
           nokogiri (~> 1.4)
           ruby-hmac (~> 0.3)
    @@ -357,16 +369,10 @@ GEM
           rack (~> 1.0)
         omniauth-facebook (3.0.0)
           omniauth-oauth2 (~> 1.2)
    -    omniauth-google-oauth2 (0.2.8)
    -      addressable (~> 2.3)
    -      jwt (~> 1.0)
    -      multi_json (~> 1.3)
    -      omniauth (>= 1.1.1)
    -      omniauth-oauth2 (>= 1.1.1)
         omniauth-oauth (1.1.0)
           oauth
           omniauth (~> 1.0)
    -    omniauth-oauth2 (1.4.0)
    +    omniauth-oauth2 (1.3.1)
           oauth2 (~> 1.0)
           omniauth (~> 1.2)
         omniauth-twitter (1.2.1)

**Comment by zquestz** [comment]
You shouldn't need to use the git repo, the new release has been pushed.

**Comment by michaelklem** [comment]
@subimage Thank you! Your solution was the only solution that worked for me. Using Rails 4.2.4 and Ruby 2.2.2p95, in my Gemfile, specifying gem 'omniauth-google-oauth2' would show these in my Gemfile.lock file:

    omniauth-google-oauth2 (0.2.8)
      addressable (~> 2.3)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      omniauth (>= 1.1.1)
      omniauth-oauth2 (>= 1.1.1)


If I update the Gemfile to use:
gem 'omniauth-google-oauth2', github: 'zquestz/omniauth-google-oauth2', branch: 'v0.2.10'

Then my Gemfile.lock file:
  remote: git://github.com/zquestz/omniauth-google-oauth2.git
  revision: 80f8bb509f9675a4f0b6827e097fd2b2f0558df8
  branch: v0.2.10
  specs:
    omniauth-google-oauth2 (0.2.10)
      addressable (~> 2.3)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      omniauth (>= 1.1.1)
      omniauth-oauth2 (~> 1.3.1)

**Comment by subimage** [comment]
@zquestz unfortunately I had to, as bundle updating was not grabbing the latest?

**Comment by michaelklem** [comment]
Correct. Bundle was getting older version.

**Comment by LucasCioffi** [comment]
I also experienced this issue this week out of the blue, even without making any recent changes to `omniauth.rb` and even though it was working fine for many months:
```
Started GET "/auth/google_oauth2/callback?state=abc&code=4/xyz" for [my ip address] at 2016-01-08 04:05:35 +0000
(google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, redirect_uri_mismatch: 
{
  "error" : "redirect_uri_mismatch"
}
```

Although I did go to the Google Developer Console today and accept the new terms of service (as suggested in a comment above), I was able to resolve the error by changing the `omniauth-google-oauth2` line in my gemfile to include this (without having to edit the redirect URI's in the Google Developer Console):
```gem 'omniauth-google-oauth2', github: 'zquestz/omniauth-google-oauth2', branch: 'v0.2.10'```

**Comment by skunkworker** [comment]
This finally fixed it for me as well. Though I am confused on why exactly it is necessary even when using youtube. As in the playground I can get it to authenticate without having the google+ api there.

**Comment by vajapravin** [comment]
"Contacts API" and "Google+ API" were not enabled. Added them and working like charm!
