### ISSUE TITLE
Hybrid Authentification returning null 

### ISSUE THREAD

**Issue by nicohvi** [zquestz/omniauth-google-oauth2#122]
I'm trying to use the Hybrid Authentification, but the response I get from the Google Plus API is always `null`.

```
$ ->
  Q($.ajax(
    url:'https://apis.google.com/js/client:plus.js?'
    dataType: 'script'
    cache: true
    )
  )
  .then(
    ->
      initGoogleAuth()
      console.log 'Google oauth loaded.'
  )
  .fail(
    (error) ->
      console.log 'failed to initialize Google oauth, are you online brah?'
  )

@initGoogleAuth = ->
  $('.google').on 'click', (event) ->
    event.preventDefault()
    gapi.auth.authorize({
      immediate: true
      response_type: 'code'
      cookie_policy: 'single_host_origin'
      client_id: '<my client-id>'
      scope: 'email profile'
    }
    ,
      (response) ->
        # response is null
    )
```

Anything in particular I am doing wrong/misunderstanding?

**Comment by krzcho** [comment]
such immediate toggle works fine (however in my case it is true then false) but now has anyone a clue how to work with account selection (prompt: select_account)?

**Comment by mmahalwy** [comment]
@gkopylov & @raidred is this the best way to do that? Has anything changed to make this better?

**Comment by raldred** [comment]
@mmahalwy I never found a solution unfortunately.
I switch to using omniauth-gplus

**Comment by gkopylov** [comment]
@mmahalwy I think it is not related to this gem. As you can see it is just a client side flow.

Unfortunately, when I posted solution above, I didn't take a close look into official google implementation and just experimented with code in the readme. So when you look at official google readme https://developers.google.com/api-client-library/javascript/features/authentication#Authexample you can find that there are also two authorize actions with immediate false and immediate true.

**Comment by zquestz** [comment]
K after looking into this again, it seems clear the path forward. I am going to put in some fixes for the README. Will close once this is updated.
