### ISSUE TITLE
Need to force jQuery to send the 'X-Requested-With': 'XMLHttpRequest' header to activate hybrid flow.

### ISSUE THREAD

**Issue by benguillet** [zquestz/omniauth-google-oauth2#125]
The `request.xhr?` would resolve to false by default: https://github.com/zquestz/omniauth-google-oauth2/blob/master/lib/omniauth/strategies/google_oauth2.rb#L70 

Even though I was doing the request from a different domain and using CORS.

**Comment by matixmatix** [comment]
@benguillet I wish you did it, I lost several hours of debugging due to this issue as well! I just opened a pull request to add this to README.
