### ISSUE TITLE
redirect_uri_mismatch with Rails 4.1

### ISSUE THREAD

**Issue by TimKJones** [zquestz/omniauth-google-oauth2#131]
I'm trying to debug a redirect_uri_mismatch error.  I've followed the setup in the readme.  My client-side flow to obtain a token from Google seems to be correct.  Additionally, I can complete the flow by pointing my browser to the redirect url.  However, when posting to the redirect url with javascript using the token received via Google's javascript authentication, I always get a redirect_uri_mismatch error.  

I'm on Rails 4.1.  Are there any known bugs with this version?  Thanks for the help!

**Comment by krzcho** [comment]
anyone can try with this: https://github.com/zquestz/omniauth-google-oauth2/issues/181#issuecomment-114635065

**Comment by teamgonuts** [comment]
Had this same issue with my rails-4 application. The solution was to disable turbo-links for the request, as that was causing it to be ajax:

<a href="<%= user_omniauth_authorize_path(:google_oauth2) %>"
        class="btn btn-block btn-social btn-google btn-lg"
        data-no-turbolink="true">
        <i class="fa fa-google"></i> Sign up with Google
    </a>
