### ISSUE TITLE
Refresh Token / Consent Page

### ISSUE THREAD

**Issue by ssteeg** [zquestz/omniauth-google-oauth2#134]
I'm writing an application that lets a user sign in to Google using OmniAuth. Everything is working fine, but I have a question related to refresh tokens.

Here is my configuration: 

``` ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2,
    Rails.application.config.signin[:google][:client_id],
    Rails.application.config.signin[:google][:client_secret],
    {
      name: 'google',
      scope: 'email, youtube',
      prompt: 'consent'
    }
end
```

With this configuration, the user clicks the login link, they select their appropriate Google account and then click "Accept" to the "This app would like to have offline access" message. After doing this steps, a valid refresh token is returned and can be saved. 

At this point, our system has the oauth record, including refresh token. If the user comes back to the site again and clicks login, they have to go through the entire process and click "Accept" to the offline access message.

Is there any way to avoid showing the Consent Prompt to the user everytime? 

I tried removing the prompt line in the config, and the Consent Prompt wasn't show, but the refresh token wasn't returned. :confused: From the documentation: `Note that if you need a refresh token, google requires you to also to specify the option prompt: 'consent', which is not a default.`

It seems like there are two possible paths:
1. Always show the consent screen and get a refresh token
2. Don't show the consent screen and don't get a refresh token

Any ideas?

Thanks,
Scott

**Comment by daniel-nelson** [comment]
Sorry to comment on a closed issue, but I've had this issue bookmarked for some months and am finally getting around to implementing it (actually, #2 from https://github.com/zquestz/omniauth-google-oauth2/issues/9#issuecomment-26525644). But it seems I'm now able to refresh offline tokens for offline access without the `prompt: 'consent'`. The first time a user authenticates, Google automatically prompts without my specifying `prompt: 'consent'`. Has Google perhaps changed how this works?
