### ISSUE TITLE
No birthday value

### ISSUE THREAD

**Issue by samozeleznik** [zquestz/omniauth-google-oauth2#136]
I do not get back the birthday value (not even if it is made public in the google+ account).
My scope is:
scope: "email, profile, plus.me, http://gdata.youtube.com"

**Comment by hsaini734** [comment]
I am facing the similar issue and need to know, Is there any workaround to retrieve date of birth? 
I am able to fetch date of birth in android and ios platforms but not in my rails web app? Why so ?

**Comment by xsannyx** [comment]
No, no solution so far unfortunately. Google just doesn't support it any more apparently.

**Comment by thor-hammer** [comment]
Well, I was able to get birthday using another gem (https://github.com/seejohnrun/google_plus). So, when I get token and all other data, I do another request to google via that gem, something like
obj = GooglePlus::Person.get('me', :access_token => access_token)
and then I can get birthday as 
obj.attributes['birthday']
Ugly solution but it works for me.

**Comment by pramodshinde** [comment]
Its not necessary to add any gem to get profile info, you can get birthday & additional profile info with following api end-point

```ruby
client = OAuth2::Client.new('app_id', 'app_secret')
access_token = OAuth2::AccessToken.new(client, 'access_token')
profile_api_url = 'https://www.googleapis.com/plus/v1/people/me'
response = access_token.get(profile_api_url)
response = JSON.parse(response.body)
```
Note: `access_token` is received in auth_hash.
If you see response it will have [these](https://developers.google.com/+/web/api/rest/latest/people#resource) fields.

**Important:** Make sure your `birthday` is public and you must pass `plus.login` scope while authorizing user for more info visit [this](https://developers.google.com/+/web/api/rest/latest/people#resource).

**Comment by thor-hammer** [comment]
pramodshinde, thanks for your reply! I'll try it.

**Comment by PirunSeng** [comment]
Hi!

Late in the discussion, but I just want to give :+1: to pramodshinde since his solution fixes my problem as this original posted issue.

**Comment by ganbootyard** [comment]
2019 and I confirm @pramodshinde 's solution still works but with some minor updates.
Did
`profile_api_url = 'https://people.googleapis.com/v1/people/me?personFields=birthdays'`
instead of his
`profile_api_url = 'https://www.googleapis.com/plus/v1/people/me'`

There could be something wrong with my API settings, but I also suspect this is because of Google's decision with Google+ a few months ago.

Also, it could possibly help to add `user.birthday.read` in your scopes.
