### ISSUE TITLE
CSRF error

### ISSUE THREAD

**Issue by rpechayr** [zquestz/omniauth-google-oauth2#138]
Hello, 

I am using this gem to handle google oauth authentication and I encountered a strange behaviour. 
When I authenticate with google, everything works fine : redirected to google, consent screen, redirected by to my site, token requested, profile fetched. 
However, ultimately, the code enters a second time in the callback_phase function (from the parent gem), but throws a csrf error. Indeed, the first time the code entered in this method, the omniauth.state variable has been removed : 
https://github.com/intridea/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L72

Am I doing something wrong ? Any help would be appreciated. 

Regards,

Romain

**Comment by krzcho** [comment]
still nothing else than ignoring state?

**Comment by gkopylov** [comment]
@krzcho I solved that problem thereat by implementing omniauth state by myself, so you can do this:
```
class ApplicationController < ActionController::Base
  before_action :initialize_omniauth_state
  
  protected

  def initialize_omniauth_state
    session['omniauth.state'] = response.headers['X-CSRF-Token'] = form_authenticity_token
  end
...
```
and then add ```skip_before_filter :verify_authenticity_token``` in your omniauth callback controller because it is already verified by omniauth state.

**Comment by gkopylov** [comment]
@zquestz maybe it worth to add this in the readme file?

**Comment by zquestz** [comment]
Would be great to have a PR provided to update the README. This would definitely be beneficial.

**Comment by gkopylov** [comment]
@zquestz done.

**Comment by johnsonyeap** [comment]
@gkopylov, I noticed the README stated:

_"And then you need to add :provider_ignores_state => true in your omniauth initializer."_

Is that right?

**Comment by vmvwebworks** [comment]
By the way, something new about that? good solution?
