### ISSUE TITLE
Incremental authorization, or using :include_granted_scopes to ask for additional permissions at runtime?

### ISSUE THREAD

**Issue by kbighorse** [zquestz/omniauth-google-oauth2#143]
Is there a way to ask for basic permissions (profile, email) at login time, and then ask for another permission, (e.g. Google Drive), in a later action? Everything I see locks down a list of permissions to ask for at application initialize time. Apologies if I'm missing it somewhere in the docs.

Perhaps if not, is there a way to configure more than one Google OAuth application with different permissions?

Thank you in advance.

Relevant section in README:
https://github.com/zquestz/omniauth-google-oauth2#configuration

**Comment by Onumis** [comment]
Not sure what changed meanwhile, but this seems to also work:
```
  config.omniauth :google_oauth2,
                  Rails.application.credentials.oauth[:google_id],
                  Rails.application.credentials.oauth[:google_secret],
                  access_type: 'offline',
                  scope: 'email profile',
                  include_granted_scopes: true

###

user_google_oauth2_omniauth_authorize_url(scope: 'gmail.send, gmail.compose, gmail.modify, gmail.readonly')
```
