### ISSUE TITLE
Authentication failure! invalid_credentials

### ISSUE THREAD

**Issue by millerpils** [zquestz/omniauth-google-oauth2#149]
Hi guys,

I'm new to this stuff and a bit stumped with this error. I've been given a Rails Oauth project that currently uses LinkedIn (works a treat) and needs extending to Google. When the code hits the callback phase, the error below is thrown:

ERROR -- omniauth: (google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, invalid_request: Missing required parameter: code

We're using a YAML file to power the configuration options and the ID and token are clearly correct and valid, taken direct from Google Console.

Here's the builder as it stands:

```
use OmniAuth::Builder do
      provider :google_oauth2, Settings.google_client_id,  Settings.google_client_secret, { access_type: "offline", approval_prompt: "", provider_ignores_state: true }
 end
```

Any clues?

**Comment by TiGaI** [comment]
Hi Millerpils can you tell me what type of internal issue was it? My website, www.pregreat.com is having the same issues.
