### ISSUE TITLE
Can't make Hybrid auth work. Code param is missing

### ISSUE THREAD

**Issue by laurynasra** [zquestz/omniauth-google-oauth2#153]
Hello!

I was trying to make a hybrid auth. I am able to retrieve a code param from google api in client side but when i do post to /users/auth/google_oauth2/callback it goes to the failure method, and in console i can see this:

```
I, [2014-10-28T17:48:58.220414 #54603]  INFO -- omniauth: (google_oauth2) Callback phase initiated.
17:48:58 web.1    | E, [2014-10-28T17:48:58.617783 #54603] ERROR -- omniauth: (google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, invalid_request: Missing required parameter: code
17:48:58 web.1    | {
17:48:58 web.1    |   "error" : "invalid_request",
17:48:58 web.1    |   "error_description" : "Missing required parameter: code"
17:48:58 web.1    | }
17:48:58 web.1    | Invalid credentials
```

then the failure template gets returned to the ajax post call.

The credentials are set correctly as pure server side auth was working before. Code param can be seen in dev tools before sending to the rails.

Client side request coffee snippet:

```
gapi.auth.authorize({
      # immediate: true,
      response_type: 'code',
      cookie_policy: 'single_host_origin',
      client_id: '...',
      scope: 'email'
    }, 
    (response) ->
      if (response && !response.error)
        # // google authentication succeed, now post data to server and handle data securely
        $http.post(
          "/users/auth/google_oauth2/callback",
          response
        ).then( 
```

response object includes code property.

Gems versions:
devise (3.4.0)
omniauth (1.2.2)
omniauth-google-oauth2 (0.2.5)
omniauth-oauth2 (1.2.0)

Update:
i tried to track outgoing rails app requests to check whether or not the code is sent to google from server side. It seems that OmniauthCallbacksController#failure is being executed in the first place and no server side requests to google api is being made.

**Comment by lizbaillie** [comment]
Thanks for making this gem!

I'm experiencing this error right now and the patch doesn't seem to work, though I may be implementing it incorrectly. I forked this repo and placed @snovity's patch at the bottom of `lib/omniauth/strategies/google_oauth2.rb`, but still get the `"Missing required parameter: code"` error. 

When I put a `binding.pry` on the first line of `callback_phase_with_json` I see that `['action_dispatch.request.request_parameters']` is `nil`, and when I exit the pry session I get the error. I'm sure I'm just doing something slightly wrong, does anyone have any ideas?

Any help is appreciated!

**Comment by pigoz** [comment]
This monkeypatch works for me on version 0.5.0 (only touches this gem and not omniauth as the previous one)

```
module OmniAuth
  module Strategies
    class GoogleOauth2
      def get_access_token(request)
        json = JSON.parse(request.body.read)
        json = json.dup.deep_transform_keys { |key| key.to_s.underscore }
        raise "invalid token '#{json['access_token']}'" unless verify_token(json['access_token'])
        ::OAuth2::AccessToken.from_hash(client, json)
      end
    end
  end
end
```
