### ISSUE TITLE
Include way to specify the cert to use

### ISSUE THREAD

**Issue by parkr** [zquestz/omniauth-google-oauth2#159]
Some platforms have the certificates placed strangely. I looked at https://github.com/intridea/omniauth/pull/479 which said it was strategy-specific. Would you mind adding a configuration option for this? Is that a possibility?

Prompted by https://github.com/brightroll/screens/pull/14/files#r22837247 /cc @sodabrew

**Comment by zquestz** [comment]
I am open to PR's. =)

**Comment by zquestz** [comment]
I believe this is taken care of in the omniauth gem, however you just pass the client options to the strategy to actually set it. I don't see any special handling of this in omniauth-twitter or omniauth-facebook.
