### ISSUE TITLE
How to add the openid_shutdown_ack parameter?

### ISSUE THREAD

**Issue by jakeonrails** [zquestz/omniauth-google-oauth2#160]
https://developers.google.com/accounts/docs/OpenID#shutdown-timetable says to add the `openid_shutdown_ack` parameter to extend the timeline where users are not shown the warning about the shutdown.

How do I achieve this using this gem?

I've just spent far too long mucking around in the source code of omniauth, omniauth-openid and omniauth-oauth2 and it's not obvious at all where/how to pass this parameter along.

**Comment by zquestz** [comment]
This would just need to be added to the allowed parameters list in the gem. Then you can just pass it through the auth link url.

**Comment by zquestz** [comment]
I don't think this actually effects us. I don't hit the endpoints in question.

**Comment by jakeonrails** [comment]
Thanks, I'll give that a shot!
