### ISSUE TITLE
change credentials -> token to access_token

### ISSUE THREAD

**Issue by adbatista** [zquestz/omniauth-google-oauth2#161]
I'm using the [google-api-ads-ruby](https://github.com/googleads/google-api-ads-ruby), who uses signet and I saw that the keys in the credentials hash follows the token name pattern used in [signet](https://github.com/google/signet/blob/08961df954e8b53d3ae784f500f160b9900c6150/lib/signet/oauth_2/client.rb#L209-L226) except the `token` key, named `access_token` in signet;

My idea is rename the credentials -> token to access_token, in order to make more compatible with other google gems

**Comment by zquestz** [comment]
Where exactly did you want to change this? A PR to see it would be nice.
