### ISSUE TITLE
image_size setting is ignored

### ISSUE THREAD

**Issue by hajder** [zquestz/omniauth-google-oauth2#166]
Due to typo in the image url the image_size setting is ignored. Current url is:

    https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M//photo.jpg?sz=50

and should be

    https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=50

(mind single slash before `photo.jpg`)

**Comment by zquestz** [comment]
Can you provide a bit more context... as size options should be in the url not a query param. Or maybe write a test illustrating the bug?

**Comment by zquestz** [comment]
I think I understand now. I assume google is providing the bad url with 2 //'s? As we don't generate this url? It just just when we add the sizing options we get an extra slash and hit a 404?

**Comment by hajder** [comment]
Yes, that's exactly it - url  seems to be generated with double slash and Google doesn't like it and returns 404

**Comment by olivierlacan** [comment]
It seems like this issue is re-occuring but not due to a URL issue anymore. I receive:

```
https://lh6.googleusercontent.com/-lDP57qXndCU/AAAAAAAAAAI/AAAAAAAEeVQ/M3c432SPq4I/s160-c/photo.jpg?sz=50
```

Despite having the following configuration:
```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, ENV['GOOGLE_KEY'], ENV['GOOGLE_SECRET'],
  {
    prompt: "select_account",
    image_aspect_ratio: "square",
    image_size: 160
  }
end
```

It looks like the `sz` query parameter needs to be removed (or altered) since it overrides the image size in the avatar URL:

```
s160-c/photo.jpg?sz=50
```

**Comment by timurvafin** [comment]
Confirming the same behaviour.

**Comment by zquestz** [comment]
Yep if someone puts up a PR that would be great. I might be able to get to this in the next couple days otherwise.

**Comment by olivierlacan** [comment]
@zquestz I'm on it. Will be up in a few minutes.
