### ISSUE TITLE
Doesn't work with YouTube

### ISSUE THREAD

**Issue by dtsadok** [zquestz/omniauth-google-oauth2#17]
Hello,

According to the YouTube docs (http://code.google.com/apis/youtube/2.0/developers_guide_protocol_oauth2.html), the library needs to set "scope" to "gdata.youtube.com", and "response_type" to "code" in order for OAuth to work with YouTube.

Is there any way to add that functionality?

Thanks,
Daniel

**Comment by ricvillagrana** [comment]
Anyone knows how can I get YouTube Channel information with this data?
