### ISSUE TITLE
It's not work today after I have made bundle update

### ISSUE THREAD

**Issue by laddhadhiraj** [zquestz/omniauth-google-oauth2#171]
I have integrated this in my website which is running on rails '4.1.5' .
 after making bundle update today I am not able to authenticate by google. 
I have looked on google and I find other google auth gem goes updated may be some update happen in google auth process, so guys can you check and let me know why our 'omniauth-google-oauth2' is not working after bundle update.

updated other gem version today... 
https://rubygems.org/gems/googleauth
https://rubygems.org/gems/google-api-client

Please let me know how can I fix google authentication  issue in  my website

**Comment by zquestz** [comment]
I would need more information to debug this. Do you have the error message you are getting?

**Comment by zquestz** [comment]
I have just confirmed that I can login with the rails 4.1.x series and sinatra apps. Reopen this ticket when you provide more info.
