### ISSUE TITLE
Not working with override callback_uri

### ISSUE THREAD

**Issue by ptuchster** [zquestz/omniauth-google-oauth2#172]
For example my app configured to redirect by default to http://my.app/auth/google_oauth2/callback
It works like a charm. But now I need to override  callback_uri not on whole app but only for couple scopes. For example I want to make my callback controller respond to js format. First i had change the href of login link to user_omniauth_authorize_path('google_oauth2', redirect_uri: "http://my.app/auth/google_oauth2/callback**.js**"). And it's generate right link, and it's added in google app credentials, and it actually redirects to http://my.app/auth/google_oauth2/callback**.js**, and I have in my callback controller 

    respond_to do |format|
      format.html do
        redirect_to root_path, notice: "Nice!"
      end
      format.js { render :json => response }
    end

What is perfectly working. BUT there is no request.env["omniauth.auth"]. It's nill. When I'm changing it back to http://my.app/auth/google_oauth2/callback (without JS) it starts to work. But it's rendering whole site that is not satisfied my goals.

The only way to do that now through omniauth_authorize_path('google_oauth2', format: 'js') and then handle it with request.env["omniauth.params"]

**Comment by zquestz** [comment]
This isn't a unique problem for this gem. I think you need to open this request against the official omniauth gem. I don't do anything specific in this gem that would prevent this flow from working.
