### ISSUE TITLE
Security Error with the Hybrid Authentication flow

### ISSUE THREAD

**Issue by MartinsTiago** [zquestz/omniauth-google-oauth2#174]
I used the code on the readme file, to make my authentication flow by javascript. I couldn't get it working by letting the 'imediate' option as 'true', so I set it to 'false'. Doing this change, I got this error, on my browser console:

Uncaught SecurityError: Blocked a frame with origin "https://localhost:3000" from accessing a frame with origin "https://accounts.google.com". Protocols, domains, and ports must match.

Can you guys help me out with this?

**Comment by movstox** [comment]
@MartinsTiago you can probably try this as a quick workaround: http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by zquestz** [comment]
@MartinsTiago can you give me the error you are getting when immediate is set to 'true'? This should work for you and avoid the error you are seeing.

**Comment by krzcho** [comment]
the problem is when you are logged on multiple google accounts and account selection dialog is brought even without prompt: select_account; then everything stops with
"Uncaught SecurityError: Blocked a frame with origin..."

**Comment by krzcho** [comment]
even with a single account it fails - basically I am not able to go through consent stage

**Comment by MartinsTiago** [comment]
I'm getting the following error when I set the authentication to true:

XMLHttpRequest cannot load https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=4162…Fwww.googleapis.com%2Fauth%2Fplus.circles.members.read&access_type=offline. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

I guess that I can't make an ajax call from different domains, since I'm getting the response from the google API, and making a ajax call to my callback controller. 

I tried to use the window.location js method, as I'm doing on my FB sign-up, but this workaround doesn't work when the application is running on an iframe (mine does)...

So, what should I do to send the response to controller, from my js file?

**Comment by gkopylov** [comment]
@MartinsTiago I also had the same problem half-year ago(and there was also "Uncaught SecurityError: Blocked a frame with origin..." and "No 'Access-Control-Allow-Origin' header...") and you can try my solution for this https://github.com/zquestz/omniauth-google-oauth2/issues/122#issuecomment-60510241

Maybe it is worth to add into readme file too...

**Comment by zquestz** [comment]
Anyone have updates on this issue?

**Comment by zquestz** [comment]
I have posted updated samples for the hybrid auth flow. They are directly from the examples provided by google. If you continue to have issues we can reopen this issue.

**Comment by shaqonline** [comment]
I had similar problem. The solution is here: http://stackoverflow.com/questions/25065194/google-sign-in-uncaught-securityerror

You should put:
```
delete response['g-oauth-window'];
```
just before AJAX'ing result.
