### ISSUE TITLE
state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by tpitale** [zquestz/omniauth-google-oauth2#175]
Gem versions in my bundle all appear to be latest:
  * omniauth (1.2.2)
  * omniauth-google-oauth2 (0.2.6)
  * omniauth-oauth2 (1.2.0)
  * oauth2 (1.0.0)
  * faraday (0.9.1)

Using ruby 2.2.2.

```
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

Not sure if this is an error in omniauth, faraday, or net/http … but this is broken … but only in development. I'm at a complete loss as to what is going on.

This happens during the callback from google.

**Comment by tpitale** [comment]
Tried downloading http://curl.haxx.se/ca/ca-bundle.crt into $(brew --prefix)/etc/openssl/certs/

**Comment by tpitale** [comment]
My omniauth config:

```ruby
options = {
  :name => "google",
  :scope => "email, profile",
  :prompt => "select_account",
  :image_aspect_ratio => "square",
  :image_size => 50
}

if !Rails.env.production?
  options.merge!({
    :client_options => {
      :ssl => {
        :ca_path => "/usr/local/etc/openssl/certs"
      }
    }
  })
end

Rails.application.config.middleware.use OmniAuth::Builder do
  provider(:google_oauth2, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, options)
end
```

**Comment by tpitale** [comment]
Also needed to explicitly set the :ca_file like this:

```ruby
  options.merge!({
    :client_options => {
      :ssl => {
        :ca_file => "/usr/local/etc/openssl/certs/ca-bundle.crt",
        :ca_path => "/usr/local/etc/openssl/certs"
      }
    }
  })
```

**Comment by hayesr** [comment]
Thanks for writing about this! After I found this, I also found more info on the [Devise wiki](https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview#openssl).
