### ISSUE TITLE
Protocol for redirect_url incorrect

### ISSUE THREAD

**Issue by constantm** [zquestz/omniauth-google-oauth2#179]
The `redirect_uri` that gets passed to Google uses `http` instead of `https`, while it originates from a `https` domain. Is there somewhere I need to set this, or this potentially a big? I had a look through the code and I'm not much closer to finding a solution.

```
https://accounts.google.com/o/oauth2/auth?scope=email+profile&response_type=code&redirect_uri=http://domain.com/users/auth/google_oauth2/callback&access_type=offline&state=6d8729a3dbaec306f7fd512298869cab1229981ae587fcbe&client_id=REMOVED&hl=en&from_login=1&as=-1f0eb8600f163211&pli=1&authuser=0
```

**Comment by constantm** [comment]
A fix for this is to manually set the domain and protocol in the omniauth initialiser. Strangely enough this isn't a problem when using the `omniauth-facebook` gem.

`OmniAuth.config.full_host = Rails.env.production? ? 'https://domain.com' : 'http://localhost:3000'`

**Comment by zquestz** [comment]
Thanks for the info. Any chance on a small PR to add this to the README?

**Comment by constantm** [comment]
Sure. Doesn't this feel really hacky though?

**Comment by sahin** [comment]
+1

**Comment by sahin** [comment]
We have https in movielala.com, but this is a cloudflare https, so internally all requests get ssl termination . We have the same problem. but in tumblr, facebook, twitter, it works great.

**Comment by zquestz** [comment]
Updated the docs. Closing. If more needs to be done we can reopen this ticket.

**Comment by constantm** [comment]
Sorry for not submitted that PR! I was hoping somebody would come up with a less hacky fix. :)

**Comment by zquestz** [comment]
No worries, at least we have the workaround documented. =)
