### ISSUE TITLE
One-time Code Flow (Hybrid Authentication)

### ISSUE THREAD

**Issue by mmahalwy** [zquestz/omniauth-google-oauth2#180]
On the *One-time Code Flow (Hybrid Authentication)* there isn't an example of what the action should look like that handles the post request and what to expect when `console.log` that requestion.

Here is what it is:
```
code: "SOME_CODE_FROM_GOOGLE"
cookie_policy: "single_host_origin"
expires_at: "1432424738"
expires_in: "86400"
g_user_cookie_policy: "single_host_origin"
issued_at: "1432338338"
```

This is the code, but now what?

**Comment by gkopylov** [comment]
The action that handle post request should look like as described in this section https://github.com/zquestz/omniauth-google-oauth2#devise :

```
def google_oauth2
...
end
```

So, when you are using only client-side flow, you need to add in this action something like this:
```
sign_in('user', user)
render :json => { :some => 'information about user' }, :status => 200
```
After this you can parse that json in your js and update current page or redirect user to something else page.

**Comment by mmahalwy** [comment]
@gkopylov what if i am not using devise with omniauth?

**Comment by gkopylov** [comment]
Then you need to create this route with callback and implement user authentication by yourself.
