### ISSUE TITLE
redirect_uri_mismatch

### ISSUE THREAD

**Issue by mmahalwy** [zquestz/omniauth-google-oauth2#181]
No matter what I do, I cannot escape it and I cannot escape the redirect_uri being different.

Here is my omniauth.rb
```
require 'awesome_print'
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, Rails.application.secrets[:google_client_id], Rails.application.secrets[:google_client_secret],
  {
    name: 'google',
    scope: 'email profile https://www.googleapis.com/auth/contacts.readonly',
    prompt: 'select_account',
    access_type:  'offline',
    # redirect_uri: 'postmessage',
    provider_ignores_state: true, # BAD, TODO: https://github.com/intridea/omniauth-oauth2/issues/58
    setup: (lambda do |env|
      request = Rack::Request.new(env)
      env['omniauth.strategy'].options['redirect_uri'] = 'http://townsquared.com:3000/auth/google/callback12123123123'
      Rails.logger.ap env['omniauth.strategy'].inspect
      Rails.logger.ap env['omniauth.strategy'].options

    end)
  }
end
```

My client:
```
gapi.auth.authorize({
        client_id: 'CLIENTID,
        scope: 'email profile https://www.googleapis.com/auth/contacts.readonly',
        immediate: false,
        cookie_policy: 'single_host_origin',
        response_type: 'code'
      }, function(response) {
        return gapi.auth.authorize({
          client_id: 'CODE,
          scope: 'email profile https://www.googleapis.com/auth/contacts.readonly',
          immediate: true,
          cookie_policy: 'single_host_origin',
          response_type: 'code'
        }, function(response) {
          if (response && !response.error) {

            response.redirect_uri = 'http://townsquared.com:3000/auth/google/callback';
            console.log(response);
            $http.get('/auth/google/callback', {params: response}).then((r) => {
              console.log(r.data);
            });
          }
        });
      });
```

Firstly, I ran into the CSRF problem, which `provider_ignores_state` solved for the time being. Now I cannot escape the `redirect_uri_mismatch`. In my request, I can set `redirect_uri` as BLAH and still get this request to google:

```
  HTTP POST (45.93ms)   https://accounts.google.com:443/o/oauth2/token
  Request body   client_id=CLIENTID&client_secret=CLIENTSECRET&code=4%2FxwsEFz5g2sSYkaHAvksApQcPe3pd0FPCk2c3gduakho.wsWDhoI5BeMbXmXvfARQvtiMkhr_mgI&grant_type=authorization_code&redirect_uri=http%3A%2F%2Ftownsquared.com%3A3000%2Fauth%2Fgoogle%2Fcallback
  Response status   Net::HTTPBadRequest (400)
  Response body   {
  "error" : "redirect_uri_mismatch"
}
App 50330 stdout: E, [2015-05-23T02:54:36.534528 #50330] ERROR -- omniauth: (google) Authentication failure! invalid_credentials: OAuth2::Error, redirect_uri_mismatch:
App 50330 stdout: {
App 50330 stdout:   "error" : "redirect_uri_mismatch"
App 50330 stdout: }

OAuth2::Error (redirect_uri_mismatch:
{
  "error" : "redirect_uri_mismatch"
}):
```

It's ALWAYS `http%3A%2F%2Ftownsquared.com%3A3000%2Fauth%2Fgoogle%2Fcallback`

Any ideas to why this is happening? 

![image](https://cloud.githubusercontent.com/assets/3749095/7782794/9e1b9aae-00f7-11e5-85bc-87db9dbe1c63.png)

**Comment by mmahalwy** [comment]
I eventually got this fixed. Seems to be a problem with the gem being downloaded. Current version does not have the updated code, more specifically here: https://github.com/zquestz/omniauth-google-oauth2/blob/master/lib/omniauth/strategies/google_oauth2.rb#L91

I had to put the git repo in my gemfile for it to work. Should change the version number!

**Comment by krzcho** [comment]
I got the same issue. I have updated gemfile to use:
gem "omniauth-google-oauth2", :git => 'https://github.com/zquestz/omniauth-google-oauth2', :branch => 'master'
but it still fails with the same redirect_uri_mismatch; any hint Mohamed?

**Comment by mmahalwy** [comment]
Yeah, the problem is gem versioning. You have to point to the github repo

**Comment by krzcho** [comment]
I did. I made sure it is using master git repo but it still fails. Google is doing the callback but it is rails which is raising "redirect_uri_mismatch" error on the console. Pulling my hair now...

**Comment by krzcho** [comment]
Ahh - and I am not doing a javascript based call - i go through server (I was not able to bypass browser's security alerts) so it is a bit different setup

  config.omniauth :google_oauth2,
	"....apps.googleusercontent.com",
	"...",
	{
		:client_options => { :ssl => { :ca_file => 'C:\Ruby21\cacert.pem'}},
                :provider_ignores_state => true,
		:redirect_uri => 'https://.../users/auth/google_oauth2/callback',
                :prompt => "select_account"
	}

**Comment by krzcho** [comment]
ok, case closed
I receive a code but the error comes from initiating stage 2/server asking google for the token
solution is to add a token param (not yet sure if there is a more elegant way but i am already tired):
```
  {
    :client_options => { :ssl => { :ca_file => 'C:\Ruby21\cacert.pem'}},
    :provider_ignores_state => true,
    :redirect_uri => 'https://.../users/auth/google_oauth2/callback',
    :prompt => "select_account",
    setup: (lambda do |env|
      request = Rack::Request.new(env)
      env['omniauth.strategy'].options['token_params'] = {:redirect_uri => 'https://.../users/auth/google_oauth2/callback'}
    end)
	}

**Comment by zquestz** [comment]
The original poster solved his issue. Closing.

**Comment by BrandonMathis** [comment]
Hi all, I've been trying to get omniauth to work with my client-side ember app as well and this thread has been an invaluable resource of information :) I was able to get pretty far but I cannot get past this same `redirect_uri_missmatch` error.

I have an ember app sitting at `localhost:4200` talking to my rails application at `localhost:3000`. I used @krzcho's snippet above to set my reirect_uri by hand but google is still not happy with it

Is it possible that I cannot overcome the redirect_uri bc my Ember app and Rails API do not shared the same url (`localhost:4200` vs `localhost:3000`)?

```
Started POST "/users/auth/google_oauth2/callback" for 127.0.0.1 at 2015-10-11 19:10:10 -0400
  ActiveRecord::SchemaMigration Load (0.4ms)  SELECT "schema_migrations".* FROM "schema_migrations"
[httplog] Connecting: accounts.google.com:443
[httplog] Sending: POST http://accounts.google.com:443/o/oauth2/token
[httplog] Data: client_id=CLIENT_ID&client_secret=CLIENT_SECRET&grant_type=authorization_code&redirect_uri=http://localhost:3000/users/auth/google_oauth2/callback
[httplog] Status: 400
[httplog] Benchmark: 0.1462040050100768 seconds
[httplog] Response:
{
  "error" : "redirect_uri_mismatch"
}
Processing by Devise::OmniauthCallbacksController#failure as JSON
  Parameters: {"code"=>"4/4Ak2EFg5ul_c_rBegrXIEHeM2F7TviC8EhlqYl0tVd4"}
Completed 500 Internal Server Error in 7ms (Views: 6.1ms | ActiveRecord: 0.0ms)
```

**Comment by krzcho** [comment]
can you post the whole login sequence including client :3000 and :4200 apps?

**Comment by artworx** [comment]
Using  omniauth-google-oauth2 (0.2.8) and the default config from the readme, i was getting these errors:

```
I, [2015-10-22T22:23:50.364873 #25268]  INFO -- omniauth: (google) Callback phase initiated.
E, [2015-10-22T22:23:50.571590 #25268] ERROR -- omniauth: (google) Authentication failure! invalid_credentials: OAuth2::Error, redirect_uri_mis
match: 
{
  "error" : "redirect_uri_mismatch"
}

OAuth2::Error (redirect_uri_mismatch: 
{
  "error" : "redirect_uri_mismatch"
}):
  oauth2 (1.0.0) lib/oauth2/client.rb:113:in `request'
  oauth2 (1.0.0) lib/oauth2/client.rb:138:in `get_token'
  oauth2 (1.0.0) lib/oauth2/strategy/auth_code.rb:29:in `get_token'
  omniauth-oauth2 (1.4.0) lib/omniauth/strategies/oauth2.rb:89:in `build_access_token'
```

I tried the suggestion to add `token_params`

```
setup: (lambda do |env|
      request = Rack::Request.new(env)
      env['omniauth.strategy'].options['token_params'] = {:redirect_uri => 'https://.../users/auth/google_oauth2/callback'}
    end)
```

to request and it works. 

Why do we need to do this manually? Can't the `token_params` be handled by the gem? 
If this `hack` is required in order to use the library then it should probably be documented.

**Comment by Nekromancer** [comment]
I have to agree with @artworx . Such critical issue with library should be at least documented. But i really can't see why it isn't part of gem

**Comment by zquestz** [comment]
The answer is simple. The app often has no idea what the top level domain is. Imaging you are using Nginx and proxying to your app, the app never sees the actual real domain, so you have to put it somewhere. There is no way for the gem to automate this for you. You can either set the redirect uri, or you can set the following which is clearly documented in the README if people bothered to read it:

```
OmniAuth.config.full_host = Rails.env.production? ? 'https://domain.com' : 'http://localhost:3000'
```

**Comment by artworx** [comment]
@zquestz this is the full content of my initializer: 

```
require "omniauth-google-oauth2"

OmniAuth.config.full_host = 'http://localhost:3000' 

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, ENV['GOOGLE_CLIENT_ID'], ENV['GOOGLE_CLIENT_SECRET'], {
    name: 'google',
    scope: 'email, profile, plus.me',
    prompt: 'select_account',
    image_aspect_ratio: 'square',
    image_size: 50,
    setup: (lambda do |env|
      request = Rack::Request.new(env)
      env['omniauth.strategy'].options['token_params'] = {
        redirect_uri: 'http://localhost:3000/auth/google/callback'
      }
    end)
  }
end
```

If i remove the `token_params` i get redirect uri mismatch. The issue is `OmniAuth.config.full_host` seems to be ignored.

**Comment by zquestz** [comment]
What redirect does it send when you only use OmniAuth.config.full_host? That definitely should not be getting ignored.

**Comment by artworx** [comment]
in lib/omniauth/strategies/oauth2.rb:89:in `build_access_token' the value is:

```ruby
callback_url = "http://localhost:3000/auth/google/callback?state=xxxxxxx&code=xxxx
```

**Comment by zquestz** [comment]
Actually the callback definitely should have the state parameter. This looks fine, and that redirect uri should not be mismatched when the query string is present.

**Comment by artworx** [comment]
> Actually the callback definitely should have the state parameter. This looks fine, and that redirect uri should not be mismatched when the query string is present.

google disagrees with that statement:

`full_host + script_name + callback_path + query_string` => `redirect_url mismatch`

`full_host + script_name + callback_path` => `works`

**Comment by Anyoks** [comment]
@zquestz :+1:  Thanks for your answer.
Though, I got a ``` Not found. Authentication passthru ``` error with that setup. I got it working by removing ```  name: 'google' ```line from the code. The result that worked is:

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, ENV['GOOGLE_CLIENT_ID'], ENV['GOOGLE_CLIENT_SECRET'], {
    scope: 'email, profile, plus.me',
    :client_options => { :ssl => { :ca_file => 'C:\Ruby21\cacert.pem'}},
    provider_ignores_state: true,
    redirect_uri: 'http://localhost:3000/users/auth/google_oauth2/callback/',
    prompt: 'select_account',
    image_aspect_ratio: 'square',
    image_size: 50,
    setup: (lambda do |env|
      request = Rack::Request.new(env)
      env['omniauth.strategy'].options['token_params'] = {
        redirect_uri: 'http://localhost:3000/auth/google/callback/'
      }
    end)
  }
end

```
Not forgetting the with the trailing slash!
Gem file;
```
gem 'omniauth'
gem 'omniauth-google-oauth2', git: 'https://github.com/zquestz/omniauth-google-oauth2.git'
gem 'omniauth-oauth2', '~> 1.4'
gem 'devise', '~> 3.5', '>= 3.5.2'
```

My  ```omniauth_callbacks_controller.rb```
```
class OmniauthCallbacksController < Devise::OmniauthCallbacksController   
	def google_oauth2
		@user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

		if @user.persisted?
			flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
			sign_in_and_redirect @user, :event => :authentication
		else
			session["devise.google_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end
end
```

and My ```user.rb``` looking like this:

```
def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
		# byebug
		data = access_token.info
		user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
		if user
			return user
		else
			registered_user = User.where(:email => access_token.info.email).first
				if registered_user
					return registered_user
				else
					user = User.create(first_name: data["first_name"], second_name: data["last_name"],
						provider:access_token.provider,
						email: data["email"],
						uid: access_token.uid ,
						password: Devise.friendly_token[0,20],
					)
				end
		end
	end

```


Quite strange that  ```  name: 'google' ```  would give me an error. Or did I have something wrongly set up? This is just an addition... not a question. It's Working perfectly now!

**Comment by BrandonMathis** [comment]
I had mis-configured the redirect uri in my rails app to be `localhost:3000`. Configuring ember to proxy through to `:3000` via the command `ember serve --proxy http://localhost:3000` and setting the redirect uri to `localhost:4200` works great for me.

**Comment by jweisman** [comment]
I'm seeing the same behavior. The `OmniAuth.config.full_host` parameter seems to be ignored.

With `OmniAuth.config.full_host`, redirect_uri_mismatch error:
```
2015-10-27T00:02:16.575854+00:00 app[web.1]: Started GET "/auth/google_oauth2" for 212.179.71.70 at 2015-10-27 00:02:16 +0000
2015-10-27T00:02:16.576332+00:00 app[web.1]: (google_oauth2) Request phase initiated.
2015-10-27T00:02:16.577788+00:00 heroku[router]: at=info method=GET path="/auth/google_oauth2" host=myalmalib.exldevnetwork.net request_id=7d48bfa8-ea0b-440a-ae97-6b847410ed14 fwd="212.179.71.70" dyno=web.1 connect=1ms service=7ms status=302 bytes=1777
2015-10-27T00:02:17.344217+00:00 app[web.1]: Started GET "/auth/google_oauth2" for 212.179.71.70 at 2015-10-27 00:02:17 +0000
2015-10-27T00:02:17.344561+00:00 app[web.1]: (google_oauth2) Request phase initiated.
2015-10-27T00:02:17.345611+00:00 heroku[router]: at=info method=GET path="/auth/google_oauth2" host=myalmalib.exldevnetwork.net request_id=418b89dc-26ff-414e-b7ef-19ba7f093976 fwd="212.179.71.70" dyno=web.1 connect=1ms service=6ms status=302 bytes=1777
2015-10-27T00:02:18.132003+00:00 app[web.1]: Started GET "/auth/google_oauth2/callback?state=20dae168e2be6d983fe6c47ae84bce9a9760f10be1b12c30&code=4/CzOA7MfRbm-IiUVAgzyZkS8lRrDNOiV0J0IJ46PFZiM" for 212.179.71.70 at 2015-10-27 00:02:18 +0000
2015-10-27T00:02:18.132399+00:00 app[web.1]: (google_oauth2) Callback phase initiated.
2015-10-27T00:02:18.452330+00:00 heroku[router]: at=info method=GET path="/auth/google_oauth2/callback?state=20dae168e2be6d983fe6c47ae84bce9a9760f10be1b12c30&code=4/CzOA7MfRbm-IiUVAgzyZkS8lRrDNOiV0J0IJ46PFZiM" host=myalmalib.exldevnetwork.net request_id=5b70b52b-da66-46e7-bd7d-cf2c504cee70 fwd="212.179.71.70" dyno=web.1 connect=0ms service=327ms status=302 bytes=978
2015-10-27T00:02:18.454204+00:00 app[web.1]: (google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, redirect_uri_mismatch: 
2015-10-27T00:02:18.454209+00:00 app[web.1]:   "error" : "redirect_uri_mismatch"
2015-10-27T00:02:18.454208+00:00 app[web.1]: {
2015-10-27T00:02:18.454210+00:00 app[web.1]: }
2015-10-27T00:02:18.742576+00:00 heroku[router]: at=info method=GET path="/auth/failure?message=invalid_credentials&origin=http%3A%2F%2Fmyalmalib.exldevnetwork.net%2Flogin&strategy=google_oauth2" host=myalmalib.exldevnetwork.net request_id=d596aedf-6530-40a4-a7f1-65f148062252 fwd="212.179.71.70" dyno=web.1 connect=1ms service=3ms status=301 bytes=345
2015-10-27T00:02:18.744227+00:00 app[web.1]: Started GET "/auth/failure?message=invalid_credentials&origin=http%3A%2F%2Fmyalmalib.exldevnetwork.net%2Flogin&strategy=google_oauth2" for 212.179.71.70 at 2015-10-27 00:02:18 +0000
```

With the `token_params` set in the provider:
```
2015-10-27T00:06:01.932747+00:00 app[web.1]: Started GET "/auth/google_oauth2" for 212.179.71.70 at 2015-10-27 00:06:01 +0000
2015-10-27T00:06:01.933429+00:00 app[web.1]: (google_oauth2) Setup endpoint detected, running now.
2015-10-27T00:06:01.933488+00:00 app[web.1]: (google_oauth2) Request phase initiated.
2015-10-27T00:06:01.938766+00:00 heroku[router]: at=info method=GET path="/auth/google_oauth2" host=myalmalib.exldevnetwork.net request_id=51027412-e96a-4b2a-9762-4457db9bef69 fwd="212.179.71.70" dyno=web.1 connect=1ms service=13ms status=302 bytes=1777
2015-10-27T00:06:03.066633+00:00 heroku[router]: at=info method=GET path="/auth/google_oauth2" host=myalmalib.exldevnetwork.net request_id=d9aa63db-ed8e-4e82-b567-a944bb346026 fwd="212.179.71.70" dyno=web.1 connect=1ms service=10ms status=302 bytes=1777
2015-10-27T00:06:03.063904+00:00 app[web.1]: Started GET "/auth/google_oauth2" for 212.179.71.70 at 2015-10-27 00:06:03 +0000
2015-10-27T00:06:03.064397+00:00 app[web.1]: (google_oauth2) Setup endpoint detected, running now.
2015-10-27T00:06:03.064421+00:00 app[web.1]: (google_oauth2) Request phase initiated.
2015-10-27T00:06:03.862945+00:00 app[web.1]: Started GET "/auth/google_oauth2/callback?state=6c3d67201d72d173e2fd81266839146393f40a488f8c2250&code=4/jxC3q5r8rQBQu2aCIzA4qb22PHN0YlQPVEOGvWzU8Xg" for 212.179.71.70 at 2015-10-27 00:06:03 +0000
2015-10-27T00:06:03.863410+00:00 app[web.1]: (google_oauth2) Callback phase initiated.
2015-10-27T00:06:03.863342+00:00 app[web.1]: (google_oauth2) Setup endpoint detected, running now.
2015-10-27T00:06:04.444377+00:00 app[web.1]: Processing by SessionsController#create as HTML
```

**Comment by jweisman** [comment]
Looks like the cause here is a change in omniauth-oauth2:
https://github.com/intridea/omniauth-oauth2/issues/81

**Comment by samuraraujo** [comment]
I fix with:
gem 'omniauth-oauth2', '~> 1.3.1'

**Comment by brain64bit** [comment]
@samuraraujo work like a charm, thanks

**Comment by mmahalwy** [comment]
i am having the problem where my one-time code AJAX request is not getting picked up by the gem

**Comment by mmahalwy** [comment]
@samuraraujo this didnt work

**Comment by zquestz** [comment]
@mmahalwy what version of the gem are you using?

**Comment by schnmudgal** [comment]
Fixed it:
degraded from 1.4.0 to gem 'omniauth-oauth2', '~> 1.3.1'
Also sometime only registering provider gem install the dependency as latest omniauth-oauth2 i.e. 1.4.*
Register gem version manually instead, and not depending on dependency resolution.

**Comment by pulkit21** [comment]
@samuraraujo worked for me thanx :+1:

**Comment by garside** [comment]
@samuraraujo my hero! :heart_eyes_cat: :heart_eyes_cat: :heart_eyes_cat:

**Comment by relevantmedia** [comment]
@BrandonMathis - I have a similar setup with an Angular app. I have it running in an express server at http://...:3000 and my rails api is running at localhost:3001

I am getting a code back from the front end and trying to post to /users/auth/google/callback but, getting the redirect_uri_mismatch. I am running omniauth_oauth2 ~> 1.3.1

Here is my code on the front end.
```
    let headers = new Headers({ 'Content-Type': 'application/json' });
    let options = new RequestOptions({ headers: headers });
    this._http.post('http://localhost:3001/users/auth/google/callback?code=' + code, options)
```

How do I send the redirect_uri to 3001 or how do I need to setup omniauth to redirect to 3000?

**Comment by amarts** [comment]
I wasted lot of time today on this too. Even after following all these comments, my issues didn't get resolved.

I had to update to ruby 2.3.0 (and then bundle install) to get the issue fixed. Didn't require any of the changes for parameters to google_oauth2.

**Comment by Ypyth7** [comment]
> Независимо от того, что я делаю, я не могу избежать этого, и я не могу избежать redirect_uri быть другим.
> 
> Вот мой omniauth.rb
> 
> ```
> require 'awesome_print'
> Rails.application.config.middleware.use OmniAuth::Builder do
>   provider :google_oauth2, Rails.application.secrets[:google_client_id], Rails.application.secrets[:google_client_secret],
>   {
>     name: 'google',
>     scope: 'email profile https://www.googleapis.com/auth/contacts.readonly',
>     prompt: 'select_account',
>     access_type:  'offline',
>     # redirect_uri: 'postmessage',
>     provider_ignores_state: true, # BAD, TODO: https://github.com/intridea/omniauth-oauth2/issues/58
>     setup: (lambda do |env|
>       request = Rack::Request.new(env)
>       env['omniauth.strategy'].options['redirect_uri'] = 'http://townsquared.com:3000/auth/google/callback12123123123'
>       Rails.logger.ap env['omniauth.strategy'].inspect
>       Rails.logger.ap env['omniauth.strategy'].options
> 
>     end)
>   }
> end
> ```
> 
> Мой клиент:
> 
> ```
> gapi.auth.authorize({
>         client_id: 'CLIENTID,
>         scope: 'email profile https://www.googleapis.com/auth/contacts.readonly',
>         immediate: false,
>         cookie_policy: 'single_host_origin',
>         response_type: 'code'
>       }, function(response) {
>         return gapi.auth.authorize({
>           client_id: 'CODE,
>           scope: 'email profile https://www.googleapis.com/auth/contacts.readonly',
>           immediate: true,
>           cookie_policy: 'single_host_origin',
>           response_type: 'code'
>         }, function(response) {
>           if (response && !response.error) {
> 
>             response.redirect_uri = 'http://townsquared.com:3000/auth/google/callback';
>             console.log(response);
>             $http.get('/auth/google/callback', {params: response}).then((r) => {
>               console.log(r.data);
>             });
>           }
>         });
>       });
> ```
> 
> Во-первых, я столкнулся с проблемой CSRF, которая пока решается. Теперь я не могу избежать этого. В моем запросе я могу установить BLAH и по-прежнему получать этот запрос в Google:`provider_ignores_state``redirect_uri_mismatch``redirect_uri`
> 
> ```
>   HTTP POST (45.93ms)   https://accounts.google.com:443/o/oauth2/token
>   Request body   client_id=CLIENTID&client_secret=CLIENTSECRET&code=4%2FxwsEFz5g2sSYkaHAvksApQcPe3pd0FPCk2c3gduakho.wsWDhoI5BeMbXmXvfARQvtiMkhr_mgI&grant_type=authorization_code&redirect_uri=http%3A%2F%2Ftownsquared.com%3A3000%2Fauth%2Fgoogle%2Fcallback
>   Response status   Net::HTTPBadRequest (400)
>   Response body   {
>   "error" : "redirect_uri_mismatch"
> }
> App 50330 stdout: E, [2015-05-23T02:54:36.534528 #50330] ERROR -- omniauth: (google) Authentication failure! invalid_credentials: OAuth2::Error, redirect_uri_mismatch:
> App 50330 stdout: {
> App 50330 stdout:   "error" : "redirect_uri_mismatch"
> App 50330 stdout: }
> 
> OAuth2::Error (redirect_uri_mismatch:
> {
>   "error" : "redirect_uri_mismatch"
> }):
> ```
> 
> Это ВСЕГДА`http%3A%2F%2Ftownsquared.com%3A3000%2Fauth%2Fgoogle%2Fcallback`
> 
> Есть идеи, почему это происходит?
> 
> ![образ](https://cloud.githubusercontent.com/assets/3749095/7782794/9e1b9aae-00f7-11e5-85bc-87db9dbe1c63.png)
Ты на вот этой строчке 'CLIENTID,
Напиши 'CLIENTID'

**Comment by Ypyth7** [comment]
Ты на вот этой строчке 'CLIENTID,Напиши
'CLIENTID'
