### ISSUE TITLE
Can't modify frozen Array

### ISSUE THREAD

**Issue by proigor** [zquestz/omniauth-google-oauth2#183]
Hi!

When I'm adding provider :google_oauth2...I no longer able to start my rails.
It fails with:
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/stack.rb:112:in `push': can't modify frozen Array (RuntimeError)
	from /usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/stack.rb:112:in `use'
	from /Users/user/work/dt/config/initializers/omniauth.rb:2:in `<top (required)>'

I'm using: 
MacBook-Pro:dt user$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
MacBook-Pro:dt user$ rails -v
Rails 4.2.1
MacBook-Pro:dt user$

and latest gems

**Comment by zquestz** [comment]
Can you post the contents of your omniauth.rb file?

**Comment by proigor** [comment]
The problem was when I was using
provider :google_oauth2

solved the problem with.

provider OmniAuth::Strategies::GoogleOauth2

**Comment by mikecx** [comment]
I realize this is a very old issue, but in case it helps someone else, I ran into this when using Rails 6 multi-environment credentials but forgetting to set it up for a particular environment. Hopefully this prevents someone else from spending 15 minutes tracking down something silly.
