### ISSUE TITLE
Content-Type for 302

### ISSUE THREAD

**Issue by dylanz** [zquestz/omniauth-google-oauth2#184]
We're running the ZED OWASP suite, and it complains about a missing Content-Type header when accessing the /auth/google_oauth2 route on our server.  The solution being:  "Ensure each page is setting the specific and appropriate content-type value for the content being delivered"

A solution would be to add a Content-Type header of "text/html" when doing the 302 redirect.  If you don't see any issues with this, could I issue a pull request for this addition?

**Comment by zquestz** [comment]
Sounds good to me.

**Comment by zquestz** [comment]
Any status on this?

**Comment by nandukalidindi** [comment]
I too have the same problem for my connected app. Is there a way to inject the content-type header in the `302` response?

**Comment by zquestz** [comment]
It does not appear that omniauth has that option. If you look at the redirect method in `https://github.com/intridea/omniauth/blob/master/lib/omniauth/strategy.rb` you can see they just use the rack redirect function, and only pass it a URI. I don't see any handling for a content-type header.
