### ISSUE TITLE
Hybrid Authentication example uses JSON

### ISSUE THREAD

**Issue by banditrider** [zquestz/omniauth-google-oauth2#185]
In the [Hybrid Authentication](https://github.com/zquestz/omniauth-google-oauth2#one-time-code-flow-hybrid-authentication) example, the following code is used in the AJAX request:

    jQuery.ajax({type: 'POST', url: "/auth/google_oauth2/callback", dataType: 'json', data: response,
          success: function(json)

The data type used here is JSON, even though rack can't really handle json without an extension. Is there a reason for this? If there's no good reason to use JSON, I would suggest to alter the example to use the `application/x-www-form-urlencoded` format. It could save some fellow developers some time in debugging...

See this [Stackoverflow question](http://stackoverflow.com/questions/30648729/json-parameters-not-available-in-request-hash-rails-omniauth-google-oauth2-gem).

**Comment by zquestz** [comment]
That sounds good, feel free to do a PR.

**Comment by zquestz** [comment]
Any status?

**Comment by zquestz** [comment]
Fixed.
