### ISSUE TITLE
Token endpoint changed to https://www.googleapis.com/oauth2/v3/token

### ISSUE THREAD

**Issue by YoranBrondsema** [zquestz/omniauth-google-oauth2#186]
The documentation on Google (https://developers.google.com/identity/protocols/OAuth2WebServer#handlingtheresponse) now says that the endpoint for exchanging an authorization code for an access token is https://www.googleapis.com/oauth2/v3/token, whereas it is currently set to https://accounts.google.com/o/oauth2/token (see https://github.com/zquestz/omniauth-google-oauth2/blob/master/lib/omniauth/strategies/google_oauth2.rb#L21). However, the endpoint to authorize a user hasn't changed (see https://developers.google.com/identity/protocols/OAuth2WebServer#formingtheurl), it is still https://accounts.google.com/o/oauth2/auth.

The fact that the authorization URL and token URL are on different domains causes problems because the `auth2` gem assumes that both have the same base URL (see https://github.com/intridea/oauth2/blob/master/lib/oauth2/client.rb#L18-L20).

In my particular case, I am doing the authorization on the client-side and on the server I only exchange the authorization code for a token. So I hardcoded the base URL just to provide for the token URL:

````
provider :google_oauth2, ENV["GOOGLE_CLIENT_ID"], ENV["GOOGLE_CLIENT_SECRET"], {
  client_options: {
    site: "https://www.googleapis.com",
    token_url: "/oauth2/v3/token"
  }
}
````

But this wouldn't work in general. I would like to fix this issue but I'm not sure whether it should be done on this gem or by extending the `auth2` gem.

**Comment by zquestz** [comment]
I think we wait on changes to the oauth2 library first, then we can refactor the code in this gem to include the new endpoints. =)
