### ISSUE TITLE
Can we have dynamic callback_url/callback_path

### ISSUE THREAD

**Issue by spartan1234** [zquestz/omniauth-google-oauth2#189]
I am trying to add API in my existing rails application, it will just return json data, but will have different login space not the same as in existing application
Existing application - after login user will be redirected to his/her profile
New login page for api -- token will be generated and returned in api call.
So, there will be two callback function based upon the login page called, so, how can I dynamically define callback_path based upon the login page called.

**Comment by zquestz** [comment]
You shouldn't have 2 callback paths. You should have one and in that callback you can have your app logic and redirect them to the location of your choice.
