### ISSUE TITLE
Possible to request the auth info afterwards?

### ISSUE THREAD

**Issue by alexhanh** [zquestz/omniauth-google-oauth2#191]
We started using this gem to simply provide a simple login method for Google users. We haven't stored the image returned so far, but it's now relevant. We don't store the tokens either, we just have the UID and email address.

Is it possible to somehow request the profile image url using the UID/email from Google without tokens? 

Needless to say, we are now saving the image url too, but we need to migrate our existing users somehow. Thanks!

**Comment by zquestz** [comment]
Here is a StackOverflow article detailing how to do this. 

http://stackoverflow.com/questions/9128700/getting-google-profile-picture-url-with-user-id
