### ISSUE TITLE
Image Size not coming in properly

### ISSUE THREAD

**Issue by johngibbons** [zquestz/omniauth-google-oauth2#192]
I am using this strategy with a Rails application and it was previously pulling in the correct 300x300 image for users but now seems to only grab a 50x50 image.  Here is the code I am using in my omniauth.rb file within my initializers directory:

    Rails.application.config.middleware.use OmniAuth::Builder do
        provider :google_oauth2, ENV["GOOGLE_CLIENT_ID"], ENV["GOOGLE_CLIENT_SECRET"],
        {
          image_size: 300
        }
    end

I have checked the url that is being grabbed in order to process the image and it looks like this:

    https://lh5.googleusercontent.com/.../s300/photo.jpg?sz=50

It looks like the "s300" is indicating that omniauth knows I want the 300 size but the ?sz=50 query is causing only the 50 size to be grabbed.  I'm sure I can manipulate that query within my own code but wanted to at least bring this to your attention since it was working previously for me with these settings.

**Comment by hanpanpan200** [comment]
I have same problem when setting the image-size. Whatever I have set I still  get a profile-image of "50", I know I can use my own code to handle this, but I really wish that this config can set it for me.

**Comment by olivierlacan** [comment]
This issues was fixed by d9b16f65e61d6ee21a26342a9fa92371b61575ea. You can use the master branch or wait for the upcoming new release.

**Comment by zquestz** [comment]
Closing, new gem is released with a fix.

**Comment by olivierlacan** [comment]
Thanks Josh!
