### ISSUE TITLE
I get redirect_uri_mismatch but it's not the problem

### ISSUE THREAD

**Issue by jchatel** [zquestz/omniauth-google-oauth2#204]
Yesterday, I did a release in production (Heroku) of a small change (nothing to do with gem file, routes or authentification in general).

Then I started getting complains than people could not log in anymore

Turned out the error in the log is the following:

(google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, redirect_uri_mismatch:
{
  "error" : "redirect_uri_mismatch"
}

It obviously has nothing to do with redirect URL since the no routes have changed and my google console API webclient didn't change in 6 month either.

I do a lot of releases and I know that on the 20th October (4 days ago), it worked fine.

I reverted to previous release, which worked fine. Now I just can't deploy new version because of this problem that I can reproduce on my Staging environment by just making a new release.

I saw that this gem dependencies are 

RUNTIME DEPENDENCIES:
addressable ~> 2.3
jwt ~> 1.0
multi_json ~> 1.3
omniauth >= 1.1.1
omniauth-oauth2 >= 1.1.1

omniauth-oauth2 did a release on the 21st October, so I would think this is the problem but did not investigate further yet.

Any idea how to solve or investigate further?

**Comment by hmnhf** [comment]
Take a look at intridea/omniauth-oauth2#81.

**Comment by jchatel** [comment]
Thanks, sounds like it. Another +1 for explicitly stating version used instead of >=

**Comment by HunterFortuin** [comment]
+1 for explicitely stating gem version. 

gem 'omniauth-oauth2', '~> 1.3.1'

**Comment by jchatel** [comment]
Yeah that's what I did in the end and it works fine.
Those >= although great in concept (you get latest security fix) in reality turns more like "Fuck it doesn't work anymore, what changed" on deploying in production... a nightmare.

**Comment by ajsharp** [comment]
Thanks for posting this. This gem should set it's version dependency to '~>1.3.1' to avoid this issue for people. The issue has been open on omniauth-oauth2 for 7 days now and there hasn't been a single comment from a contributor. Fixing the dependency issue in this gem will save future people *hours* if not days of wasted time. Happy to handle the PR @zquestz

**Comment by ajsharp** [comment]
Also, that is what the owner of the omniauth-oauth2 repo is recommending.

**Comment by zquestz** [comment]
New gem is now released that locks the dependency to ~> 1.3.1.

**Comment by ajsharp** [comment]
@zquestz thanks!

**Comment by zquestz** [comment]
No problem. Thanks for the debugging and getting to the heart of the issue. =)

**Comment by duleorlovic** [comment]
Dependency `'omniauth-oauth2', '~> 1.3.1'` is no longer true 
[Here](cdd6e869feb8b04a0dd3fb1490ae2705ab065b20) is upgraded to 1.4
