### ISSUE TITLE
Is this documentation outdated?

### ISSUE THREAD

**Issue by daniel-nelson** [zquestz/omniauth-google-oauth2#209]
https://github.com/zquestz/omniauth-google-oauth2#configuration states "Note that if you need a refresh token, google requires you to also to specify the option prompt: 'consent', which is not a default." However, I seem to be getting a valid refresh token without specifying a prompt configuration at all. In fact, the UX appears to be identical when specifying "prompt: 'consent'" and when specifying no prompt configuration (I've confirmed that the URLs generated are different, with the one including prompt=consent, and the other not).

**Comment by daniel-nelson** [comment]
The Google documentation on offline access does not mention the consent prompt: https://developers.google.com/identity/protocols/OAuth2WebServer#offline

**Comment by zquestz** [comment]
Looks like they made a change, feel free to send a PR with that updated.
