### ISSUE TITLE
Not working correctly with Devise

### ISSUE THREAD

**Issue by raffe90** [zquestz/omniauth-google-oauth2#212]
I am following step by step the instructions detailed in the README in order to set omniauth with Devise, as well as the instructions here:
https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview

This is what happens:

- I get redirected
- I am asked to chose my account
- I get the "App would like to... 
![screenshot-allow](https://cloud.githubusercontent.com/assets/11524607/11345245/fb248af8-9215-11e5-8510-8b0a91f630ea.png)

After I click on allow I get this view:
![screenshot](https://cloud.githubusercontent.com/assets/11524607/11345144/95374f64-9215-11e5-904a-a5ae08908d12.png)

And the console (server):
![screenshot-server](https://cloud.githubusercontent.com/assets/11524607/11345177/b9011c18-9215-11e5-9467-8fb692117781.png)

Am I missing something?

In fact, if I remove/comment out the google_oauth2 method I believe I should get an error analogue to this one: 
"
Unknown action
The action 'facebook' could not be found for Users::OmniauthCallbacksController

"

But nothing happens, it is like the app is going through some other place

**Comment by alpracka** [comment]
@raffe90 it seems there is a bug in 1.4.0 version of omniauth-oauth2 gem - https://github.com/intridea/omniauth-oauth2/issues/81

Try to put (or modify) `gem 'omniauth-oauth2', '~> 1.3.1'` in your Gemfile.

**Comment by raffe90** [comment]
@alpracka thank you very much! Got it up and runnning now.
