### ISSUE TITLE
failure action is not getting triggered when someone tried email domain which is not whitelisted

### ISSUE THREAD

**Issue by aruprakshit** [zquestz/omniauth-google-oauth2#213]
In my *config/initializers/devise.rb*, I have : 

```ruby
  config.omniauth(
    :google_oauth2, 
    Rails.application.secrets.google_oauth_client_id,
    Rails.application.secrets.google_oauth_secret_key,
    scope: 'email,profile',
    prompt: "select_account",
    hd: 'gmail.com'
  )
```

For testing, I am using some testing@gmail . When hitting the google signin url from app getting the below log : 

```sh
Started GET "/users/auth/google_oauth2" for ::1 at 2015-11-29 20:55:07 +0530
I, [2015-11-29T20:55:07.403011 #27291]  INFO -- omniauth: (google_oauth2) Request phase initiated.
```

Now, I gave valid email and password, so signed in happened, but google didn't let me go further as the email domain is not the part of the whitelisted ones and it stays to the google page. But I am not getting any response back to my app, at-least from Rails log nothing is visible. I am expecting `failing` action to get triggered on this occasion.

**Comment by pramodshinde** [comment]
@aruprakshit - Did you tried same thing with `openid` scope along with `hd` parameter ?

**Comment by zquestz** [comment]
If you are just using gmail I would suggest not using the hd parameter. The docs state that is only for CUSTOM domains, not gmail itself.

**Comment by aruprakshit** [comment]
@zquestz  Why did you close it ? I have custom domains, `.gmail` is there just as an example.

**Comment by zquestz** [comment]
Sorry about that. Quick question...
If you actually fail the login on purpose, does it hit your failure endpoint?

**Comment by aruprakshit** [comment]
@zmajstor No it doesn't. If it does, I could be happy. When my hd params match, all goes well. When it doesn't match, it don't give anything as you see the log in my main description of this thread.

**Comment by zquestz** [comment]
If you don't use the hd param and just fail the login what happens? Do you see the failure? Are you behind any type of proxy?

**Comment by aruprakshit** [comment]
@zquestz  Then it hits the `failure` action.

**Comment by zquestz** [comment]
KK just wanted to make sure that in the normal flow it works as expected. I will look into how to get the failure fixed for the hd param tonight.

**Comment by aruprakshit** [comment]
@zquestz  Thank you very much in advance!

**Comment by zquestz** [comment]
Resolved in PR - https://github.com/zquestz/omniauth-google-oauth2/pull/223
