### ISSUE TITLE
403 from faraday on auth callback [production env]

### ISSUE THREAD

**Issue by jacekgrzybowski** [zquestz/omniauth-google-oauth2#214]
After auth call to `accounts.google.com` on callback to my application I get 500 error in my app, as faraday fails on some request with 403 status code.

My config with Devise:

    config.omniauth :google_oauth2, Rails.application.secrets[:google_client_id], Rails.application.secrets[:google_secret],
      {
        skip_jwt: true,
        provider_ignores_state: true,
        scope: 'email,profile'

        # client_options: {
        #   connection_opts: {
        #     proxy: nil
        #   }
        # }
      }

Log:

    A Faraday::ConnectionFailed occurred in #:

      403 "Forbidden"

    -------------------------------
    Request:
    -------------------------------

      * URL        : http://example.com/users/auth/google_oauth2/callback?state=e28c2489b0083b5c7c58a5a5f91a365c12d2aa3fb2cff2fa&code=4/MjPAPKyXu9cviE4he0KYnrr3vgBha5an2SF8UcACKe4
      * HTTP Method: GET
      * IP address : 10.0.100.2
      * Parameters : {"state"=>"e28c2489b0083b5c7c58a5a5f91a365c12d2aa3fb2cff2fa", "code"=>"4/MjPAPKyXu9cviE4he0KYnrr3vgBha5an2SF8UcACKe4"}
      * Timestamp  : 2015-11-30 15:18:03 +0100
      * Server : ---
      * Rails root : ---
      * Process: 4571

    -------------------------------
    Session:
    -------------------------------

      * session id: "16992bebee2500efc6278094174a066b"
      * data: {"session_id"=>"16992bebee2500efc6278094174a066b",
       "_csrf_token"=>"1nWJK/QVOOzunxd0CvkzjWKADE5W7M5LMGCctYdtLTc=",
       "omniauth.state"=>"e28c2489b0083b5c7c58a5a5f91a365c12d2aa3fb2cff2fa"}

    F, [2015-11-30T15:18:03.462121 #4571] FATAL -- :                                                                                                                                                                               [21/1619]
    Faraday::ConnectionFailed (403 "Forbidden"):
      /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
      /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:128:in `value'
      /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:915:in `connect'
      /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
      /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:852:in `start'
      /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1369:in `request'
      /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1128:in `get'
      faraday (0.9.2) lib/faraday/adapter/net_http.rb:80:in `perform_request'
      faraday (0.9.2) lib/faraday/adapter/net_http.rb:40:in `block in call'
      faraday (0.9.2) lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
      faraday (0.9.2) lib/faraday/adapter/net_http.rb:32:in `call'
      faraday (0.9.2) lib/faraday/request/url_encoded.rb:15:in `call'
      faraday (0.9.2) lib/faraday/rack_builder.rb:139:in `build_response'
      faraday (0.9.2) lib/faraday/connection.rb:377:in `run_request'
      oauth2 (1.0.0) lib/oauth2/client.rb:93:in `request'
      oauth2 (1.0.0) lib/oauth2/access_token.rb:107:in `request'
      oauth2 (1.0.0) lib/oauth2/access_token.rb:114:in `get'
      omniauth-google-oauth2 (0.2.10) lib/omniauth/strategies/google_oauth2.rb:81:in `raw_info'
      omniauth-google-oauth2 (0.2.10) lib/omniauth/strategies/google_oauth2.rb:42:in `block in <class:GoogleOauth2>'
      omniauth (1.2.2) lib/omniauth/strategy.rb:105:in `instance_eval'
      omniauth (1.2.2) lib/omniauth/strategy.rb:105:in `block in compile_stack'
      omniauth (1.2.2) lib/omniauth/strategy.rb:104:in `each'
      omniauth (1.2.2) lib/omniauth/strategy.rb:104:in `inject'
      omniauth (1.2.2) lib/omniauth/strategy.rb:104:in `compile_stack'
      (eval):7:in `uid_stack'
      omniauth (1.2.2) lib/omniauth/strategy.rb:317:in `uid'
      omniauth (1.2.2) lib/omniauth/strategy.rb:333:in `auth_hash'
      omniauth (1.2.2) lib/omniauth/strategy.rb:361:in `callback_phase'
      omniauth-oauth2 (1.3.1) lib/omniauth/strategies/oauth2.rb:79:in `callback_phase'
      omniauth (1.2.2) lib/omniauth/strategy.rb:227:in `callback_call'
      omniauth (1.2.2) lib/omniauth/strategy.rb:184:in `call!'
      omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
      exception_notification (4.1.1) lib/exception_notification/rack.rb:32:in `call'
      warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
      warden (1.2.3) lib/warden/manager.rb:34:in `catch'
      warden (1.2.3) lib/warden/manager.rb:34:in `call'
      rack (1.6.4) lib/rack/etag.rb:24:in `call'
      rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
      rack (1.6.4) lib/rack/head.rb:13:in `call'
      remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
      actionpack (4.2.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
      actionpack (4.2.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
      rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
      rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
      actionpack (4.2.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
      activerecord (4.2.2) lib/active_record/query_cache.rb:36:in `call'
      activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
      actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
      activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `call'
      activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
      activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
      activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
      actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
      actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
      actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
      actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
      railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
      railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
      activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
      railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
      actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
      rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
      rack (1.6.4) lib/rack/runtime.rb:18:in `call'
      activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
      actionpack (4.2.2) lib/action_dispatch/middleware/static.rb:113:in `call'
      rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
      rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
      railties (4.2.2) lib/rails/engine.rb:518:in `call'
      railties (4.2.2) lib/rails/application.rb:164:in `call'
      rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
      rack (1.6.4) lib/rack/config.rb:17:in `call'
      /usr/local/rvm/gems/ruby-2.1/gems/passenger-4.0.41/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
      /usr/local/rvm/gems/ruby-2.1/gems/passenger-4.0.41/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
      /usr/local/rvm/gems/ruby-2.1/gems/passenger-4.0.41/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
      /usr/local/rvm/gems/ruby-2.1/gems/passenger-4.0.41/lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

**Comment by zquestz** [comment]
Looks like you are using example.com somewhere in your code... that doesn't seem right to me.

**Comment by jacekgrzybowski** [comment]
I used example.com to mask the real host before posting here :) anyway, the problem had to do with our network stack - external connection to google service was blocked and 403 was returned from our squid.
