### ISSUE TITLE
Update verify_token method to use API v3/tokeninfo endpoint(v3 version)

### ISSUE THREAD

**Issue by pramodshinde** [zquestz/omniauth-google-oauth2#216]
@zquestz  Currently [verify_token](https://github.com/zquestz/omniauth-google-oauth2/blob/master/lib/omniauth/strategies/google_oauth2.rb#L172) method using v2/tokeninfo (v2 api endpoint). However, [newer version](https://developers.google.com/identity/protocols/OAuth2UserAgent#tokeninfo-validation) available for this endpoint, Should we update verify_token to use this new API endpoint. 

Though, this [newer version](https://developers.google.com/identity/protocols/OAuth2UserAgent#tokeninfo-validation) API response differs from docs response JSON in reality. 
Example: 
In docs following response is given : 
```ruby
{
  "audience":"8819981768.apps.googleusercontent.com",
  "user_id":"123456789",
  "scope":"profile email",
  "expires_in":436
}
```
But in reality API response is following 
Endpoint: https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=my_access_token

```ruby
{
  "aud": "xxxxxxxxxxxxx.apps.googleusercontent.com", 
  "sub": "12345",   
  "access_type": "offline", 
  "expires_in": "1465"
  "scope": "email profile", 
  ## some other extra fields 
}
```
Major difference is key `audience` is return as `aud` in reality which matters to us for token verification.

I have implemented this change in this [commit](https://github.com/joshsoftware/omniauth-google-oauth2/commit/d16bb8c4be44787204033c4e189f23ac308740b0), Please Let me know if its correct change for PR.

**Comment by zquestz** [comment]
This is a breaking change, we can do this but we need to bump the major version number so people don't accidentally break their apps by updating. Can you add that to your PR?

**Comment by zquestz** [comment]
Also need to update tests.

**Comment by zquestz** [comment]
This has been merged. Thanks!

**Comment by pramodshinde** [comment]
@zquestz  -  I see PR #217 is merged this has test cases update as well, Only thing remaining is version bump can you bump version as this is already merged in your next release or I shall do one commit for this?

**Comment by zquestz** [comment]
Going to do this myself. I also am bumping to the new omniauth-oauth2 gem with another fix.

**Comment by pramodshinde** [comment]
:+1: Great!
