### ISSUE TITLE
"hd" as array not working in v0.3.1

### ISSUE THREAD

**Issue by teleological** [zquestz/omniauth-google-oauth2#228]
This is not a bug, but I thought it might save others time to understand that configuring an array for the "hd" option, as suggested in the README, doesn't work with the latest released version, v0.3.1. Stick to a single domain as a string, check out from source, or wait for the next release!

**Comment by Dahlgren** [comment]
Oh, that my fault with the verification of hd after auth. Should probably add support for array as well.

**Comment by Dahlgren** [comment]
This is already fixed by #226

**Comment by zquestz** [comment]
New version is about to be published. Docs will be accurate soon enough. =)
