### ISSUE TITLE
Authentication failure! invalid_credentials: OAuth2::Error jruby 8 , rails 3.2.13 devise 3.2.4

### ISSUE THREAD

**Issue by richardsondx** [zquestz/omniauth-google-oauth2#229]
I was able to login with gmail with no problem until 2 days ago.

I'm now experiencing an issue with omniauth-google-oauth2 on jruby 9.0 , rails 3.2.13 with devise 3.2.4  the error is:

```
(google_oauth2) Callback phase initiated.
(google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, {
"access_token" : 'xyz',
"token_type" : "Bearer", 
"expires_in" : 3596
"id_token" : "xyz123..."
}

```
This is happening right before the callback so the only stack i actually get to analyze is the one that come to the failure callback. I've pasted everything I was able to get from that issue in this gist: 

https://gist.github.com/richardsondx/c202c7bc6bcb61701af1

I've placed debugger accross the gem  and the error happens when the `custom_build_access_token` is being called on this line:

`client.auth_code.get_token(verifier, get_token_options(callback_url), deep_symbolize(options.auth_token_params))`

from /Users/richardson/.rvm/gems/jruby-9.0.5.0@contat-monkey/gems/oauth2-1.1.0/lib/oauth2/client.rb:140:in `get_token'

When I inspected the `get_token` method in oauth2 the response was gzip encrypted. 

The error is initialized on the second line bellow;
`error = Error.new(response)`
`fail(error) if options[:raise_errors] && !(response.parsed.is_a?(Hash) && response.parsed['access_token'])`

My guess is that the method wasn't able to  parse the access_token because it's not able to read the encoding. This is not the first time that I'm experiencing an issue with a google response coming in gzip. How can I resolve my encoding issue without alternating the gem?

**Comment by richardsondx** [comment]
The response from google has the header 'accept-encoding': 'gzip'. When I trace the code Faraday compress the response when it receive it because of that header. I ended up writing a monkey patch to remove the that header when the request is coming from google oauth.

```
module Faraday
  class Request::UrlEncoded < Faraday::Middleware
    def call(env)
      match_content_type(env) do |data|
        params = Faraday::Utils::ParamsHash[data]
        env.body = params.to_query(env.params_encoder)
        if env.url.to_s == "https://accounts.google.com/o/oauth2/token"
          # Will remove any encoding that is happended for that url
          env.request_headers['accept-encoding'] = ''
          # The following call might be cleanner as it make sure that the response is not gzip*
          # env.request_headers["accept-encoding"] = "gzip;q=0,deflate,sdch"
        end
      end
      @app.call env
    end
  end
```

You can also find it here:
https://gist.github.com/richardsondx/e3c850ad137bfafb20d5

It forces Faraday to avoid compressing the response.

Unlike http.net, http.request doesn't automatically uncompress gzip response
more info about http.request at [https://github.com/ruby/ruby/blob/ruby_2_2/lib/net/http.rb](https://github.com/ruby/ruby/blob/ruby_2_2/lib/net/http.rb)

**Comment by richardsondx** [comment]
This is coming from **Faraday** not omniauth-google-oauth2.

**Comment by netroby** [comment]
Got the same issue
