### ISSUE TITLE
New support for :jwt_leeway doesn't include `iat` leeway

### ISSUE THREAD

**Issue by ttilberg** [zquestz/omniauth-google-oauth2#232]
Is it possible to bump the JWT dependency from `~> 1.5.0` to `~> 1.5.2` ? Adding leeway support to `iat` didn't actually happen until ver 1.5.2. I don't know if this causes trauma elsewhere, but with omniauth-google-oauth2 0.4.0, `iat` isn't affected by leeway in my current gem environment, which is opting for ver 1.5.1.

```ruby
# JWT 1.5.1  https://github.com/jwt/ruby-jwt/blob/jwt-1.5.1/lib/jwt.rb#L169
    if options[:verify_iat] && payload.include?('iat')
      fail JWT::InvalidIatError.new('Invalid iat') unless payload['iat'].is_a?(Integer) && payload['iat'].to_i <= Time.now.to_i
    end


# JWT 1.5.2  https://github.com/jwt/ruby-jwt/blob/jwt-1.5.2/lib/jwt.rb#L169
    if options[:verify_iat] && payload.include?('iat')
      fail(JWT::InvalidIatError, 'Invalid iat') unless payload['iat'].is_a?(Integer) && payload['iat'].to_i <= (Time.now.to_i + options[:leeway])
    end
```

**Comment by zquestz** [comment]
Gotcha, I can fix that, no problemo. Doing that now.

**Comment by ttilberg** [comment]
zquestz, you rock. Thanks mate!

**Comment by zquestz** [comment]
New version is being pushed now.

**Comment by zquestz** [comment]
Let me know if you have any issues with the new version. =)
