### ISSUE TITLE
Multiple client_id support

### ISSUE THREAD

**Issue by allaire** [zquestz/omniauth-google-oauth2#234]
Hi,

We have one client id for our web app and one client id for our iOS app. Currently, there's a check that make sure that the token generated is the same as the web app client id: https://github.com/zquestz/omniauth-google-oauth2/blob/master/lib/omniauth/strategies/google_oauth2.rb#L188).

Is there a way to support multiple client ids?

From Google:

https://developers.google.com/identity/sign-in/web/backend-auth#verify-the-integrity-of-the-id-token

_The value of aud in the ID token is equal to ​**one of your app's client IDs**​. This check is necessary to prevent ID tokens issued to a malicious app being used to access data about the same user on your app's backend server._

Thanks

**Comment by zquestz** [comment]
I like the work you are doing. Let me know when it is done. =)

**Comment by zquestz** [comment]
PR? Would love to see your changes land here.

**Comment by charlesvallieres** [comment]
@zquestz Done, sorry for the late answer Github's notification got lost somewhere in my emails
