### ISSUE TITLE
Profile scope not allowing to get profile information on token verification?

### ISSUE THREAD

**Issue by Charrette** [zquestz/omniauth-google-oauth2#235]
Hi,

I have set my omniauth.rb with 
`provider :google_oauth2, ENV['GOOGLE_ID'], ENV['GOOGLE_SECRET'], scope: "profile,email"`

(I know by default it's already taking account of profile and email, but I had to try!)

I get all the needed information when connecting with this on client side.

Now my problem is on my server side, my client send to my server the token_id he got when connecting. And then I want to check the authenticity of that token with

> https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=x

I get a valid answer such as:

```
{
  "iss": "accounts.google.com",
  "at_hash": "xxx-xxx",
  "aud": "xxx-xxx.apps.googleusercontent.com",
  "sub": "xxx",
  "email_verified": "true",
  "azp": "xxx-xxx.apps.googleusercontent.com",
  "email": "xxx@gmail.com",
  "iat": "xxx",
  "exp": "xxx",
  "alg": "xxx",
  "kid": "xxx"
}
```

But why do I not get the profile information in that answer?

on this tuto: https://developers.google.com/identity/sign-in/web/backend-auth
It says I should get them, like:

```
 // These seven fields are only included when the user has granted the "profile" and
 // "email" OAuth scopes to the application.
 "email": "testuser@gmail.com",
 "email_verified": "true",
 "name" : "Test User",
 "picture": "https://lh4.googleusercontent.com/-kYgzyAWpZzJ/ABCDEFGHI/AAAJKLMNOP/tIXL9Ir44LE/s99-c/photo.jpg",
 "given_name": "Test",
 "family_name": "User",
 "locale": "en"
```

Here is the stackoverflow post I opened about that a few months ago:
http://stackoverflow.com/questions/35795831/not-getting-all-profile-informations-when-verifying-a-google-token-authenticity

**Comment by zquestz** [comment]
The problem is you are hitting the wrong endpoint. The user information is fetched from https://www.googleapis.com/plus/v1/people/me/openIdConnect

You are just getting the token information which is returning the correct data.

**Comment by zquestz** [comment]
You want to use this call... https://www.googleapis.com/plus/v1/people/me/openIdConnect?access_token=YOUR_ACCESS_TOKEN
