### ISSUE TITLE
CSRF detected, when using the js api

### ISSUE THREAD

**Issue by rrphotosoft** [zquestz/omniauth-google-oauth2#238]
Hi,
I'm trying to execute the one-time code flow technique mentioned in your docs.
When I do so, I get the following in my rails log:

```
I, [2016-07-07T17:34:58.069742 #28335]  INFO -- omniauth: (google_oauth2) Callback phase initiated.
E, [2016-07-07T17:34:58.070714 #28335] ERROR -- omniauth: (google_oauth2) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
```

Is there any way to pass the correct csrf token in the js call?

Thanks,
RR.

**Comment by rrphotosoft** [comment]
I've looked through the source and realize that this isn't a problem with your gem per sae. The omniauth-oauth2 gem sets the state during the request phase. The Js api does not invoke the request phase(server side), so no matter what we do, the state will always be empty in the callback phase, and will produce this error. 

What about the following solution?

For situations where the request phase is initialized by third parties(JS/Android App/Iphone app), we  provide an api endpoint, that will generate a one-time-use code, that they can use as the state parameter. This is then checked in the request callback. The app can override the endpoint method, so as to decide how to store this code(Redis/mongo etc.)

Let me know if you would be interested in a PR.

Regards,
RR.

**Comment by zquestz** [comment]
I would suggest to use `:provider_ignores_state => true` in your omniauth initializer. Since you are getting a one time code, that gets validated server side. This should be sufficient to address your issue.

**Comment by zquestz** [comment]
Did you get this resolved?

**Comment by zquestz** [comment]
Closing, can reopen if we have activity on this issue.

**Comment by sidpan1** [comment]
Same issue happened for me. I tried setting :provider_ignores_state => true. Then another issue happened which could be solved by a monkey patch mentioned in #153. Now for ever request, I get this error - 

`(google) Authentication failure! invalid_credentials: OAuth2::Error, invalid_grant: 
2016-08-26T05:48:45.830821+00:00 app[web.1]: App 134 stdout: {
2016-08-26T05:48:45.830835+00:00 app[web.1]: App 134 stdout:   "error" : "invalid_grant"
2016-08-26T05:48:45.830848+00:00 app[web.1]: App 134 stdout: }`

Any work around for this?

**Comment by johnsonyeap** [comment]
![screenshot from 2016-12-02 22 20 00](https://cloud.githubusercontent.com/assets/5164430/20837131/93ade49c-b8dd-11e6-8185-9a2a7c3a035b.png)

@zquestz Based the suggested approach, does it mean that the callback API for (JS/Android/iOS) is open to CSRF attack?

What about the README #138? Will it helps in this scenario? _(I have tried, but just can't get it right)_

**Comment by zquestz** [comment]
@johnsonyeap no you are not open to attack, as the request phase has already completed, and that is where the CSRF could happen. By the time you use the callback, you don't need the state parameter anymore. We use the one time code to do the validation in this flow.
