### ISSUE TITLE
Cannot specify non-SSO scopes

### ISSUE THREAD

**Issue by emirkin** [zquestz/omniauth-google-oauth2#244]
It appears that non-SSO scopes cannot be requested:
```
    gapi.auth.authorize({
      immediate: false
      response_type: 'code'
      cookie_policy: 'single_host_origin'
      client_id: getMeta("google-signin-client_id")
      scope: 'email,profile,gmail.readonly' # <<<
    }, (response) ->
```

I get a 400-invalid_scope error. Is that expected or should I request non-SSO permissions after the user has been authenticated?

**Comment by zquestz** [comment]
You will need to use the fully qualified scopes listed here: https://developers.google.com/gmail/api/auth/scopes

The value should be `https://www.googleapis.com/auth/gmail.readonly`
