### ISSUE TITLE
What is the purpose of having 2 gapi.auth.authorize calls?

### ISSUE THREAD

**Issue by emirkin** [zquestz/omniauth-google-oauth2#245]
In the hybrid flow, there are 2 calls to `gapi.auth.authorize`. Could you please elaborate why?

**Comment by zquestz** [comment]
The thread describing it is here: https://github.com/zquestz/omniauth-google-oauth2/issues/122

In older google examples they used this double auth pattern, but it seems their documentation has changed and they now have an init method to accomplish this as well.
