### ISSUE TITLE
Do not get refresh token after first login

### ISSUE THREAD

**Issue by ngoral** [zquestz/omniauth-google-oauth2#247]
I'm using omniauth-googleauth2 in my rails app. Here's initializers for it:

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2,
    google_client_id,
    google_client_secret,
    scope: "email, profile, https://www.googleapis.com/auth/youtube",
    skip_jwt: true
end
```
However, for some reason, when user is logging into my app for the first time, this do not get me a refresh_token. Furthermore, this does not show a consent screen for a user to confirm that they provide me access to use this info. However, I have a checking in my code, so if user do not have saved refresh_token, I revoke their old token and ask they to confirm consent again. Here's a code:

```
`curl https://accounts.google.com/o/oauth2/revoke?token="#{token}"`
cookies[:auth_back_path] = request.fullpath
redirect_to '/auth/google_oauth2'
```
And after that it works! So, it shows a consent screen for user and then sends me so wishful refresh_token.

Shortely, in other words, consent screen is showed for user only after revoking previously recieved token. (Even if that token was recieved for the first timefor this user)

I do not want to set up prompt: consent in initializer, cause I do not want user to be forced to choose and confirm any time they log in. One time is more than enough.
Is that a bug or a feature?

**Comment by zquestz** [comment]
You have to put the prompt for consent if you wish to get a refresh_token. This is the contract with Google. Nothing we can do on this end.

**Comment by ngoral** [comment]
From [Google Oauth official site](https://developers.google.com/identity/protocols/OAuth2WebServer#preparing-to-start-the-oauth-20-flow):

>  If you don't specify this parameter, the user will be prompted only the first time your app requests access.

So, it should show consent screen. Also, if I manually compose string for request and send it with CURL, it redirects me to consent screen. That's the reason I think smth wrong with your gem.

**Comment by zquestz** [comment]
There is nothing wrong with the gem, you need to make sure to show the consent screen AND request offline access. The key is that offline access is what provides the refresh_token, otherwise you will not get it. The gem doesn't control whether you get a consent screen at all, it merely provides options to google and they direct you as they please.

**Comment by zquestz** [comment]
You get everything working?

**Comment by ngoral** [comment]
I've forked repo and tried to change smth thinking gem could provide parameterg in a wrong way. Still not working. I guess that's really Google Oauth problems, but this is still inundarstandable for me.
I think I can close this.

**Comment by lesce** [comment]
@ngoral  I am having the same issue , I wasn't getting the refresh token and I managed to fix this by adding `prompt: 'consent'`
hope this helps
better late than never :)
