### ISSUE TITLE
README is out of date.

### ISSUE THREAD

**Issue by gbrl** [zquestz/omniauth-google-oauth2#251]
Once I get everything working, I'll try and edit it.

**Comment by jmanian** [comment]
I noticed some possibly conflicting info about what scopes are required. Is that part of what's out of date?

In one place:
> Remember that 'email' and 'profile' scopes are required!

But just below that:
>The email and profile scopes are used by default. By defining your own scope, you override these defaults. If you need these scopes, don't forget to add them yourself!

The latter seems to imply that those two scopes are **not** required.

**Comment by zquestz** [comment]
Yeah they are required. If you don't have those 2 then login will fail.

**Comment by jmanian** [comment]
I just did some testing and it seems like you need "profile" **or** "email" but not both.

I was able to auth and receive tokens with all of these combinations of scopes:
- "profile"
- "email"
- "profile,email"
- "profile,email,calendar.readonly"

But when I tried to do just "calendar.readonly" I received a 403.

And in terms of the data received in the callback, it's basically what you would expect: "email" gives you their email, but not their name; "profile" gives you their name (and locale) but not their email; and "profile,email" gives you the union.

Lastly there's a weird thing with the message shown on the consent screen.
If you ask for "profile" then it shows "View your basic profile info."
If you ask for "email" then it shows "View your email address."
And if you ask for both then it shows both.
But if you do "email" **without** "profile" it also adds "Know who you are on Google."

**Comment by zquestz** [comment]
So email would be required to do anything useful, as that is the only call that would provide you unique information to create the user. So I would say that email is the only "required" item, as without it you would get a name that is not guaranteed to be unique, and there is no way to create valid user records.

**Comment by jmanian** [comment]
Yes, good point. Although I guess you could rely on the uid as a unique ID if you really don't care about the email and you wanted to do "profile" without "email" for some reason. In my case I think I'm going to do "email,calendar" because I don't care about the name, and I don't particularly like that if you ask for "profile" then it talks about Google+ on the consent screen.

**Comment by zquestz** [comment]
Any progress on the doc updates? Would be really nice to get this hammered out. =)

**Comment by gbrl** [comment]
I'm about to re-build our dev server as a production one, so I'll have to go through the process again and i'll take notes. Happening in the next 10 days.

**Comment by reubenbrown** [comment]
Regarding the required scopes, I am using the devise configuration and when explicitly requiring the email scope I noticed this **doesn't** work 

```
config.omniauth :google_oauth2, ENV['GOOGLE_CLIENT_ID'], ENV['GOOGLE_CLIENT_SECRET'], { redirect_uri: ENV['GOOGLE_CALLBACK_URI'], scope: 'email, calendar' }
```

I get a 400 error saying `https://www.googleapis.com/auth/email` is an invalid scope. 

Based on the information [here](https://developers.google.com/identity/protocols/googlescopes) when I change `email` to `userinfo.email` everything works perfectly. Should this also be clarified in the README?

**Comment by jmanian** [comment]
@reubenbrown Hm, I'm currently using the scope `'email,calendar'` and it's working fine. And the page you linked to does also list "email" [under the heading "Google Sign-in."](https://developers.google.com/identity/protocols/googlescopes#google_sign-in)

Did you have it as `'email, calendar'` with the space? Perhaps the space is causing a problem?

**Comment by reubenbrown** [comment]
@jmanian Yeah it's very strange. I tried both `email,calendar` and `email, calendar` and both didn't work

**Comment by zquestz** [comment]
Works for me too, do you have calendar access enabled in the google api console?

**Comment by reubenbrown** [comment]
@zquestz Yup I have it enabled and that scope works fine.

**Comment by zquestz** [comment]
README has been updated. Going to close this thread. Now technically email,profile is correct, as we use the OpenID endpoint https://www.googleapis.com/plus/v1/people/me/openIdConnect to pull data. The userinfo scopes should return the same data, so @reubenbrown if that works for you it should be fine.
