### ISSUE TITLE
second user not getting created

### ISSUE THREAD

**Issue by dmkrovichmix** [zquestz/omniauth-google-oauth2#253]
I'm trying to integrate google authentication into a ruby on rails application.  I thought I had everything setup and working.  Unfortunately, I'm having a bug where a second user is not getting created in the user table.

For example, I log into the site with user A.  After authenticating as that user I can login to my application and a user gets created in the User model.  I then log out.  Next I log in with user B.  After authenticating with google I'm allowed to log into my application.  However, there is no user B created in the User model and it appears that I'm logged in as user A.

Any ideas where to investigate?

**Comment by dmkrovichmix** [comment]
callbackscontroller

class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :google_oauth2, :all
end

**Comment by dmkrovichmix** [comment]
user.rb 

class User < ActiveRecord::Base

  has_many :user2instances
  has_many :instances, through: :user2instances
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
#  devise :database_authenticatable, :registerable, :omniauthable,
#         :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :omniauthable,
         :rememberable, :trackable, :validatable

  
  def self.from_omniauth(auth)
    where(auth.slice(provider: auth.provider, uid: auth.uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def email_required?
    super && provider.blank?
  end

end

**Comment by zquestz** [comment]
So the obvious place to look is in `def self.from_omniauth(auth)`. You should dump on the value of the auth object and make sure your auth.uid field is actually unique. In the examples we generally recommend to use the email address of the user for lookup.

Pretty sure your bug is in there.

**Comment by dmkrovichmix** [comment]
Thanks.  That helped.  I changed my self.from_omniauth(auth) to:

def self.from_omniauth(auth)
    user = User.where(:email => auth.info.email).first
    unless user
      user = User.create(provider: auth.provider,
                         email: auth.info.email
                        )
    end
    user
  end

**Comment by dmkrovichmix** [comment]
Thanks, I'll take a look and see what I can find.

-Dave
