### ISSUE TITLE
OAuth broken for standalone web apps

### ISSUE THREAD

**Issue by avand** [zquestz/omniauth-google-oauth2#254]
Google recently disabled OAuth for standalone web apps:

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

If you try and do this from a web-view (aka "Add to Home Screen"), you'll see an error 403: disallowed_useragent. I can't find a work around.

**Comment by zquestz** [comment]
There is no work around. Google no longer supports this.
