### ISSUE TITLE
:hd parameter not working as array in v0.4.1

### ISSUE THREAD

**Issue by jeffse** [zquestz/omniauth-google-oauth2#256]
I'm using tag v0.4.1, and I am trying to set my :hd parameter as an array as it specifies in the docs:

`hd: ['gmail.com','ptappt.com']`

However, when I try this, I always get the same response:

`Could not authenticate you from GoogleOauth2 because "Invalid hosted domain".`

Setting the :hd parameter to a single string (aka `hd: 'gmail.com'` or `hd: 'ptappt.com'`) works just fine. 

Even setting it to an array with a single value (`hd: ['gmail.com']`) gives the same 'Invalid hosted domain' error.

For what it's worth, the [OpenID docs for the hd parameter](https://developers.google.com/identity/protocols/OpenIDConnect#hd-param) makes no mention of being able to specify multiple domains. It would be nice if I can support it in my app, but I'm beginning to believe that it's not possible even though the omniauth-google-auth2 docs say it is.

**Comment by zquestz** [comment]
So I can't replicate this, but I have an idea what is going on. So here is how I tested:

1) Update the example app to use a hosted domain.
2) I did with and without array syntax for my company domain, both worked perfectly.

```
use OmniAuth::Builder do
  # For additional provider examples please look at 'omni_auth.rb'
  provider :google_oauth2, ENV['GOOGLE_KEY'], ENV['GOOGLE_SECRET'], {access_type: "offline", prompt: "consent", scope: 'userinfo.email,calendar', hd: ['noneofyourbusiness.com'']}
end
```

NOTE: I found that google NEVER returns gmail.com for the hosted domain. This will always fail, which is why I think your having issues. For gmail it returns a response with no hd key.

**Comment by zquestz** [comment]
If you need it to support a hosted domain AND gmail.com, then you need to use `hd: [nil, "DOMAIN"]`. This will do what you want, just tested it locally. =)

**Comment by jeffse** [comment]
Thank you for the writeup! I will look into this some more on Monday.

I may try setting some of the other options that you list there (access_type, prompt, etc.) and see if that gets me anywhere faster too.
