### ISSUE TITLE
Whitelisted Domain Name in provider method won't works

### ISSUE THREAD

**Issue by KanjariyaHardik** [zquestz/omniauth-google-oauth2#258]
Following is my code :

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, ENV["GOOGLE_CLIENT_ID"], ENV["GOOGLE_CLIENT_SECRET"],
    {
        hd: 'domain.com'
    }          
end
```

**Comment by zquestz** [comment]
So I need more context on what you are doing. I tested the hd parameter last week and it works fine. What exact error are you seeing?

**Comment by KanjariyaHardik** [comment]
I want to allow only specific domains to be logged in via Google OAuth2. I have put the above code in my config file that is "omniauth.rb".

I am not getting error, It allows other domain to logged in but I want to allow only specified domains to log in.

**Comment by zquestz** [comment]
Are you using the latest version of the gem? It definitely checks the domain...

```
raise CallbackError.new(:invalid_hd, "Invalid Hosted Domain") unless allowed_hosted_domains.include? @raw_info['hd']
```

After the response is received it checks to make sure the hd parameter in @raw_info includes the domain you specified.

**Comment by KanjariyaHardik** [comment]
Yes, I am using latest version of gem

**Comment by zquestz** [comment]
Can you provide me the output of the response you receive from the gem? I want to see what is contained in the `hd` key. It should be returning your domain, this should definitely be raising the CallbackError.

**Comment by KanjariyaHardik** [comment]
Do you need the response that I have received from callback of google ?

**Comment by zquestz** [comment]
Yep, exactly.

**Comment by KanjariyaHardik** [comment]
<ActionController::Parameters {"state"=>"9044a16146c5ff8e9021e238ee055fa153c1b6e4a5a34b00", "code"=>"4/fvxV2uUy0-YvAQESGjdI-wlkI_YkKsI-h7KNugCUQXM", "controller"=>"sessions", "action"=>"create", "provider"=>"google_oauth2"} permitted: false>

**Comment by zquestz** [comment]
That contains none of the raw info, I need the actual response from google, not the controller values. It should include things like the email address etc.

**Comment by KanjariyaHardik** [comment]
How can I be able to check this response ? I won't have much idea of it..

**Comment by zquestz** [comment]
It should look something like the response in the README.md file.

```
{
    :provider => "google_oauth2",
    :uid => "123456789",
    :info => {
        :name => "John Doe",
        :email => "john@company_name.com",
        :first_name => "John",
        :last_name => "Doe",
        :image => "https://lh3.googleusercontent.com/url/photo.jpg"
    },
    :credentials => {
        :token => "token",
        :refresh_token => "another_token",
        :expires_at => 1354920555,
        :expires => true
    },
    :extra => {
        :raw_info => {
            :sub => "123456789",
            :email => "user@domain.example.com",
            :email_verified => true,
            :name => "John Doe",
            :given_name => "John",
            :family_name => "Doe",
            :profile => "https://plus.google.com/123456789",
            :picture => "https://lh3.googleusercontent.com/url/photo.jpg",
            :gender => "male",
            :birthday => "0000-06-25",
            :locale => "en",
            :hd => "company_name.com"
        },
        :id_info => {
            "iss" => "accounts.google.com",
            "at_hash" => "HK6E_P6Dh8Y93mRNtsDB1Q",
            "email_verified" => "true",
            "sub" => "10769150350006150715113082367",
            "azp" => "APP_ID",
            "email" => "jsmith@example.com",
            "aud" => "APP_ID",
            "iat" => 1353601026,
            "exp" => 1353604926,
            "openid_id" => "https://www.google.com/accounts/o8/id?id=ABCdfdswawerSDFDsfdsfdfjdsf"
        }
    }
}
```

**Comment by zquestz** [comment]
It should be contained in `request.env["omniauth.auth"]`

**Comment by KanjariyaHardik** [comment]
`raw_info=#<OmniAuth::AuthHash email="john@company_name.com" email_verified="true" family_name="test" given_name="john" hd="company_name.com" kind="plus#personOpenIdConnect" locale="en" name="john test" picture="https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAI/AAAAAAAAA/4252rscv5M/photo.jpg?sz=50" sub="100725351299656487349">> info=#<OmniAuth::AuthHash::InfoHash email="john@company_name.com" first_name="john" image="https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAI/AAAAAAAAA/425scbv5M/photo.jpg" last_name="test" name="john test"> provider="google_oauth2" uid="1007253519966487349">
`
I have received above response, But the `HD` params in not the one that I had set in my config file that is "omniauth.rb".

**Comment by zquestz** [comment]
Make sure you are not trying to hot reload code when making changes to the initializer, as they will not update reliably. Make sure you completely stop, then start your app when making changes. You might also want to play with the example app included in the repo, as it is far easier to debug.

**Comment by KanjariyaHardik** [comment]
Okey, I'll go for example app too.. and get back to you If I do face any issue.
Thanks for the help.

**Comment by zquestz** [comment]
Any luck?

**Comment by zquestz** [comment]
Closing, if it needs to be revisited we can reopen this issue.

**Comment by gisellerocha** [comment]
Hello!
I have solved the 'invalid_hd' exception with the following code:

`config/initializers/omniauth.rb`
###
`Rails.application.config.middleware.use OmniAuth::Builder do
provider :google_oauth2, Rails.application.secrets.omniauth_provider_key, Rails.application.secrets.omniauth_provider_secret,
  {
      hd: "domain.com"
  }`
`end`
`OmniAuth.config.on_failure = SessionsController.action(:failure)`
###
`app/controllers/sessions_controller.rb`
###
`  def failure
    redirect_to root_url, alert: "Authentication error"
  end`

###
I'm a beginner in RoR!

**Comment by gisellerocha** [comment]
Hello!
I have solved the 'invalid_hd' exception with the following code:

`config/initializers/omniauth.rb`
###
`Rails.application.config.middleware.use OmniAuth::Builder do
provider :google_oauth2, Rails.application.secrets.omniauth_provider_key, Rails.application.secrets.omniauth_provider_secret,
  {
      hd: "domain.com"
  }`
`end`
`OmniAuth.config.on_failure = SessionsController.action(:failure)`
###
`app/controllers/sessions_controller.rb`
###
`  def failure
    redirect_to root_url, alert: "Authentication error"
  end`

###
I'm a beginner in RoR!
