### ISSUE TITLE
Scope of access token doesn't correspond to the expected scope

### ISSUE THREAD

**Issue by Mcdostone** [zquestz/omniauth-google-oauth2#259]
Hi,
I want to access to the google drive API. So I put 'drive' into the scope param !

```
OmniAuth.config.logger = Rails.logger

Rails.application.config.middleware.use OmniAuth::Builder do
	provider :google_oauth2, 'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET' {
      	        :scope => 'email,profile,drive',
		:prompt => "select_account",
		:image_aspect_ratio => "square",
		:image_size => 50,
		:include_granted_scopes => 'true',
		:access_type => 'online'
  	}
end
```

But I can't access to the google drive API. Indeed, I Checked properties of my access token thanks to [https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=XXXXXXX](https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=XXXXXXX), I got:

```
{
  "issued_to": "XXXXXX",
  "audience": "XXXX",
  "user_id": "XXXXXX",
  "scope": "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile",
  "expires_in": 761,
  "email": "XXX@XXX",
  "verified_email": true,
  "access_type": "offline"
}
```

I should get :
`"scope": "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile  https://www.googleapis.com/auth/drive"`

I tested with [oauthplayground](https://developers.google.com/oauthplayground/ ) and I got the correct scope.

Is it normal ?

**Comment by zquestz** [comment]
So you can't use just "drive" as the scope, you need to pass the fully qualified scope. Use `email.profile,https://www.googleapis.com/auth/drive`. That should fix it.

**Comment by Mcdostone** [comment]
Nothing changes, I had the same scope:

```
Rails.application.config.middleware.use OmniAuth::Builder do
	provider :google_oauth2, Rails.application.secrets.GOOGLE_CLIENT_ID, Rails.application.secrets.GOOGLE_CLIENT_SECRET
  	{
      	:scope => 'email,profile,https://www.googleapis.com/auth/drive',
		:prompt => "select_account",
		:image_aspect_ratio => "square",
		:image_size => 50,
		:include_granted_scopes => 'true',
		:access_type => 'online'
  }
end
```

```
{
  "azp": "XXXX",
  "aud": "XXX",
  "sub": "XXXXXX",
  "scope": "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile",
  "exp": "1482523261",
  "expires_in": "3568",
  "email": "XXX",
  "email_verified": "true",
  "access_type": "offline"
}
```

**Comment by zquestz** [comment]
Yeah that is very odd, the gem is passing it to google... so for some reason google isn't respecting the passed in scope. You might want to try an offline access_type to see if that helps at all.

**Comment by Mcdostone** [comment]
hmmm nothing changes ! So you think there is a problem with the google API ?

**Comment by zquestz** [comment]
Yeah that is what it seems like. You might want to test with the included example app just to make sure.

**Comment by zquestz** [comment]
Any luck?

**Comment by zquestz** [comment]
Closing, if it needs to be revisited we can reopen this issue.

**Comment by tknazn** [comment]
I am having a similar issue - but with calendar scope. 
Any suggestions?

**Comment by tknazn** [comment]
@zquestz  I actually resolved this issue by removing the {}. See below.
Not sure why it would cause the insufficient scope issue. Doc may need to be updated. 

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, ENV["GOOGLE_CLIENT_ID"], ENV["GOOGLE_CLIENT_SECRET"],
    
      :name => "google",
      :scope => "email,profile,plus.me,https://www.googleapis.com/auth/calendar",
      :prompt => "select_account",
      :image_aspect_ratio => "square",
      :image_size => 50
    
end
```
