### ISSUE TITLE
oauth state isn't honored

### ISSUE THREAD

**Issue by KevinColemanInc** [zquestz/omniauth-google-oauth2#260]
I can't get this [omniauth-state](https://github.com/zquestz/omniauth-google-oauth2#omniauth-state) to work like the read me says.

Looking [here](https://github.com/zquestz/omniauth-google-oauth2/blob/master/lib/omniauth/strategies/google_oauth2.rb#L40) within `omniauth-google-oauth2`, I see that it is setting `session['omniauth.state']` from the configured state from the initializer which doesn't really do anything, because `session['omniauth.state']` is just used to check the state later, not actually setting it in the request.

Looking within the `omniauth-oauth2` gem [here](https://github.com/intridea/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L52), if you don't specify the state in the initializer, it uses `SecureRandom.hex(24)` to generate a state value.

It seems like the the suggestion in the readme is a good way to make every oauth request invalid, because the state in the session won't match the random hex.

So it seems there isn't a good way to set the state without monkey patching something on a per request basis?

**Comment by zquestz** [comment]
@KevinColemanInc this is not accurate. It only sets it if the initializer includes a state option. That is indeed sent to google, and then sent back as the state. So that flow is correct.

In fact you can test with the included sample app, and that does the right thing. Remember the request includes all the values from authorize_options, so the state is definitely sent. What exact error are you seeing?

**Comment by KevinColemanInc** [comment]
@zquestz I think maybe I didn't explain this correctly.  Yes, setting it in the initializer works fine.  I want to set the omniauth state param in my controller, just like it says that I can do here: 
https://github.com/zquestz/omniauth-google-oauth2#omniauth-state.

It sounds like I can set the state to what I want it to be on a per request basis by adding a method to my application controller.

I created a sample rails app demonstrating the issue. https://github.com/KevinColemanInc/google_auth2_state_bug

it seems to completely ignores the state variable that I set in the controller. And like I mentioned above, I can't find anywhere in the source code that would make this work.

**Comment by zquestz** [comment]
Ahh I see the issue. Have you tried just including the state param in the link_to call for the login itself? Those params also cascade to the request to google.  For example in the sample app, this works:

```
<a href='/auth/google_oauth2?state=ANYSTATEYOUWANT'>Sign in with Google</a>
```

**Comment by KevinColemanInc** [comment]
awesome! this works for my purposes.  thank you for your help.

**Comment by zquestz** [comment]
Glad it worked for you. I also removed the confusing state handling in the README. =)
