### ISSUE TITLE
Question about the library with android authentication

### ISSUE THREAD

**Issue by eugenio1590** [zquestz/omniauth-google-oauth2#269]
I am using this library to clients authentication on the backend server. The process is the next:

1. The clients open the app using the browser or the android app.
2. Go to the login page
3. Click on the google button.
4. Select the google account for authenticating.
  4.1. In the android app
    4.1.1. Using the play service on android app, the app get the token id

      ```
      // Signed in successfully, show authenticated UI.
      GoogleSignInAccount acct = result.getSignInAccount();
      Log.d("LOGIN", "Id: "+acct.getIdToken());
      ```

    4.1.2. Ok, in this step, the android app should send the token_id to the library for authenticating the backend server. But, I'm not sure the end-point for this in the rails app. Can you help me with this?

    4.2. In the web app, the process is similar.

I am using this library together with the "[devise token auth](https://github.com/lynndylanhurley/devise_token_auth)" library

**Comment by zquestz** [comment]
The url should be `/auth/google_oauth2/callback`

**Comment by eugenio1590** [comment]
OK, perfect. But, the end-point needed the Auth Hash, like this:

 ```
{
    :provider => "google_oauth2",
    :uid => "123456789",
    :info => {
        :name => "John Doe",
        :email => "john@company_name.com",
        :first_name => "John",
        :last_name => "Doe",
        :image => "https://lh3.googleusercontent.com/url/photo.jpg"
    },
    :credentials => {
        :token => "token",
        :refresh_token => "another_token",
        :expires_at => 1354920555,
        :expires => true
    },
    :extra => {
        :raw_info => {
            :sub => "123456789",
            :email => "user@domain.example.com",
            :email_verified => true,
            :name => "John Doe",
            :given_name => "John",
            :family_name => "Doe",
            :profile => "https://plus.google.com/123456789",
            :picture => "https://lh3.googleusercontent.com/url/photo.jpg",
            :gender => "male",
            :birthday => "0000-06-25",
            :locale => "en",
            :hd => "company_name.com"
        },
        :id_info => {
            "iss" => "accounts.google.com",
            "at_hash" => "HK6E_P6Dh8Y93mRNtsDB1Q",
            "email_verified" => "true",
            "sub" => "10769150350006150715113082367",
            "azp" => "APP_ID",
            "email" => "jsmith@example.com",
            "aud" => "APP_ID",
            "iat" => 1353601026,
            "exp" => 1353604926,
            "openid_id" => "https://www.google.com/accounts/o8/id?id=ABCdfdswawerSDFDsfdsfdfjdsf"
        }
    }
}

 ```

I found a temporary solution in this account: https://github.com/elcurator/android-google-plus-omniauth-tutorial   But, Is there a better solution?

**Comment by eugenio1590** [comment]
Ok, perfect. With code and redirect_uri params, It worked correctly. Thanks

**Comment by eugenio1590** [comment]
Ok with the code and redirect_uri parameters worked well. But I get the following response from the server in the android application.

![screenshot_20170216-112739](https://cloud.githubusercontent.com/assets/11418577/23029770/fbbf6228-f441-11e6-81db-537ad594bfd5.png)

It is an Html response to logging in. Change the parameter for access_token and I got the same answer. I'm using this tutorial for android.

Https://developers.google.com/identity/sign-in/android/v1/offline-access

The request is this:

```
02-16 11:52:24.198 15877-16484/ D/OkHttp: --> GET https://example.herokuapp.com/api/v1/auth/google_oauth2.json?access_token=4/t_TVSPSK8CY21cX-LlkZXlKsFT2HeIyRZkvZwntRTSI&redirect_uri=https://example.herokuapp.com/api/v1/auth/google_oauth2/callback http/1.1
02-16 11:52:24.198 15877-16484/ D/OkHttp: Access-Token: 
02-16 11:52:24.198 15877-16484/ D/OkHttp: Client: 
02-16 11:52:24.198 15877-16484/ D/OkHttp: Uid: 
02-16 11:52:24.198 15877-16484/ D/OkHttp: --> END GET
```

**Comment by zquestz** [comment]
Yeah you want to use the callback url... Sorry about that. For instance:

http://localhost:3000/auth/google_oauth2/callback?state=STATE_VALUE&code=CODE

Or you can just pass the access_token if you have it. Then it should reply with the json response.

**Comment by eugenio1590** [comment]
Ok, The request is this:

```
02-16 20:54:40.522 5582-6117/ D/OkHttp:  --> GET https://example.herokuapp.com/api/v1/auth/google_oauth2/callback.json?resource_class=User&code=4/hNPXTWia27agrvVUGcbS_LwCIFq00BV0jP6GQ1ViQNM http/1.1
02-16 20:54:40.522 5582-6117/ D/OkHttp: Access-Token: 
02-16 20:54:40.522 5582-6117/ D/OkHttp: Client: 
02-16 20:54:40.522 5582-6117/ D/OkHttp: Uid: 
02-16 20:54:40.522 5582-6117/ D/OkHttp: --> END GET
```

And the server responds with an error (500), the first was with the name of the class, so add the resource_class parameter in the request. But, I finally got this error:

```
2017-02-17T01:24:42.473131+00:00 app[web.1]: F, [2017-02-17T01:24:42.473078 #4] FATAL -- : [26fd19bb-156d-4c19-8bb4-9ac75da29c23] NoMethodError (undefined method `[]' for nil:NilClass):
2017-02-17T01:24:42.473216+00:00 app[web.1]: F, [2017-02-17T01:24:42.473168 #4] FATAL -- : [26fd19bb-156d-4c19-8bb4-9ac75da29c23]   
2017-02-17T01:24:42.473267+00:00 app[web.1]: F, [2017-02-17T01:24:42.473215 #4] FATAL -- : [26fd19bb-156d-4c19-8bb4-9ac75da29c23] vendor/bundle/ruby/2.2.0/gems/devise_token_auth-0.1.39/app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:236:in `get_resource_from_auth_hash'
```

**Comment by zquestz** [comment]
You want to POST to that endpoint, not GET.

**Comment by eugenio1590** [comment]
The problem is that the following dumps are empty.

- Toggle session dump
- Toggle env dump

So, for example, the "oparams" field does not exist.

oparams = request.env['omniauth.params'] 

For now, I will be focusing on other things. But it would be excellent to be able to fix this error.

**Comment by zquestz** [comment]
It should be in `request.env["omniauth.auth"]`
