### ISSUE TITLE
Also not getting refresh token

### ISSUE THREAD

**Issue by Turelyo** [zquestz/omniauth-google-oauth2#27]
Similarly to https://github.com/zquestz/omniauth-google-oauth2/issues/16, I'm not receiving a refresh token -- only the token that expires after an hour.  I'm not configuring this in devise, though.  I'm configuring it separately as is done in the examples for this gem.

The line in my omni_auth.rb initializer is as follows:

provider :google_oauth2, client_id, client_secret, :scope => 'https://www.googleapis.com/auth/analytics.readonly', :display => 'popup'

I've tried pretty much every combination of approval_prompt and access_type, but to no avail.

The response I get back is as follows (sensitive fields filtered out):

{ :email => "[filtered]", :name=>"", :uid => "[filtered]", :provider => "Google_oauth2", :token => "[filtered]" }

**Comment by sammieValsangkar** [comment]
In my case 
```scope: ['email',
    'https://www.googleapis.com/auth/gmail.modify'],
    access_type: 'offline', approval_prompt: 'force', prompt: 'consent'}```
returned  me refresh token
