### ISSUE TITLE
Mobile client + Server Client ID requires empty redirect_uri

### ISSUE THREAD

**Issue by ened** [zquestz/omniauth-google-oauth2#272]
According to this page https://developers.google.com/identity/sign-in/ios/offline-access, it is possible to login on a users mobile device (in that case iOS), retrieve a code (just like in the JS SDK) and send it to the server.

The tricky bit is inside the code section on that page:

>               REDIRECT_URI)  // Specify the same redirect URI that you use with your web
>                              // app. If you don't have a web version of your app, you can
>                              // specify an empty string.

Right now, the gem supports the basic hybrid flow (for the JavaScript login), but in case of the mobile login, the REDIRECT_URI needs to be an empty string. ATM, it's being set to "postmessage". Using "postmessage", I will get a uri_redirect_mismatch error response from Google:

```
(google) Authentication failure! invalid_credentials: OAuth2::Error, redirect_uri_mismatch: 
{
  "error" : "redirect_uri_mismatch"
}
```

I was able to get it working with a small change in `custom_build_access_token`:

```
        if request.xhr? && request.params['code']
          verifier = request.params['code']
          redirect_uri = request.params['redirect_uri'] || 'postmessage'
          client.auth_code.get_token(verifier, get_token_options(redirect_uri), deep_symbolize(options.auth_token_params || {}))
```

This requires a redirect_uri parameter (with value "") to be sent from a mobile client, when storing the token. Happy to get comments on this.

**Comment by zquestz** [comment]
Fix has been merged.
