### ISSUE TITLE
Possible for any oauth2 provider?

### ISSUE THREAD

**Issue by derTobsch** [zquestz/omniauth-google-oauth2#275]
Could it be possible to use this plugin for any other oauth2 provider and if not how could it be done? i want to use this plugin to authenticate against my own oauth2 provider

**Comment by zquestz** [comment]
This is not a generic oauth gem. This is very specific to google. There are a number of other omniauth oauth2 strategies here: https://github.com/omniauth/omniauth/wiki/list-of-strategies
