### ISSUE TITLE
defining controller action for callback

### ISSUE THREAD

**Issue by BKSpurgeon** [zquestz/omniauth-google-oauth2#278]
Hi there Mr Joshua

thank you very much for making this code available to the public.

I have a further question. I notice that there is no controller/action defined for the call back redirect - doesn't it have to be defined?

Or if i add OmniAuth::Builder to the middle ware - will that take care of everything?

Your advice is much appreciated.

rgds

Ben

**Comment by zquestz** [comment]
By default the callback is at `/auth/google_oauth2/callback`. Documentation for devise is included in the README.
