### ISSUE TITLE
Devise not respecting access_type configuration parameter

### ISSUE THREAD

**Issue by bhgames** [zquestz/omniauth-google-oauth2#280]
As far as I can tell, the config.omniauth method of Devise is not respecting your access_type parameter, because I'm trying to use it to get offline access but it appears to be ignoring it.

Here is my code from my Devise initializer:

` config.omniauth :google_oauth2, ENV['GOOGLE_CLIENT_ID'], ENV['GOOGLE_API_SECRET'], { scope: 'youtube.readonly,youtube.upload,plus.login,youtubepartner,email', access_type: :offline }
`

Here is the resulting page from Google on sign-in:

https://screencast.com/t/W0d2JAYLdA

Here is the request it made on the backend:

`/users/auth/google_oauth2/callback?state=[REDACTED]&code=[REDACTED]&authuser=0&session_state=[REDACTED]&prompt=none`

The hash returned:
` {"provider"=>"google_oauth2",
 "uid"=>"[REDACTED]",
 "info"=>
  {"name"=>"[REDACTED]",
   "email"=>"[REDACTED]",
   "first_name"=>"[REDACTED]",
   "last_name"=>"[REDACTED]",
   "image"=>"[REDACTED]",
   "urls"=>{"Google"=>"[REDACTED]"}},
 "credentials"=>
  {"token"=>"[REDACTED]",
   "expires_at"=>1492609680,
   "expires"=>true},
    ...
`

And here are the controller and routes.rb:

`
      class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
        def google_oauth2
          @user = User.from_omniauth(request.env["omniauth.auth"])

        if @user.persisted?
          sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
          set_flash_message(:notice, :success, :kind => "Google Oauth2") if is_navigational_format?
        else
          session["devise.google_oauth2_data"] = request.env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end

      def failure
        redirect_to root_path
      end
    end
`

(I'm sorry, I spent a while trying to figure out why the backticks are ignoring the top three lines of this controller code.)

` 
devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
`

Any chance you can give some insight into this? I'd really appreciate it. Thanks!

**Comment by zquestz** [comment]
In order to request offline access you have to also pass the `consent` key. For example:

```
{access_type: "offline", prompt: "consent", scope: 'youtube.readonly,youtube.upload,plus.login,youtubepartner,email'}
```

**Comment by zquestz** [comment]
Closing as I believe the consent prompt will resolve this issue. Let me know if it doesn't work.

**Comment by bhgames** [comment]
It did. Thanks.
