### ISSUE TITLE
Redirect Uri Mismatch Error

### ISSUE THREAD

**Issue by laranicolas** [zquestz/omniauth-google-oauth2#281]
Hi, I'm trying to make it work **One Time Code Flow** using devise plus `omniauth-google-oauth2` gem and when I send request: 

```
http://localhost:3000/users/auth/google_oauth2/callback?
code=4/6IHeN49qX4gpQ0GdgqcPa6O1u_G_GIu27IH7Ps0T-Cg
```
(`code` I get from playground using `client_id` and `client_secret` from my own proyect)

I get always `redirect_uri_mismatch` error.

**Output Server**
```
15:48:42 web.1    | I, [2017-05-11T15:48:42.013299 #46922]  INFO -- omniauth: (google_oauth2) Callback phase initiated.
15:48:42 web.1    | E, [2017-05-11T15:48:42.835223 #46922] ERROR -- omniauth: (google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, redirect_uri_mismatch: 
15:48:42 web.1    | {
15:48:42 web.1    |   "error" : "redirect_uri_mismatch"
15:48:42 web.1    | }
15:48:42 web.1    | I, [2017-05-11T15:48:42.868512 #46922]  INFO -- : method=GET path=/users/auth/google_oauth2/callback format=*/* controller=OmniauthCallbacksController action=failure status=302 duration=31.96 view=0.00 db=0.00 location=http://localhost:3000/
```

**Google oauth configuration at config/initializers/devise.rb`**
```
  config.omniauth :google_oauth2, ENV['GOOGLE_CLIENT_ID'], ENV['GOOGLE_CLIENT_SECRET'], {
    :skip_jwt => true,
    :provider_ignores_state => true,
    :scope => 'email,profile'
  }
```

**Gemfile**
```
gem 'omniauth-facebook', '~> 4.0.0'
gem 'omniauth-facebook-access-token', github: 'gnumarcelo/omniauth-facebook-access-token'
gem 'omniauth-google-oauth2'
gem 'omniauth-oauth2', '~> 1.3.1'
```

Permissions and credentials are configured as I read in the site.

I read in many posts about this error and I have tried a lot recommended solutions, but I still having same error.

**Note:** Normal oauth process with sign in google buttons is working.

**Comment by zquestz** [comment]
Have you tried sending an empty redirect_uri?

```
http://localhost:3000/users/auth/google_oauth2/callback?
code=4/6IHeN49qX4gpQ0GdgqcPa6O1u_G_GIu27IH7Ps0T-Cg&redirect_uri=
```

Also are you doing this via ajax or a normal request?

**Comment by laranicolas** [comment]
If I send with empty `redirect_uri` I get `Missing parameter: redirect_uri`

```
10:02:24 web.1    | I, [2017-05-12T10:02:24.337045 #50145]  INFO -- omniauth: (google_oauth2) Callback phase initiated.
10:02:25 web.1    | E, [2017-05-12T10:02:25.015735 #50145] ERROR -- omniauth: (google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, invalid_request: Missing parameter: redirect_uri
10:02:25 web.1    | {
10:02:25 web.1    |   "error" : "invalid_request",
10:02:25 web.1    |   "error_description" : "Missing parameter: redirect_uri"
10:02:25 web.1    | }
10:02:28 web.1    | I, [2017-05-12T10:02:28.458940 #50145]  INFO -- : method=GET path=/users/auth/google_oauth2/callback format=*/* controller=OmniauthCallbacksController action=failure status=302 duration=2507.16 view=0.00 db=0.00 location=http://localhost:3000/
```

It is a normal request, I'm using **Postman** to send the request.

**Comment by zquestz** [comment]
Yeah that won't work. Right now the code only supports sending the "code" parameter via an ajax request, otherwise you need to pass it a valid redirect_uri or it will fail.

**Comment by laranicolas** [comment]
I just add to Postman the headers related with an ajax request and doesn't works.

**Headers:**
```
Content-Type      application/json
X-Requested-With  XMLHttpRequest
```
I continue getting same response `redirect_uri` error.

Also I tried the second option sending a normal request with `redirect_uri` query string with `http:/localhost:3000/users/auth/google_oauth2/callback` value (same value as developers console).

I don't know what else can be...

**Comment by zquestz** [comment]
AJAX requests should definitely work, as they work fine within javascript. We have lots of users already using this flow.

**Comment by laranicolas** [comment]
How I define on `devise.rb` config file the `full_host` attibute?, is required?

```
OmniAuth.config.full_host = Rails.env.production? ? 'https://domain.com' : 'http://localhost:3000'
```

I used something I saw on a closed PR but also didn't work either.

```
config.omniauth :google_oauth2, ENV['GOOGLE_CLIENT_ID'], ENV['GOOGLE_CLIENT_SECRET'], {
                  :skip_jwt => true,
                  :provider_ignores_state => true,
                  :scope => 'email,profile',
                  setup: (lambda do |env|
                    request = Rack::Request.new(env)
                    env['omniauth.strategy'].options['token_params'] = {:redirect_uri => 'https://localhost:3000/users/auth/google_oauth2/callback'}
                  end)
```

Do you have a complete client where I can test the whole process?, now I'm using mix of google playground and mix of Postman client.

**Comment by zquestz** [comment]
You should not need to set it, but the top example works fine. As for a full implementation, one is included in the examples folder. There is also a javascript example in the README.

**Comment by laranicolas** [comment]
I just create an html file with **Sign In** button using the javascript suggested on README, first step getting the code from google is working fine but second step requesting to the server is still failing and getting `redirect_uri` error.

What else I can do?

**Comment by zquestz** [comment]
Does it work with the normal flow without using javascript for you?

**Comment by zquestz** [comment]
I just added an example that I tested locally and can confirm is working. Please pull the latest changes and test it out. Make sure to replace YOUR_CLIENT_ID.

**Comment by laranicolas** [comment]
I'm using **One Time Flow** but not as monolythic application, ergo  I'm using Rails as api and frontend as simple `.html` with `.js`.

```
<html>

  <head>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://apis.google.com/js/client:plus.js"></script>
  </head>

  <body>
    <button class="googleplus-login">Sign In</button>
    <script type="text/javascript">
      $(function() {
        $('.googleplus-login').click(function(e) {
          e.preventDefault();
          gapi.auth.authorize({
            immediate: false,
            response_type: 'code',
            cookie_policy: 'single_host_origin',
            client_id: '545166989362-b9to6579h76grauak7s1sj9gekg8m0j6.apps.googleusercontent.com',
            // client_id: 'CLIENT_ID',
            scope: 'email profile'
          }, function(response) {
            if (response && !response.error) {
              // google authentication succeed, now post data to server.
              console.log(response);
              jQuery.ajax({
                type: 'POST',
                url: "http://localhost:3000/users/auth/google_oauth2/callback",
                data: response,
                success: function(data) {
                  // response from server
                  console.log("Getting data:" + data);
                }
              });
            } else {
              // google authentication failed
              console.log("Failing");
            }
          });
        });
      });
    </script>
  </body>

</html>
```

But the problems is in the backend.

**Comment by zquestz** [comment]
That is no different than how the example is structured. There is a simple HTML view with JS, then a backend app in Sinatra. Are you sure you setup the google side correctly? Did you follow the steps in the README and setup your app at https://code.google.com/apis/console/ ?

**Comment by laranicolas** [comment]
Yes I know it is pretty similar, but I wanted you to know exactly the stack, I tried everything.

Yes I have the apis enable, origins javascript configured and `redirect_uri` configured.

**Comment by zquestz** [comment]
You should have had to setup Authorized Redirect URI's... Something like `https://localhost:3000/auth/google_oauth2/callback`

**Comment by zquestz** [comment]
Does the example app, as it is in the repo work for you? If not there is a setup problem in your Google console. You should debug that before using your own app.

**Comment by laranicolas** [comment]
Ok I will see how to run that sinatra example.

**Comment by zquestz** [comment]
It should be easy. There is a Gemfile, just install the gems with bundler then run `rackup -p <PORT>`. I have mine setup on port 3000.

**Comment by laranicolas** [comment]
but I know google configurations are fine because I also have normal flow on the site with **Google** button working.

**Comment by laranicolas** [comment]
Yes is working on that project, only I have to add another callback to developers google console `http://localhost:3000/auth/google_oauth2/callback` (without users). 

Now we can discard it is frontend and google configurations values.

**Comment by zquestz** [comment]
Glad you are making progress. =)

**Comment by laranicolas** [comment]
Very weird I tried everything.. **Normal flow** is working but **One Time Code Flow** not.

I debugged Google Omniauth2, specifically on `custom_build_access_token` method:

```
def custom_build_access_token
        access_token =
        if request.xhr? && request.params['code']
          verifier = request.params['code']
          client.auth_code.get_token(verifier, get_token_options('postmessage'), deep_symbolize(options.auth_token_params || {}))
        elsif request.params['code'] && request.params['redirect_uri']
          verifier = request.params['code']
          redirect_uri = request.params['redirect_uri']
          client.auth_code.get_token(verifier, get_token_options(redirect_uri), deep_symbolize(options.auth_token_params || {}))
        elsif verify_token(request.params['access_token'])
          ::OAuth2::AccessToken.from_hash(client, request.params.dup)
        else
          verifier = request.params["code"]
          puts verifier
          puts callback_url
          puts options.auth_token_params.inspect
          client.auth_code.get_token(verifier, get_token_options(callback_url), deep_symbolize(options.auth_token_params))
        end
```

I can see code that `code` and `callback_url` are good.

And  the output of `options` seems to be well:

```
14:51:56 web.1    | #<OmniAuth::Strategy::Options access_type="offline" auth_token_params=#<OmniAuth::Strategy::Options> authorize_options=[:access_type, :hd, :login_hint, :prompt, :request_visible_actions, :scope, :state, :redirect_uri, :include_granted_scopes, :openid_realm] authorize_params=#<OmniAuth::Strategy::Options> client_id="***********" client_options=#<OmniAuth::Strategy::Options authorize_url="/o/oauth2/auth" site="https://accounts.google.com" token_url="/o/oauth2/token"> client_secret="************" jwt_leeway=60 name="google_oauth2" prompt="consent" provider_ignores_state=true redirect_uri="http://localhost:3000/users/auth/google_oauth2/callback" setup=false skip_friends=true skip_image_info=true skip_info=false skip_jwt=true token_options=[] token_params=#<OmniAuth::Strategy::Options>>
```

What else I can test to find why is returning `redirect_uri` error?

**Comment by zquestz** [comment]
To be honest I would need to see your app and debug it a bit myself. However you shouldn't be falling into the else block, or something is wrong. Technically the gem is designed to only handle the one time code from an XHR request, or the code with a redirect_uri via a normal request. There should never be a time that only code is passed via a normal request.

It would also be very useful if you could provide an exact stack trace so I can see exactly where it is failing.

**Comment by laranicolas** [comment]
Done, is working!

It was a very difficult thing to debug because about the response error, as you said the request must be Ajax so I inspected your gem and I figured out that was taking another flow. Thanks for support.

The problem was that as we are using jQuery to do ajax request, will not send the header `X-Requested-With` (HTTP_X_REQUESTED_WITH) = XMLHttpRequest, because it is cross domain, so I added headers to jquery requests and know is working:

```
$.ajax({  
                type: 'GET',
                url: 'http://localhost:3000/users/auth/google_oauth2/callback?code='+response.code,
                headers: {
                  'X-Requested-With': 'XMLHttpRequest'
                },
                success: function(data) {
                  // response from server
                  console.log("Getting data:" + JSON.parse(data));
                }
```

**Comment by kikocastro** [comment]
hi @laranicolas 

Had the same problems you had. I still had to call a reload for it to work.

```
if (response && !response.error) {
          // google authentication succeed, now post data to server.
          jQuery.ajax({
            type: 'GET', url: "/users/auth/google_oauth2/callback?code=" + response.code,
            headers: {
              'X-Requested-With': 'XMLHttpRequest'
            },
            success: function() {
              location.reload();
            }
          });
```

**Comment by nimzco** [comment]
In my case, what solved the problem was adding the param`{ redirect_uri: 'postmessage' }` along with the code, and the Google response when sending my GET request to `auth/google_oauth2/callback`.

The JS code looks like:
```js
window.gapi.auth2.authorize(
  {
    client_id:'xxx',
    cookie_policy: 'single_host_origin',
    scope: 'email profile',
    response_type: 'code',
  },
  async (googleResponse: any) => {
    if (googleResponse && !googleResponse.error) {
      // google authentication succeed, now post data to server.
      const response = await fetch(
        `http://localhost:3000/admins/auth/google_oauth2/callback?${new URLSearchParams(
          { ...googleResponse, redirect_uri: 'postmessage' }
        )}`
      )
    } else {
      // google authentication failed
    }
  }
)
```
