### ISSUE TITLE
Cannot display consent view for email and profile

### ISSUE THREAD

**Issue by Rigel89** [zquestz/omniauth-google-oauth2#282]
I'm configuring the the gem to work with Devise but i cannot get it to display the consent view for the email and profile. If i add other informations such as calendar it will pop up by asking the permission to use the other scopes but email and profile are never displayed.

I set up a pretty basic example:
config.omniauth :google_oauth2,
                  Rails.application.oauth_configuration['google']['credentials']['client_id'],
                  Rails.application.oauth_configuration['google']['credentials']['client_secret'],
                  {
                      access_type: "online",
                      prompt: "consent",
                      scope: "email,profile,calendar"
                  }

**Comment by zquestz** [comment]
Google is the one that displays the dialog. I tested this myself and found it only says calendar, but all the information from the other scopes is returned! Seems they have changed the confirmation screen.
