### ISSUE TITLE
Refresh Token not present in auth_hash.credentials

### ISSUE THREAD

**Issue by droberts-ada** [zquestz/omniauth-google-oauth2#285]
I need offline access to user accounts, which means I need to be able to refresh the Google access token. However, I am not able to pull the refresh token out of the auth hash.

This one feels a lot like #27, but as far as I can tell I'm doing everything discussed in that thread and still no refresh token.

My `config/initializers/omniauth.rb`:

```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2,
      ENV["GOOGLE_OAUTH_CLIENT_ID"],
      ENV["GOOGLE_OAUTH_CLIENT_SECRET"],
      {
        scope: 'email profile spreadsheets drive',
        access_type: 'offline',
        approval_prompt: 'force'
      }
end
```

In my auth callback I log `request.env['omniauth.auth']['credentails']`:
```
#<OmniAuth::AuthHash expires=true expires_at=1496866381 token="<TOKEN OMITTED>">
```

Thinking it might be a weird syntax thing, I've done the keword args to `provider` with and without curly braces, and done the scope as all of

```ruby
scope: 'email profile spreadsheets drive',
scope: 'email, profile, spreadsheets, drive',
scope: 'email', 'profile', 'spreadsheets', 'drive',
scope: ['email', 'profile', 'spreadsheets', 'drive'],
```

with no difference in the results.

I'm sure I must have some mistake here, but I can't for the life of me figure out what it is. Thanks for your attention on this!

**Comment by droberts-ada** [comment]
Ah, I figured it out. I had previously requested online access with this app/account, and for some reason it seems Google had cached that info and was not sending back the refresh token. All I had to do was to go into my Google account settings and reset the permissions for this app.

**Comment by amast09** [comment]
Bless you kind sir for figuring this out. I also ran into the same issue and your solution worked for me as well 👍

**Comment by MatthewRDodds** [comment]
I ran into this as well. The `refresh_token` was received the first time a user linked their account, but not in subsequent times (the application allows unlinking the Google account). The fix for me was to specify `prompt: "select_account consent"` so that the user consented to the permissions each time.
