### ISSUE TITLE
How can i get the location/address from the auth object ?

### ISSUE THREAD

**Issue by mike1011** [zquestz/omniauth-google-oauth2#288]
i am using `oauth2 `for fetching basic information on my Rails 4 app.However finding it hard to get location form Oauth google.

is there is way as the `info `object do not contain the **address** by default.Can i use scope ? if yes then how.

i also tried to go through the api docs here - https://developers.google.com/google-apps/contacts/v3/reference but not sure what to use .

Kindly help.

**Comment by zquestz** [comment]
First you need the address scope. https://www.googleapis.com/auth/user.addresses.read

I don't believe the data comes back through the auth info though. You will need to use the access_token to fetch it from google.

**Comment by mike1011** [comment]
Thanks for the reply @zquestz , how can i use the access token..i tried but was unable to find the address.Can you help in this ?

Thanks in advance.

**Comment by BKSpurgeon** [comment]
Refer to this - it should help for  a very general overview

https://developers.google.com/drive/v3/web/quickstart/ruby

Once you have your access token you need to create a drive object using that access token. something like this.

```
access_token = AccessToken.new 'SECRET_TOKEN'
drive = Google::Apis::DriveV2::DriveService.new
drive.authentication = access_token
drive.list_files # works ( If you get unauthorized error ... refresh the access token )
```
