### ISSUE TITLE
Default scope for devise does not show google consent screen.

### ISSUE THREAD

**Issue by skeletonx** [zquestz/omniauth-google-oauth2#289]
consider the following configuration in config/initializers/devise.rb:

`config.omniauth :google_oauth2, 'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', {}
`
which use the default scope 'email,profile'.
But when I sign up with google, it will bypass the consent screen. I have clear my app credential in google app setting.

screenshot as the following:
![defaultscope](https://user-images.githubusercontent.com/9355437/27749535-908288c0-5d99-11e7-88d7-f34f09baca7d.JPG)

If I add a scope with something different than the default api prefix("https://www.googleapis.com/auth/"), like the following example:
`
config.omniauth :google_oauth2, 'GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', {
   scope: "'email, profile, plus.me, http://gdata.youtube.com'"
}
`
the consent screen will show, login image as the following
![hasscopeparamsinurl](https://user-images.githubusercontent.com/9355437/27749537-92ba6ff4-5d99-11e7-8a58-f8409ed80c1a.JPG)

I check for the url when clicking "sign up with google", there is a parameter "scope%3Demail", which is not in the first case's url.

I am guessing the problem is the request url.

**Comment by skeletonx** [comment]
never mind, I am guess there is something wrong with google,

When I use OAuth 2.0 Playground, "Youtube API" is the only one shows normal consent screen. 
If I combine other API(like email, profile) with Youtube API, it shows every permission.
If I only select (email, profile), it does not show anything.

**Comment by zquestz** [comment]
Yes this was a change on Google's end.
