### ISSUE TITLE
Google Oauth2 in embedded browser (web view) 403 disallowed_useragent

### ISSUE THREAD

**Issue by indermishra** [zquestz/omniauth-google-oauth2#297]
[https://stackoverflow.com/questions/43152411/google-oauth2-in-embedded-browser-web-view](https://stackoverflow.com/questions/43152411/google-oauth2-in-embedded-browser-web-view)

**Comment by zquestz** [comment]
https://stackoverflow.com/questions/40591090/403-error-thats-an-error-error-disallowed-useragent

**Comment by zquestz** [comment]
The link above should help. You just need to report a fake accepted user agent.
