### ISSUE TITLE
redirect_uri_mismatch

### ISSUE THREAD

**Issue by Rubioli** [zquestz/omniauth-google-oauth2#299]
I'm trying to set up `Devise` with *Facebook* & *Google*. I followed [this article](http://willschenk.com/setting-up-devise-with-twitter-and-facebook-and-other-omniauth-schemes-without-email-addresses/) *(without using `happyseed gem` & I've followed this article for setting up Facebook & Twitter and they work fine)*.

When I'm testing google login in my production I get `Error: redirect_uri_mismatch`.

*This is the screenshot of the error:*

![skjermbilde 2017-08-06 kl 15 14 44](https://user-images.githubusercontent.com/16593596/29003599-06896538-7aba-11e7-9dc3-3eb382c3fe15.png)

*This is my gems:*
```
gem 'devise'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'
gem 'google-api-client', '~> 0.7.1'
```

*These are `gem` versions:*
```
Using oauth2 1.1.0
Using omniauth 1.3.1
Using omniauth-oauth2 1.4.0
Using omniauth-facebook 3.0.0
Using omniauth-google-oauth2 0.5.2
```

*In Google Consol I have:*

![skjermbilde 2017-08-06 kl 15 02 54](https://user-images.githubusercontent.com/16593596/29003498-6849e632-7ab8-11e7-9efe-dd58e023e40b.png)

In `devise.rb` I've added the `client_id` & `secret key`:
`config.omniauth :google_oauth2, '479297749641-83hslqnkjekqlejq76wyhafbgc847ahb98samq1.apps.googleusercontent.com', '6QAoshnb8SO8KsIb9a_uh5jKL', scope: "email,profile,offline", prompt: "consent", setup: true`

In my `routes.rb`
```
devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
devise_scope :user do
  get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
  get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
end
```

It's my first time setting up Google Auth. Any help is appreciated.

*PS: I've change client ID and secret key for submitting here. So if they dont match is because I changed them in the images and code. But it does match in my actual code*

**Comment by zquestz** [comment]
Google Console changes can take up to 15 minutes to actually become active. The settings look correct.

**Comment by Rubioli** [comment]
@zquestz Thanks for reply.

I've waited 24hrs now and same error from google. What else I can do?

**Comment by zquestz** [comment]
You can't just run that url in your browser. It must be through the full oauth flow. Otherwise the state variables will not be set correctly and you will see CSRF errors.
