### ISSUE TITLE
hd parameter does not work with wildcard

### ISSUE THREAD

**Issue by vshulman** [zquestz/omniauth-google-oauth2#301]
https://github.com/zquestz/omniauth-google-oauth2/blob/6364a35581d0443c96b82535e02a86f3bf5b8732/lib/omniauth/strategies/google_oauth2.rb#L209

According to the [openID documentation](https://developers.google.com/identity/protocols/OpenIDConnect) `hd=*` is a valid option to only allow G Suite emails, and it does in fact work to limit options in the UI. However on callback `verify_hd` does not seem to recognize it and throws an exception. Perhaps there should be a special case for `options.hd == "*"`?

**Comment by zquestz** [comment]
Yes we should definitely add that. =)

**Comment by zquestz** [comment]
Thank you!
