### ISSUE TITLE
Is it possible to authenticate with different scopes for different users?

### ISSUE THREAD

**Issue by hooverlunch** [zquestz/omniauth-google-oauth2#302]
It seems you can do this with the Facebook Oauth gem: https://github.com/mkdynamic/omniauth-facebook#per-request-options

Is there a way to do it with this one?

If not, can you suggest where I could add this? Would you be open to PRs?

Thanks!

**Comment by zquestz** [comment]
You can do it the exact same way as the Facebook gem. Just add the param `scope` to the auth url.

**Comment by hooverlunch** [comment]
Great! Any hints on how I'd do this when using Devise?

**Comment by zquestz** [comment]
Not sure, the url helpers should allow you to easily add params. Just include:

```
{ scope: "YOUR_CUSTOM_SCOPES" }
```
