### ISSUE TITLE
Hybrid auth from a Chrome Extension

### ISSUE THREAD

**Issue by nburt** [zquestz/omniauth-google-oauth2#304]
I'm attempting to authenticate a user from a Chrome Extension for offline access to the Gmail API and I'm getting the following error:

```
Authentication failure! invalid_credentials: OAuth2::Error, unauthorized_client:
{
  "error" : "unauthorized_client"
}
```
Do you know if this is possible? My thought is that creating different client ids for the extension and rails backend is causing the issue. I've enabled the Contacts API, Google + API, and Gmail API in the console and I'm using the JS code snippet provided in the readme.

If hybrid auth isn't supported from a Chrome Extension, do you have any recommendations on the best path forward?

**Comment by zquestz** [comment]
To be honest I haven't tested running the hybrid code within a Chrome extension. However that was not really the use case this gem was designed for.

**Comment by nburt** [comment]
OK, makes sense. I ended up just going up with the standard auth flow and that worked out. Thanks!

**Comment by wJoenn** [comment]
Sorry for reviving this but I think I may know why this didn't work and how to make it work.

When you declare a middleware in your Rails application you need the `client_id` to be the same as the client_id made with the request that did the initial signin.

So from your web extension you probably signed in the user using your web extension client_id and in your Rails backend you tried to validate the `code` with your API client_id, this would result in the `unauthorized_client` error.

When using Devise what you can do is declare different middlewares for different client_ids by adding a `name` parameter
```ruby
# config/initializers/devise.rb
config.omniauth :google_oauth2, google_android_client_id, name: 'google_oauth2_android'
config.omniauth :google_oauth2, google_ios_client_id, name: 'google_oauth2_ios'

# app/models/user.rb
devise :omniauthable, omniauth_providers: %i[google_oauth2_android google_oauth2_ios]

# app/controllers/omniauth_callbacks_controller.rb
def google_oauth2_android
  # handle auth from android device
end

def google_oauth2_ios
  # handle auth from ios device
end
```

Does this makes sense ?
