### ISSUE TITLE
JWT 2.0

### ISSUE THREAD

**Issue by Alagaesia93** [zquestz/omniauth-google-oauth2#305]
Hi guys,

Jwt 2.0 has come out! [https://github.com/jwt/ruby-jwt](url)

Could you please update your dependencies?

Thank you very much 🥇

**Comment by kiomac** [comment]
👍

**Comment by runephilosof** [comment]
Jwt 2.1 has been released.

**Comment by zquestz** [comment]
We now allow any version > 1.5. Closing.
