### ISSUE TITLE
One-time Code Flow - where is omniauth.state set?

### ISSUE THREAD

**Issue by eddiej** [zquestz/omniauth-google-oauth2#307]
When implementing the one-time code flow as per the example, there doesn't seem to be a value for 'omniauth.state' set in the session (this value is set at https://github.com/intridea/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L58).

This results in a `csrf_detected` error, raised at https://github.com/intridea/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L70 because the session has no value for omniauth.state. Is there a workaround for this (apart from setting `provider_ignores_state` to true which has security issues).

**Comment by mgeyer** [comment]
+1 Having similar issue

**Comment by zquestz** [comment]
This is correct as the omniauth.state is done server side for the server side flow. The only option right now is to use `provider_ignores_state`.
