### ISSUE TITLE
CSRF issue

### ISSUE THREAD

**Issue by pitosalas** [zquestz/omniauth-google-oauth2#308]
Can't say that this is a bug but I am stumped on how to solve it. Maybe posting it hear will bring an idea to someone's mind. I've written a super simple Rails program to verify the problem. It seems that when I attempt to login to my gmail.com account, when I have other google oauth enabled accounts, I get this exception:

OmniAuth::Strategies::OAuth2::CallbackError at /auth/google_oauth2/callback
csrf_detected | CSRF detected

Here are all the relevant code snippets:

```
# initializers/omniauth.rb
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2,
    "redacted",
    "redacted"
end

# routes.rb
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'home', to: 'home#show'
  get 'me', to: 'me#show', as: 'me'

# views/home/show.html.erb
<%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>

# application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def authenticate
    redirect_to :login unless user_signed_in?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    # converts current_user to a boolean by negating the negation
    !current_user.nil?
  end
end

# sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
    session[:user_id] = @user.id
    redirect_to :me
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

```

* I run the server with rails server -p 3000
* I access the page with http://localhost:3000
* This displays the page with the login button, which I press
* This displays a list of all my possible google logins (I think there are 4)
* I click on one of them, and I get the following exception: ```
```
OmniAuth::Strategies::OAuth2::CallbackError at /auth/google_oauth2/callback
csrf_detected | CSRF detected

Stack trace is attached.
![screen shot 2017-10-15 at 10 44 21 am](https://user-images.githubusercontent.com/44681/31585803-ebc8848c-b195-11e7-98aa-31407d7d4a5e.png)

**Comment by yo-gen** [comment]
Me too facing the same issue.

**Comment by zquestz** [comment]
Try including a state parameter in the link to auth, that might address your issue.

**Comment by zquestz** [comment]
You also want to bypass `protect_from_forgery` in the callback. There is built in CSRF protection in the gem.

**Comment by MythosRaconteur** [comment]
Hey all,

This is specific to the use of Google's One-Time Flow (hybrid) authorization.

I too was facing this issue, and nothing I read or tried worked. I kept looking for a CSRF token issue, adding headers, etc.

Turns out, after digging in the gem code a bit, there is a check in the omniauth-oauth2/lib/omniauth/strategies/oauth2.rb (not the Google-specific one) during the `callback_phase` method.

If you are not ignoring state in the omniauth config, then a CSRF gets detected if the passed in state is empty/non-existent or it does not match the session's omniauth.state value.

So, the solution I put in is this:

1) In the Javascript, where you send the token you received from Google back to your server, tack on a `state=XXX` parameter, so the URL ends up looking something like:
`/auth/google_oauth2/callback?state=SOMETHING`

2) In the controller code that presents the view with the "Sign In with Google" button (the `new` method for me), set the session var to the same value (whatever your replaced SOMETHING with):

`session['omniauth.state'] = SOMETHING`

And violá! Much work! So fix!

Hope this helps someone!

**Comment by pitosalas** [comment]
@MythosRaconteur Thanks!! Question - the js sending the token back is part of the gem, isn't it? Do I need to modify this gem?

**Comment by MythosRaconteur** [comment]
When you tack the token onto the OAuth callback (per step 1 in my solution), the gem will take it and compare it to ```session['omniauth.state']``` during the ```callback_phase``` method.

**Comment by pitosalas** [comment]
Sorry @MythosRaconteur I am new and vague on this... Thanks for your help. I thought that when using the gem I don't write any javascript. I believe the gem is providing that so that I can't modify it unless I modify the gem.

**Comment by MythosRaconteur** [comment]
Hi Pito,

No worries, it was a bit confusing to me as well.

Here is how I have it setup:

1. In my session controller (the controller that presents the Login controls), I set the ```session['omniauth.state']``` just before the Login screen appears (this is done in my ```new``` method)

2. I use a gem called Gon to move Ruby/Rails variables to Javascript so that my JS files can get to data from the backend. In my JS file that handles the Google One-Time Flow (look at the One-time Code Flow - Hybrid Authorization section of https://github.com/zquestz/omniauth-google-oauth2), on the line with ```jQuery.ajax({type: 'POST', url: '/auth/google_oauth/callback ... ``` I just made action url look like this: ```url: '/auth/google_oauth/callback??state=' + gon.omniauth_state```

That should do the trick!

**Comment by pitosalas** [comment]
Thanks, so it seems like you do want me to modify the code in the gem and use a locally hacked gem right? In other words the gem as is cannot be made to work?

**Comment by MythosRaconteur** [comment]
No, nothing in what I describe above touches the gem.  This is all your own session controller code, and the JS that you had to write to use the One-Time flow.

**Comment by pitosalas** [comment]
@zquestz I wanted to try your method too. Can you give another level of detail of how I "Try including a state parameter in the link to auth"  and how I "bypass protect_from_forgery in the callback". Which callback? Sorry for the dumb questions @zquestz (and @MythosRaconteur), I am a good rails dev but not up to speed on oauth2 stuff!

**Comment by zquestz** [comment]
Your Sessions controller is inheriting from ApplicationController which has `protect_from_forgery with: :exception`. You can't do the protect_from_forgery on the sessions controller. Subclass from ActionController::Base. Then it should work as expected.

**Comment by MythosRaconteur** [comment]
@zquestz How do you subclass one Devise controller from ActionController while letting others be subclassed from ApplicationController without hacking the gem? Is that possible?

You made me think that perhaps we should move our entire Devise strategy under ActionController, but two things stand in the way:

1) We need the functionality added by our AppController for several things in the Devise system.
2) The Devise default parent controller is AppController, which makes it feel like the wrong choice.

The method I outlined is working for our needs, but I wanted to make sure I am not missing a better, more elegant solution, so any insight/input is greatly appreciated!

**Comment by zquestz** [comment]
In SessionsController add `skip_before_filter :verify_authenticity_token`. This should bypass the protect from forgery hooks in ApplicationController.

**Comment by yo-gen** [comment]
request includes the large request object. Attaching output of request.params.inspect
![google-oauth-bug2](https://user-images.githubusercontent.com/3635878/31927228-c10e499e-b8b0-11e7-8708-334cecbbd373.png)

**Comment by yo-gen** [comment]
As for the JS code being different, I am trying to get this to work using react with redux.

**Comment by zquestz** [comment]
Whats strange is I see code in the payload, but then it says there isn't one...

**Comment by yo-gen** [comment]
Yes, exactly.

https://github.com/zquestz/omniauth-google-oauth2/issues/153

Does this strike any bells?

**Comment by zquestz** [comment]
Yeah but the data looks fine, you can try the monkey patch but I am not sure it will do anything for you.

**Comment by donapieppo** [comment]
temporary solution for me:

`provider :google_oauth2, ENV['GOOGLE_APP_ID'], ENV['GOOGLE_APP_SECRET'], { provider_ignores_state: true }
`
I did not use One-Time flow (no oauth2 javascript in my code) but had the same issue.

**Comment by pitosalas** [comment]
Hi all,

These instructions work for me:
https://richonrails.com/articles/google-authentication-in-ruby-on-rails/


Pito Salas
Brandeis Computer Science
Volen 134

**Comment by donapieppo** [comment]
My application required a logged user for every page.

In `app/controllers/application_controller.rb` had `before_action :force_user` and in `force_user` had a `redirect_to` google oauth2 unless current_user.

To solve the this CSRF problem had to create an unproteced page (with skip_before_action) with a link to google. Clicking the link the authentication works fine.
