### ISSUE TITLE
Omniauth callback working with GET but not with POST

### ISSUE THREAD

**Issue by yo-gen** [zquestz/omniauth-google-oauth2#309]
```es6
$.ajax({
  type: 'POST',
  headers: { 'X-Requested-With': 'XMLHttpRequest' },
  url: 'users/auth/google/callback',
  data: JSON.stringify(response),
  contentType: 'application/json; charset=utf-8',
  dataType: 'json',
}).done((data) => {
  // do something
}).fail((data) => {
  // do something
});
```
This api call throws an error in my server console saying
ERROR -- omniauth: (google) Authentication failure! invalid_credentials: OAuth2::Error, invalid_request: Missing required parameter: code
18:48:57 rails.1      | {
18:48:57 rails.1      |   "error" : "invalid_request",
18:48:57 rails.1      |   "error_description" : "Missing required parameter: code"
18:48:57 rails.1      | }

However with request type GET and removing JSON.stringify for params, it works fine, why?

My routes are defined using the devise helpers

```ruby
  devise_for :users, controllers: { sessions: "sessions", registrations: "registrations",
                                    confirmations: "confirmations", passwords: "passwords",
                                    omniauth_callbacks: "omniauth_callbacks" }
```

and my devise initializer has:

```ruby
  config.omniauth :google_oauth2,
                  Rails.application.config.omniauth[:google_oauth2][:key],
                  Rails.application.config.omniauth[:google_oauth2][:secret],
                  name: "google",
                  scope: 'email,profile',
                  provider_ignores_state: true
```

**Comment by dbarria** [comment]
I have same error. @yo-gen Do you found any solution?

**Comment by zquestz** [comment]
And you can confirm that `code` is being passed in?

**Comment by yo-gen** [comment]
Yes, I can see the code being passed in the parameters logged in console. Attaching a snapshot here.
![bug-google-omniauth](https://user-images.githubusercontent.com/3635878/31926246-099f2cce-b8ab-11e7-9843-25b55caf1bfe.png)

**Comment by zquestz** [comment]
Can you try monkey patching the class as so:

```
module OmniAuth
  module Strategies
    # Main class for Google OAuth2 strategy.
    class GoogleOauth2 < OmniAuth::Strategies::OAuth2
      def get_access_token(request)
        puts "REQUEST INFO #{request.inspect}"
        if request.xhr? && request.params['code']
          verifier = request.params['code']
          redirect_uri = request.params['redirect_uri'] || 'postmessage'
          client.auth_code.get_token(verifier, get_token_options(redirect_uri), deep_symbolize(options.auth_token_params || {}))
        elsif request.params['code'] && request.params['redirect_uri']
          verifier = request.params['code']
          redirect_uri = request.params['redirect_uri']
          client.auth_code.get_token(verifier, get_token_options(redirect_uri), deep_symbolize(options.auth_token_params || {}))
        elsif verify_token(request.params['access_token'])
          ::OAuth2::AccessToken.from_hash(client, request.params.dup)
        else
          verifier = request.params['code']
          client.auth_code.get_token(verifier, get_token_options(callback_url), deep_symbolize(options.auth_token_params))
        end
      end
    end
  end
end
```

**Comment by zquestz** [comment]
Also the example is quite different than your code:

```
<script>
--
  | jQuery(function() {
  | return $.ajax({
  | url: 'https://apis.google.com/js/client:plus.js?onload=gpAsyncInit',
  | dataType: 'script',
  | cache: true
  | });
  | });
  |  
  | window.gpAsyncInit = function() {
  | gapi.auth.authorize({
  | immediate: true,
  | response_type: 'code',
  | cookie_policy: 'single_host_origin',
  | client_id: '170493746857-eoeurctgfjtegl4hvnnvf6ej21iqc66v.apps.googleusercontent.com',
  | scope: 'email profile'
  | }, function(response) {
  | return;
  | });
  | $('.googleplus-login').click(function(e) {
  | e.preventDefault();
  | gapi.auth.authorize({
  | immediate: false,
  | response_type: 'code',
  | cookie_policy: 'single_host_origin',
  | client_id: '170493746857-eoeurctgfjtegl4hvnnvf6ej21iqc66v.apps.googleusercontent.com',
  | scope: 'email profile'
  | }, function(response) {
  | if (response && !response.error) {
  | // google authentication succeed, now post data to server.
  | jQuery.ajax({type: 'POST', url: "/auth/google_oauth2/callback", data: response,
  | success: function(data) {
  | // Log the data returning from google.
  | console.log(data)
  | }
  | });
  | } else {
  | // google authentication failed.
  | console.log("FAILED")
  | }
  | });
  | });
  | };
  | </script>
```

**Comment by yo-gen** [comment]
request includes the large request object. Attaching output of request.params.inspect
![google-oauth-bug2](https://user-images.githubusercontent.com/3635878/31927228-c10e499e-b8b0-11e7-8708-334cecbbd373.png)

**Comment by yo-gen** [comment]
As for the JS code being different, I am trying to get this to work using react with redux.

**Comment by zquestz** [comment]
I see the issue. Remove JSON.stringify.

**Comment by yo-gen** [comment]
Have tried that, it leads to a different error
![google_oauth_bug3](https://user-images.githubusercontent.com/3635878/31931895-3b60fe2e-b8c2-11e7-95dd-fa9c100e61c7.png)

**Comment by yo-gen** [comment]
Also, I just noticed, the monkey patch u gave me is not applied properly. code isn't reaching there. 
The request object I shared above is what I get in my callback controller.
Trying to monkey patch properly, will then share the actual request payload

**Comment by zquestz** [comment]
This is due to ParamsParser choking thinking it is json, which it isn't. Did you remove the content type?

**Comment by yo-gen** [comment]
Removing content_type worked

**Comment by zquestz** [comment]
WOOT!

**Comment by yo-gen** [comment]
Thanks

**Comment by zquestz** [comment]
I am not sure, I would need to look closer. Most likely the updated params handling in Rails 5. Just need to look closer at request.params and see what is going on there.

**Comment by yo-gen** [comment]
Tried a lot, code is not even reaching the method get_access_token. I tried the monkey patch from https://github.com/zquestz/omniauth-google-oauth2/issues/153, there when I inspect parsed_params, it gives me nil.

**Comment by zquestz** [comment]
Not sure, all depends on how Rack is parsing it. I generally use my own Sinatra frameworks these days, so haven't checked on the Rails side in a while. Will make an action item to look into the JSON issue.

**Comment by ajsharp** [comment]
This seems like a bug with this library. My understanding from reading https://github.com/omniauth/omniauth-oauth2/issues/66#issue-48577127 and #153, the issue is that this library expects rails to deliver the params, but rails hasn't had a chance to parse json params yet. Thus, this library should just do some basic checking for a json content type, and if so, read the body from the params like the patch suggested in #66.
