### ISSUE TITLE
Processing of routes with a variable scope

### ISSUE THREAD

**Issue by eduardobarbiero** [zquestz/omniauth-google-oauth2#312]
Hello!

I encountered a problem when implementing the gem, because I use a "dummy path per company", that is, I have a url:

Ex: http://localhost:3000/vetor-saude/auth/google_oauth2

However, gem is not recognizing that "vetor-saude" is my business identifier by route scope.

Is there any way around this problem? being sending a parameter via query or even injecting the same in the callback? I use this identifier to identify which company the user is in.

route:

```ruby
scope ":company_id" do
    resources :auth, path: "autorizar" do
      get :callback, to: 'auth#oauth_create'

      collection do
        get 'failure', to: redirect('/')
      end
    end
end
```

Thanks!

**Comment by zquestz** [comment]
Yes, you can adjust the callback URL by passing `redirect_uri` as a param in the auth link.

**Comment by eduardobarbiero** [comment]
@zquestz thanks answer!

I believe that this is not possible, since google only releases exact urls (taking into account my variable company parameter), is this still viable?

**Comment by eduardobarbiero** [comment]
I using:

http://localhost:3000/auth/google_oauth2?redirect_uri=http://localhost:3000/vetor-saude/auth/google_oauth2/callback

Only worked, when I placed the URL in the URL authorized callback in google console.

**Comment by zquestz** [comment]
Yes, the redirect_uri is the URL google will use to call back into your application. You will need to make sure those are allowed in the Google API however. =\
