### ISSUE TITLE
# character appended to callback URL

### ISSUE THREAD

**Issue by humphreybc** [zquestz/omniauth-google-oauth2#313]
We're using Rails 5.1, Devise 4.3, and omniauth-google-oauth2 0.4.1. After authenticating with Google a # character is appended to the end of the URL. 

In our case, we redirect to /projects after authentication so this looks like `http://localhost:3000/projects#` or `https://dovetailapp.com/projects#` on production. It would be nice to remove this # character.

### config/initializers/devise.rb

```ruby
config.omniauth :google_oauth2, Figaro.env.google_client_id, Figaro.env.google_client_secret, { name: 'google', prompt: 'select_account' }
```

### config/routes.rb

```ruby
devise_for :users, controllers: { confirmations: 'confirmations',
                                  invitations: 'invitations',
                                  omniauth_callbacks: 'omniauth_callbacks',
                                  passwords: 'passwords',
                                  registrations: 'registrations',
                                  sessions: 'sessions' }
```

### app/controllers/omniauth_callbacks_controller.rb

This method handles both creating an account and logging in via Google.

```ruby
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'website'

  def google
    url = request.env['REQUEST_URI']
    params = Rack::Utils.parse_query URI(url).query
    data = request.env['omniauth.auth'].info
    name = data['name']
    email = data['email']

    user = User.find_by(email: email)

    if user.nil?
      user = User.from_omniauth(name, email)
      sign_in_and_redirect user, event: :authentication
      return
    end

    sign_in_and_redirect user, event: :authentication
  end
end
```

**Comment by zquestz** [comment]
So, since the last redirect is handled via `sign_in_and_redirect`, I checked out the docs here: http://www.rubydoc.info/github/plataformatec/devise/Devise/Controllers/Helpers#sign_in_and_redirect-instance_method

Seems this redirects to the location set by `after_sign_in_path_for`, which can be customized to fix the behavior you see. The gem doesn't do anything with anchors in the url.

**Comment by humphreybc** [comment]
@zquestz Thanks for your quick reply! I have tried overriding `after_sign_in_path_for` but didn't get anywhere. The # is there, no matter what I change that to. I've raised an issue with Devise: https://github.com/plataformatec/devise/issues/4716

**Comment by zquestz** [comment]
Since this is just with devise, hopefully they can fix it. Closing. If you need more assistance make sure to reopen this =)
