### ISSUE TITLE
Hybrid authentication flow with `gapi.auth2`

### ISSUE THREAD

**Issue by hbomb79** [zquestz/omniauth-google-oauth2#314]
I'm really struggling to get `gapi.auth.authorize` to work properly, with the intention of getting one-time flow working. Issues include the `/auth/google/callback` erroring with 500:

```
Started POST "/auth/google/callback" for 127.0.0.1 at 2017-12-15 18:56:41 +1300
(google) Callback phase initiated.
(google) Authentication failure! invalid_credentials: OAuth2::Error, invalid_request: Could not determine client ID from request.
{
  "error" : "invalid_request",
  "error_description" : "Could not determine client ID from request."
}
```

As well as issues with the widgets on the webpage (I'm following instructions from Google's developer site, however, your instructions clash with them completely), such as the 'Sign in' widget reading 'Signed in' before starting auth flow.

The [Google documentation](https://developers.google.com/identity/sign-in/web/server-side-flow) suggest a completely different approach (using `auth2` instead of `auth`, and `grantOfflineAccess` instead of `authorize`). Is it possible to use their approach with this gem (and if so, how)? If not, why not?

I don't really know what I'm doing and I'm really struggling to find documentation for the `auth` calls (whereas `auth2` is documented everywhere), so literally, no aspect of the sign in is working anymore.

Help would be appreciated, This might be the wrong place but it feels more appropriate than StackOverflow because I feel like the README is using an outdated version of Google's authentication API (or maybe it isn't? I don't know).

**Comment by zquestz** [comment]
Please look at the sample in the `examples` folder. This has code that is know to work with the `auth` endpoint.
