### ISSUE TITLE
hd=*  error

### ISSUE THREAD

**Issue by johnpearson555** [zquestz/omniauth-google-oauth2#315]
I'm referring to the support added in this PR: https://github.com/zquestz/omniauth-google-oauth2/pull/303

I'm having a issue with using this:

My omniauth.rb file:
`Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, ENV['GOOGLE_CLIENT_ID'], ENV['GOOGLE_CLIENT_SECRET'],
    {
      name: 'google',
      scope: 'email, profile, https://www.googleapis.com/auth/admin.directory.user.readonly, https://www.googleapis.com/auth/admin.directory.orgunit.readonly',
      prompt: 'select_account',
      hd: '*'
    }
end`

The Error:
`web_1  | Started GET "/auth/google/callback?state=f33c55de1633f71dcbbe75783c385c4845218078e868a8db&code=4/8f2XXaUh1qLL8Bq2UH5DHI6PYOIt6OnLegS4gIlkRpI" for 172.20.0.1 at 2018-01-02 01:03:20 +0000
web_1  | Cannot render console from 172.20.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
web_1  | I, [2018-01-02T01:03:20.507798 #7]  INFO -- omniauth: (google) Callback phase initiated.
web_1  | E, [2018-01-02T01:03:21.043494 #7] ERROR -- omniauth: (google) Authentication failure! invalid_credentials: OmniAuth::Strategies::OAuth2::CallbackError, invalid_hd | Invalid Hosted Domain
web_1  |   
web_1  | OmniAuth::Strategies::OAuth2::CallbackError (invalid_hd | Invalid Hosted Domain):
web_1  | omniauth-google-oauth2 (0.5.2) lib/omniauth/strategies/google_oauth2.rb:209:in 'verify_hd'
web_1  | omniauth-google-oauth2 (0.5.2) lib/omniauth/strategies/google_oauth2.rb:97:in 'custom_build_access_token'
web_1  | omniauth-oauth2 (1.5.0) lib/omniauth/strategies/oauth2.rb:73:in callback_phase
`

I added credentials for: Google+ API, Contacts API, Admin SDK. The same G Suite Account works when the hd option is not specified. I want to use hd=* to limit login to G Suite Accounts.

Thanks.

**Comment by retainai** [comment]
Does this work when you explicitly specify the domain to whitelist (e.g. hd: 'corpdomain.com')?

**Comment by vshulman** [comment]
Does it work when you explicitly specify the domain to whitelist, e.g. `hd: 'corpdomain.com'`, rather than using the wildcard?

**Comment by johnpearson555** [comment]
Yes, it works when a specific domain is specified. Though that isn't my use case. I'd like to restrict to only G Suite Accounts.

**Comment by johnpearson555** [comment]
Were you able to reproduce the problem? Or am I doing something wrong? Thanks!

**Comment by retainai** [comment]
I haven't been able to reproduce. One thought: are you sure you're using a version that includes this fix? I don't believe this was included in 0.5.2.

**Comment by vshulman** [comment]
I haven't been able to reproduce. One thought: are you sure you're using a version that includes this fix? I don't believe this was included in 0.5.2.

**Comment by johnpearson555** [comment]
Ah yes, I see 0.5.2 was released on July 30 and your fix was in September. I'll pull from github and report back.

**Comment by johnpearson555** [comment]
That fixed it. Thanks!
