### ISSUE TITLE
Compatibility with cordova googleplus

### ISSUE THREAD

**Issue by mgs96** [zquestz/omniauth-google-oauth2#320]
Hello, I was trying to make this gem work with ionic using [cordova-plugin-googleplus](https://github.com/EddyVerbruggen/cordova-plugin-googleplus) using the hybrid flow but wasn't successful, any clues on how can I achieve this?

**Comment by zquestz** [comment]
Sorry I am not sure how this would be done. From the looks of cordova they aren't designed to work with this strategy and have rolled a complete solution. You should probably ask their devs how to accomplish the flow you need.

**Comment by mgs96** [comment]
I found that the problem was with devise, thank you for answering!
