### ISSUE TITLE
I'm trying to make login with google in PHP everything is done but the issue is getting error 400

### ISSUE THREAD

**Issue by madhukanttiw** [zquestz/omniauth-google-oauth2#324]
The redirect URI in the request, http://127.0.0.1/googlelogin, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs

I have the files on localhost the path is 

http://127.0.0.1/googlelogin/

**Authorized Javascript origin is** 
http://127.0.0.1:8000

**Authorised redirect URIs**

http://127.0.0.1:8000/accounts/google/login/callback/

can anybody help me out with it !

**Comment by zquestz** [comment]
The authorized redirect URI must be `http://127.0.0.1/googlelogin/` if that is where your callback is.
