### ISSUE TITLE
Using omniauth-google-oauth2 0.5.3 with rails 5.1.5, devise 4.4.3

### ISSUE THREAD

**Issue by alexdatsko** [zquestz/omniauth-google-oauth2#325]
I know the problem here is most likely with my code, not your gem, but I have not been able to get further after a week and hoping that someone can spot what I'm doing wrong here, and possibly this will help others down the road.  Having a problem after creating a new user, my devise users are set to confirmable as well, so during the first 'sign up with google' which is successful, I see in the logs the user is created and all of the code executes properly.  However, users on my site must also confirm their email as an extra level of security.  After this, they can log back in using Oauth2, which succeeds, but also "Processing by Users::OmniauthCallbacksController#failure as HTML" shows up in the logs due to this error:
`
E, [2018-04-14T16:33:59.456947 #8233] ERROR -- omniauth: (google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, invalid_grant: Code was already redeemed.

{

  "error" : "invalid_grant",
  "error_description" : "Code was already redeemed."

}
`
I had a CSRF error initially so I included :provider_ignores_state => true in the scope hash.  The odd thing with my code is that the failure is called, the user is redirected to root and gets my error message, but is still logged in correctly and can function within the app.. current_user is set and logged_in passes, etc.  So this creates an interesting security bug in my app.  I believe its just a before_action in ApplicationController that is calling the authentication scheme twice when logging in, but can't seem to recognize what is calling it so far.  

So, I was able to get rid of the CSRF error by changing the scope to add 'provider_ignores_state', but then began receiving the above error.   However, putting the following line in the OmniAuth controller did not seem to help.  Have reviewed my code in depth and tried various methods around this and can't get past it for a week now.  Anyone have any useful insight?

`skip_before_action :authenticate_user!, only: [:google_oauth2]`

(Sorry for formatting, character is not being parsed correctly everywhere..)

DEVISE.RB---------------------
`  config.omniauth :google_oauth2, 
  'XXXXXXXXXXcups.apps.googleusercontent.com', 
  'XXXXXXXXXXXXXXXXXXXXXXXX', 
  { 
    provider_ignores_state: true,
    prompt: 'select_account'
  }`

OMNIAUTHCONTROLLER.RB---------------------
`class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :authenticate_user!, only: [:google_oauth2]
  
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
  
  def failure
    puts "Login from Google Oauth2 failure..." if (DEBUG)
    redirect_to root_path,  notice: "Unable to authenticate to Google Oauth2"
  end
  
end`

APPLICATIONCONTROLLER.RB---------------------

`class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :navbar_helper
  helper_method :current_user, :logged_in?, :using_S3?, :age
  
  #################################################

  def setup      # PUT ALL INITIALIZATIONS/CONFIG STUFF HERE
  end

  #################################################
  
  def logged_in?
    user_signed_in?
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action!"
      redirect_to root_path
    end
  end
  
  def require_admin
    if !current_user.admin
      flash[:danger] = "You must be logged in as an Admin to perform that action!"
      redirect_to root_path
    end
  end
  
  def navbar_helper
    if logged_in?
      if current_user.setting.view_all_users
        @nav_categories = Category.all.limit(11)
      else
        @nav_categories = current_user.categories.all.limit(11)
      end
    end
  end
...
  #########################
  
  protected
    def configure_permitted_parameters
      added_attrs = [:username, :email, :first_name, :middle_name, :last_name, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end

end`

USER.RB---------------------

`  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2],
         authentication_keys: [:login]
...
  after_create :create_settings
  attr_accessor :login

  def create_settings
    Setting.create_settings(self.id)
  end
  
  def self.from_omniauth(access_token)

    data = access_token.info
    user = User.where(email: data['email']).first
      
    # Create user if they do not exist
    unless user
      if data['name'].count(' ')>1  # if there are more than 1 space split into 3 names
        @first_name = data['name'].split.first 
        @middle_name = data['name'].split.second
        @last_name = data['name'].split.third
      else # assume returned 2 names
        @first_name = data['name'].split.first 
        @middle_name = "-"
        @last_name = data['name'].split.second
      end
      @username = @first_name+@middle_name+@last_name
    
      user = User.create(
          first_name: @first_name,
          middle_name: @middle_name,
          last_name: @last_name,
          username: @username.downcase,
          email: data['email'],
          #image: auth.info.image, # assuming the user model has an image
          password: Devise.friendly_token[0,20]
      )
      puts "Created user "+user.first_name+user.middle_name+user.last_name if (DEBUG)
...
      user.save
      puts "Saved new user from Google Oauth2!" if (DEBUG)
      puts "" if (DEBUG)
    end
    user
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end`

**Comment by zquestz** [comment]
Are you still having issues? If so feel free to reopen. Just closing old issues that may not be relevant anymore.
