### ISSUE TITLE
Set multiple scopes for authentication

### ISSUE THREAD

**Issue by dchun** [zquestz/omniauth-google-oauth2#328]
Is there a way to set the scope for initial login/account creation with one scope (i.e. analytics.readonly) and once the user is logged in re-authenticate with another scope (i.e. analytics.edit)?

**Comment by Onumis** [comment]
yes, it's on the README, use option: include_granted_scopes

> include_granted_scopes: If this is provided with the value true, and the authorization request is granted, the authorization will include any previous authorizations granted to this user/application combination for other scopes. See Google's Incremental Authorization for additional details.

https://developers.google.com/accounts/docs/OAuth2WebServer#incrementalAuth

**Comment by Onumis** [comment]
see also https://developers.google.com/api-client-library/ruby/auth/web-app#incrementalAuth
