### ISSUE TITLE
Incorrect "image" urls for users with default avatars

### ISSUE THREAD

**Issue by 4ndv** [zquestz/omniauth-google-oauth2#329]
Link from the raw_info (raw_info.picture, works fine):

```
https://lh5.googleusercontent.com/-S8mTowD280o/AAAAAAAAAAI/AAAAAAAAAAA/AB6qoq0Cr49EzgV8Paw_Zky5cWdkk9dtgA/mo/photo.jpg?sz=50
```

Link from the info (info.image, 404):

```
https://lh5.googleusercontent.com/-S8mTowD280o/AAAAAAAAAAI/AAAAAAAAAAA/AB6qoq0Cr49EzgV8Paw_Zky5cWdkk9dtgA/mo/s75-c/photo.jpg
```

But when i'm changing it like this (stripping `/mo` part from the link), it works fine:

```
https://lh5.googleusercontent.com/-S8mTowD280o/AAAAAAAAAAI/AAAAAAAAAAA/AB6qoq0Cr49EzgV8Paw_Zky5cWdkk9dtgA/s75-c/photo.jpg
``` 

My initializer:

```
provider :google_oauth2, ENV['GOOGLE_CLIENT_ID'], ENV['GOOGLE_CLIENT_SECRET'], {
  image_aspect_ratio: 'square',
  image_size: 75
}
```

**Comment by 4ndv** [comment]
Looks like it's broken only for accounts that doesn't have set avatar and uses google's pregenerated "letter"-avatars. For them, google returns links like blahblah/mo/photo.jpg, but for users with non-default avatar it returns blahblah/photo.jpg

Fixed it for myself using VERY UGLY solution by monkey-patching removal of `/mo/` in image_url:

```ruby
# FIXME: Monitor this issue: https://github.com/zquestz/omniauth-google-oauth2/issues/329

OmniAuth::Strategies::GoogleOauth2.class_eval do
  def image_url
    return nil unless raw_info['picture']

    u = URI.parse(raw_info['picture'].gsub('https:https', 'https').sub('/mo/photo', '/photo')) # Fix 329

    path_index = u.path.to_s.index('/photo.jpg')

    if path_index && image_size_opts_passed?
      u.path.insert(path_index, image_params)
      u.path = u.path.gsub('//', '/')
    end

    u.query = strip_unnecessary_query_parameters(u.query)

    u.to_s
  end
end
```

It seems to not break the autogenerated avatar and doesn't affect users with set avatars at all.

**Comment by zquestz** [comment]
Would love a PR that automates this with tests. I bet others are having a similar issue.

**Comment by chamnap** [comment]
Same issue here...

**Comment by zquestz** [comment]
Images are no longer supported now that G+ support has been removed.
