### ISSUE TITLE
OAuth State is not passed back when auth is mocked

### ISSUE THREAD

**Issue by NickTaylor-** [zquestz/omniauth-google-oauth2#333]
When performing a mocked authentication using `OmniAuth.config.mock_auth` to `/auth/google_oauth2?state=MY_STATE` this state is not passed back when redirected to `/auth/google_oauth2/callaback` as `/auth/google_oauth2/callaback?state=MY_STATE` . 

Based on some cursory investigation into the both the google-oauth2 and omniauth code, I am unsure if it is possible to implement this, but hopefully someone else has an idea.

**Comment by zquestz** [comment]
This seems like an OmniAuth concern. Not something specific to this gem.
