### ISSUE TITLE
force all authentication to provider (Google)

### ISSUE THREAD

**Issue by trepidity** [zquestz/omniauth-google-oauth2#334]
I want all users to be forced to use Google, no long username/password. When I add `before_action :authenticate_user!` on a controller, a user is redirected to a local login page, instead of the Google Consent screen.

Is there something I can change to control this?

In my devise.rb I have `config.omniauth :google_oauth2,....`

**Comment by zquestz** [comment]
You would need to create your own helper that forwards to your local auth route for google. It defaults to `/auth/google_oauth2` but for devise might be slightly different.

Basically your helper would:
- Check if the user is logged in
- If logged in allow
- If not logged in then forward to the google_oauth2 endpoint in your app.

Hope this helps.
