### ISSUE TITLE
Could not find a valid mapping for path "/auth/google_oauth2/callback"

### ISSUE THREAD

**Issue by ahe** [zquestz/omniauth-google-oauth2#335]
Hi guys,

I have implemented omniauth-google-oauth2 with devise in a Rails 5 project and everything is working perfectly.

Well, almost perfectly. From time to time I get this exception : Could not find a valid mapping for path "/auth/google_oauth2/callback"

It seems to happen randomly. I already got it once with my Google account. And sometimes it happens to my clients. But most of the time it's working perfectly.

Do you have any idea of what could be the issue here?

Thanks!

-------------------------------
Request:
-------------------------------

  * URL        : https://www.myproject.io/auth/google_oauth2/callback?state=XXX&code=XXX
  * HTTP Method: GET
  * Parameters : {"state"=>"XXX", "code"=>"XXX"}
  * Timestamp  : 2018-08-21 21:57:15 +0200
  * Server : 5bba2d23-d69d-48c8-86b6-3ccb5f74813d
  * Rails root : /app
  * Process: 4

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: {"session_id"=>"XXX",
   "_csrf_token"=>"XXX",
   "warden.user.user.key"=>[[41], "XXX"]}

-------------------------------
Environment:
-------------------------------

  * GATEWAY_INTERFACE                              : CGI/1.2
  * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, br
  * HTTP_ACCEPT_LANGUAGE                           : fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,pt;q=0.6
  * HTTP_CONNECTION                                : close
  * HTTP_CONNECT_TIME                              : 1
  * HTTP_COOKIE                                    : _ga=GA1.XXX; _gid=GA1.2.232716263.1534881268; _fstudio_session=XXX
  * HTTP_DNT                                       : 1
  * HTTP_HOST                                      : www.myproject.io
  * HTTP_REFERER                                   : https://accounts.google.com/signin/oauth/consent?authuser=1&part=XXX&hl=fr&as=XXX
  * HTTP_TOTAL_ROUTE_TIME                          : 0
  * HTTP_UPGRADE_INSECURE_REQUESTS                 : 1
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Linux; Android 6.0.1; STARADDICT 6 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36
  * HTTP_VERSION                                   : HTTP/1.1
  * HTTP_VIA                                       : 1.1 vegur
  * HTTP_X_FORWARDED_FOR                           : 109.62.69.49
  * HTTP_X_FORWARDED_PORT                          : 443
  * HTTP_X_FORWARDED_PROTO                         : https
  * HTTP_X_REQUEST_ID                              : 0aebb2b5-2433-42c5-87dd-3f7ece2dc472
  * HTTP_X_REQUEST_START                           : 1534881434997
  * ORIGINAL_FULLPATH                              : /auth/google_oauth2/callback?state=XXX&code=XXX
  * ORIGINAL_SCRIPT_NAME                           : 
  * PATH_INFO                                      : /auth/google_oauth2/callback
  * QUERY_STRING                                   : state=XXX&code=XXX
  * REMOTE_ADDR                                    : 10.8.0.31
  * REQUEST_METHOD                                 : GET
  * REQUEST_PATH                                   : /auth/google_oauth2/callback
  * REQUEST_URI                                    : /auth/google_oauth2/callback?state=XXX&code=XXX
  * ROUTES_43316520_SCRIPT_NAME                    : 
  * SCRIPT_NAME                                    : 
  * SERVER_NAME                                    : www.myproject.io
  * SERVER_PORT                                    : 443
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : puma 3.11.3 Love Song
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x00007fb9940091f0>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x00007fb98e291f18>
  * action_dispatch.cookies_digest                 : 
  * action_dispatch.cookies_serializer             : json
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x0000000004c43d68>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x0000000005267618>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 109.62.69.49
  * action_dispatch.request.content_type           : 
  * action_dispatch.request.parameters             : {"state"=>"XXX", "code"=>"XXX"}
  * action_dispatch.request.path_parameters        : {}
  * action_dispatch.request.query_parameters       : {"state"=>"XXX", "code"=>"XXX"}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"XXX", "_csrf_token"=>"XXX", "warden.user.user.key"=>[[41], "XXX"]}
  * action_dispatch.request_id                     : 0aebb2b5-2433-42c5-87dd-3f7ece2dc472
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x000000000529ea50>
  * action_dispatch.secret_key_base                : XXX
  * action_dispatch.secret_token                   : 
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * omniauth.error                                 : OmniAuth::Strategies::OAuth2::CallbackError
  * omniauth.error.strategy                        : #<OmniAuth::Strategies::GoogleOauth2:0x00007fb9908e0430>
  * omniauth.error.type                            : csrf_detected
  * omniauth.origin                                : 
  * omniauth.params                                : {}
  * omniauth.strategy                              : #<OmniAuth::Strategies::GoogleOauth2:0x00007fb9908e0430>
  * puma.config                                    : #<Puma::Configuration:0x000000000804f170>
  * puma.socket                                    : #<TCPSocket:0x00007fb9908e3518>
  * rack.after_reply                               : []
  * rack.errors                                    : #<IO:0x0000000000e9da40>
  * rack.hijack                                    : #<Puma::Client:0x00007fb9908e34f0>
  * rack.hijack?                                   : true
  * rack.input                                     : #<Puma::NullIO:0x0000000008015bc8>
  * rack.multiprocess                              : false
  * rack.multithread                               : true
  * rack.request.cookie_hash                       : {"_ga"=>"GA1.XXX", "_gid"=>"GA1.2.232716263.1534881268", "_myproject_session"=>"XXX
  * rack.request.cookie_string                     : _ga=GA1.XXX; _gid=GA1.2.232716263.1534881268; _myproject_session=XXX
  * rack.request.query_hash                        : {"state"=>"XXX", "code"=>"XXX"}
  * rack.request.query_string                      : state=XXX&code=XXX
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x00007fb9908e0840>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x00007fb9908e07f0>
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 3]
  * warden                                         : Warden::Proxy:70217485452200 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x000000000506d088>}

**Comment by zquestz** [comment]
I have not seen this issue. What does your routes file look like?

**Comment by ahe** [comment]
Hi, thank you for your answer.

My routes : 
`devise_for :users, :controllers => { :registrations => :registrations, omniauth_callbacks: 'omniauth_callbacks' }
  devise_scope :user do
    get 'auth/google_oauth2/callback', to: 'omniauth_callbacks#google_oauth2'
  end`

But it's working 90% of the time.  That's why I don't understand this issue.

Thank you!

**Comment by BKSpurgeon** [comment]
- What APIs are enabled, and what APIs are being accessed when that particular error occurs?

**Comment by ahe** [comment]
Calendar + Gmail send access :

{ scope: ['email', 'https://www.googleapis.com/auth/gmail.send', 'https://www.googleapis.com/auth/calendar'], access_type: 'offline', callback_path: '/auth/google_oauth2/callback'}

API enabled : Google Calendar, Google+ and Gmail

Thanks!

**Comment by BKSpurgeon** [comment]
**Where the exception is being raised?**

This is where the exception seems to be raised: https://github.com/plataformatec/devise/blob/3b0bc08ec67dd073ddd6d043c71646c2784ced6c/lib/devise/mapping.rb#L49

```ruby
def self.find_by_path!(path, path_type=:fullpath)
      Devise.mappings.each_value { |m| return m if path.include?(m.send(path_type)) }
      raise "Could not find a valid mapping for path #{path.inspect}"
end
```

**Why is it being raised?**

I suspect: either you are accessing an API which you haven't enabled, or the credentials are invalid; when that happen devise will [try to find mappings based on paths because routes will be skipped](https://github.com/plataformatec/devise/issues/2004#issuecomment-7466322). See that link for potential a potential solution - add the on failure call back manually.

**Also consider whether this is necessary?**

```ruby
#this shouldn't be necessary and can probably be safely removed - check your routes to see if it is:
devise_scope :user do
   get 'auth/google_oauth2/callback', to: 'omniauth_callbacks#google_oauth2'
end
```

**Comment by zquestz** [comment]
@BKSpurgeon's answer was quite thorough. If you continue to have issues feel free to reopen.

**Comment by jivKrishna** [comment]
Hey can anyone resolve my problem?
The problem is that I want to authenticate two types of user "Admin" and "Viewer".
so, I have created two separate actions in SessionsController like:

class SessionsController < ApplicationController
  def create_admin
    auth = request.env["omniauth.auth"]
    p auth
    #session[:omniauth] = auth.except("extra")
    user = Admin.find_by(provider: auth["provider"], uid: auth["uid"])
    unless user
      user = Admin.create(
        name: auth["info"]["name"],
        email: auth["info"]["email"],
        image: auth["info"]["image"],
        provider: auth["provider"],
        uid: auth["uid"]
      )
    end
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed In as Admin!"
  end

  def create_viewer
    auth = request.env["omniauth.auth"]
    p auth
    session[:omniauth] = auth.except("extra")
    user = Viewer.find_by(provider: auth["provider"], uid: auth["uid"])
    unless user
      user = Viewer.create(
        name: auth["info"]["name"],
        email: auth["info"]["email"],
        image: auth["info"]["image"],
        provider: auth["provider"],
        uid: auth["uid"]
      )
    end
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed In Viewer!"
  end

  def destroy 
    session[:user_id] = nil
    session[:omniauth] = nil
    redirect_to root_url, notice: "Signed Out!"
  end
end

and I have created routes like:

Rails.application.routes.draw do
  get "auth/:provider/callback", to: "sessions#create_admin"
  get "auth/:provider/callback", to: "sessions#create_viewer"
  delete "sign_out", to: "sessions#destroy", as: "sign_out"
end

but during admin login or viewer login, I only redirect to "admin" login,
please someone help me to resolve my problem...

**Comment by zquestz** [comment]
Yeah you can't list the same route for the callbacks. This will always go to the admin screen as you have seen. You  will need to have just 1 callback method. To figure out if it is an admin or viewer, you can set the `state` param on the login request. You can set it to something like `admin_RAND_NUM`, and parse the state in your callback, and initialize the correct type of user. You want to include the random number so the state variable can't be predicted.
