### ISSUE TITLE
Should be able to retry access to accounts.google.com

### ISSUE THREAD

**Issue by richdrich** [zquestz/omniauth-google-oauth2#337]
We occasionally see a read timeout on the OpenIDConnect endpoint (https://developers.google.com/identity/protocols/OpenIDConnect)
(from an AWS box, btw).

It would be nice if we could configure a retry counter on this so that the user can log in normally.

**Comment by zquestz** [comment]
Interesting. Feel free to send us a PR for adding retries. I have no problem with that. Maybe limit it to just 3 instead of adding additional configuration options?

**Comment by jcutrell** [comment]
Perhaps this is the same issue we are having that ends up being an `invalid_credentials` message?

**Comment by zquestz** [comment]
We have updated to new endpoints. This should not be required. If so we can reopen the issue.
