### ISSUE TITLE
omniauth-google-oauth2 for Multi tenant application

### ISSUE THREAD

**Issue by vipulvkp** [zquestz/omniauth-google-oauth2#338]
I have a multitenant rails application. i.e. customer1.mydomain.com and customer2.mydomain.com both hit the same piece of code in the same server.

Now , i have to allow all my users for both the tenants to single sign on with google and omniauth-google-oauth2 has been working perfectly till the application was single tenant.

Now for requests for different tenants are received for sso , I need to initialize the middleware everytime with the specific tenant's id and secret. which is not possible as omniauth:builder is loaded as middleware in config/initializers that runs only once when the server starts.

Is there any way not to use omniauth-google-oauth2 as middleware but instead load it with different configurations based on the incoming request.

Please suggest the way forward.

**Comment by zquestz** [comment]
I don't believe there is a way to do this. Might be a better question for the omniauth developers, as this affects all providers.
