### ISSUE TITLE
Dash or underscore?

### ISSUE THREAD

**Issue by monkeysuffrage** [zquestz/omniauth-google-oauth2#339]
In my routes I see:

> user_google_oauth2_omniauth_authorize GET|POST /users/auth/google-oauth2(.:format)  
> user_google_oauth2_omniauth_callback GET|POST /users/auth/google-oauth2/callback(.:format)

But when I go to:
> http://localhost:3000/users/auth/google-oauth2 (with dash)
I get:
> Not found. Authentication passthru.

When I go to:
> http://localhost:3000/users/auth/google_oauth2 (with underscore)
it works but I have issues with the callback:
> ActionController::RoutingError (No route matches [GET] "/users/auth/google_oauth2/callback"):

Can someone help me resolve this please?

**Comment by BKSpurgeon** [comment]
Please paste your `routes.rb` file.

**Comment by zquestz** [comment]
Definitely is underscore, but seems you didn't register the callback routes.

**Comment by monkeysuffrage** [comment]
Ok I tracked it down to omniauth_providers in my users model (needs to be google_oauth2 and not google-oauth2). Some places it's a dash and some places it's an underscore which is a bit confusing.
