### ISSUE TITLE
Google+ gets shutdown on August 2019

### ISSUE THREAD

**Issue by MrGeneration** [zquestz/omniauth-google-oauth2#340]
Hey,

first of all: Thanks for this gem!
When I had to integrate authentication with google over at Zammad, I discovered it needs Google+ API-Services. That's okay by me, but Google+ gets shut down at August 2019 next year.

I know that's some time ahead - but better too early than too late.. :)
Are there plans on migrating already / alternatives at the moment?

Sorry if this is too much of a question or unwanted. :)

Best regards

**Comment by cswilliams** [comment]
Also curious about this issue. We just received a notification from Google today they they are shutting it down on March 7.

**Comment by joe1chen** [comment]
These lines will have to be removed/replaced since they make calls to the plus api's.  The user's image can be retrieved by adding the scope `picture` to the initial authentication request. 

I don't have time to test it out at the moment but I'll submit a pull request when I get a chance to.

```
      def raw_info
        @raw_info ||= access_token.get('https://www.googleapis.com/plus/v1/people/me/openIdConnect').parsed
      end

      def raw_friend_info(id)
        @raw_friend_info ||= access_token.get("https://www.googleapis.com/plus/v1/people/#{id}/people/visible").parsed
      end

      def raw_image_info(id)
        @raw_image_info ||= access_token.get("https://www.googleapis.com/plus/v1/people/#{id}?fields=image").parsed
      end
```

**Comment by palasha** [comment]
I *think* we can replace the url in `raw_info` with `https://www.googleapis.com/oauth2/v2/userinfo` and it should work. The response format appears almost identical.

Not sure about the friend and image stuff, those might not be possible anymore at all.

**Comment by gingerlime** [comment]
Just got an email from Google that it might start to break even sooner

> On March 7, 2019, all Google+ APIs and Google+ Sign-in will be shut down completely. This will be a progressive shutdown beginning in late January, with calls to these APIs starting to intermittently fail as early as January 28, 2019.

**Comment by abrom** [comment]
I've had success replacing the `raw_info` URL with: https://www.googleapis.com/oauth2/v3/userinfo

source: https://developers.google.com/identity/protocols/OpenIDConnect#discovery

I'm not sure if there is an equivalent path for the image? The `userinfo` endpoint does return the users `picture`. Should this be deprecated/removed?

It would seem that the `raw_friend_info` would no longer be valid (given no more G+) and likely should be deprecated/removed

**Comment by jacferreira** [comment]
+1

**Comment by zquestz** [comment]
Merged changes to remove G+ dep.

**Comment by benoittgt** [comment]
It is never too late to do the change...

**Comment by zquestz** [comment]
Already happened...
