### ISSUE TITLE
Debugging the "invalid_credentials" message

### ISSUE THREAD

**Issue by frederickdubois** [zquestz/omniauth-google-oauth2#341]
I get redirected to the "/auth/failure?message=invalid_credentials"

I read other issues and found out this is usually due to APIs not being enabled so I double checked that all needed APIs are indeed enabled in my account... 

I cut the requested scopes to bare minimum (email and profile) and still am getting this error. 

My client id and secret are already double-checked also... 

Is it somewhat possible to get a more precise error? Any debugging mode?

**Comment by jcutrell** [comment]
We're facing this issue as well. No clue what is happening here, but has been picking up more over the last 6 months, so perhaps this is actually a Google issue.

**Comment by jcutrell** [comment]
It's possible this is related to an update to the authorization URLs - see https://github.com/googleapis/google-auth-library-ruby/issues/155 and https://forums.servicestack.net/t/google-oauth-suddenly-failing-with-bad-request-400/6338

**Comment by zquestz** [comment]
Updated the auth urls in 0.5.4, this should be resolved.

**Comment by JeetDesai** [comment]
Best solution i found so far by trying(for around 10h) all possible solutions mentioned in different community platform is 

https://www.semicolonworld.com/question/74575/google-plus-api-shutdown-today-which-alternative-can-be-used-to-authentication
