### ISSUE TITLE
not working in incognito window?

### ISSUE THREAD

**Issue by sanjaygir** [zquestz/omniauth-google-oauth2#342]
So i followed the integration steps as described in this github page. 

The problem is that it works right in normal browsing. But, When i open the app in incognito mode then first time i signin when i use an account that has already been created in the app then it gives "Email has already been taken". Now when i click signin with google button again then it should give account selection window but it again gives "Email has already been taken". In other words after first fail the "signin with google"button becomes stuck with this error. It cannot progress. Is there a fix to this issue? It works as expected in normal browsing but it gives this error only in incognito window. I hope to hear your reply. Thanks!

`
<%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %>`

**Comment by zquestz** [comment]
No idea why this is failing, but we never throw an Email has already taken error so this must exist somewhere in your app logic. Feel free to post more details and reopen the issue.
