### ISSUE TITLE
Google+ API deprecation

### ISSUE THREAD

**Issue by crazyshot** [zquestz/omniauth-google-oauth2#347]
Current integration with omniauth-google-oauth2 requires Google+ API, but it's being deprecated and is going to be shut down within this month
https://developers.google.com/+/api-shutdown

Will this Gem be updated to work without Google+ API?

**Comment by zaclac** [comment]
Howdy! Issue #340 may provide the information you need.

**Comment by crazyshot** [comment]
Heh, I relied on the new "related issues" that didn't show that issue.

**Comment by crazyshot** [comment]
Oh, found issue. I had dependency conflict with jwt-2 in my Gemfile.lock that prevented bundler to update to v0.6. All works now, thanks!
