### ISSUE TITLE
Deprecating G+ without JWT 2.0 dependency?

### ISSUE THREAD

**Issue by ritec** [zquestz/omniauth-google-oauth2#349]
Hello There! 
I am attempting to update this gem to a version that does not depend on G+ since it is being deprecated as we all know. However, I am running into an issue in our application because it seems the only version that currently deprecates G+ also depends on `JWT 2.0` . This JWT 2.0 dependency is causing some issues with other internal gems that depend on `JWT ~> 1.5`. 

Is our only option updating all our gems that depend on JWT 1.0 to use JWT 2.0 as well in order to bypass this dependency clash? It's a bit of heavy lifting on our end so just checking before I exhaust all other options.

Any help or advice would be greatly appreciated.

**Comment by zquestz** [comment]
This is a good point. I think all users should be updating to JWT 2.0 and I would ask any gem authors using the old versions to update their code to support JWT 2.0. There are key improvements in there that are required for this gem to work well given the ISS value can return different values, and only the JWT 2.0 gem actually allows you to set an array for this value.

The best plan of action is to be proactive and get people to start updating their dependencies now before G+ is shut off. I currently have no plans to provide a new version using the old JWT release.

**Comment by ritec** [comment]
Thank you for your answer @zquestz. We will get to work then!
