### ISSUE TITLE
Dynamic providers error, client_id not found

### ISSUE THREAD

**Issue by Ivangrx** [zquestz/omniauth-google-oauth2#35]
Hi, 
Currently I'm working with dynamic providers (https://github.com/intridea/omniauth/wiki/Dynamic-Providers), but google keeps saying:

Error: invalid_request
Missing required parameter: client_id

This is my omniauth.rb:

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :facebook, :setup => true
  provider :twitter,:setup => true
  provider :linkedin,:setup => true
  provider :foursquare, :setup => true
  provider  :google_oauth2, :setup => true
end

This is my setup method:

  def setup_google
    request.env['omniauth.strategy'].options[:client_id] = @site.google_client_id
    request.env['omniauth.strategy'].options[:client_secret] = @site.google_client_secret

```
render :text => "Setup complete.", :status => 404
```

  end

I made it work with facebook, twitter, linkedin and foursquare. It not seems to be a routes problem, I done it right for all the others strategies,  but with google keeps failing.

What am I missing? any clue o this?

Thanks in advance.

**Comment by shantilal-narola** [comment]
@Ivangrx Any luck? I'm facing similar issue with google. Seems like my method doesn't get called
