### ISSUE TITLE
Any way to identify Google+ vs Google sign in from omniauth.auth hash?

### ISSUE THREAD

**Issue by AbhishekChauhanTriangle** [zquestz/omniauth-google-oauth2#351]
Hi Team, 

First of all, Thank you guys for providing this gem, that is awesome of you guys. I have upgraded to omniauth-google-oauth2 - 0.6.0 for preventing Google+ login. I was curious about -- is there any way we can check from request.env["omniauth.auth"] omniauth hash whether Google+ authentication or Google Authentication was done? 

Because i still see in :url field - "https://plus.google.com/__________________".

**Comment by zquestz** [comment]
It never uses G+ anymore. The gem no longer requires those scopes. If you are seeing anything G+ related it is probably due to caching of a previous login attempt.
