### ISSUE TITLE
Is there a way to safely update state?

### ISSUE THREAD

**Issue by Arepo** [zquestz/omniauth-google-oauth2#352]
I've read somewhere that I can affect the oauth state param by adding it as a param to the path helper, eg `user_google_oauth2_omniauth_authorize_path(state: 'registering')` - and this superficially does seem to have the desired effect: I get back the `"state"=>"registering"` param.

But I'm not sure about the security implications of this - from what I gather from reading the [specs](https://auth0.com/docs/protocols/oauth2/redirect-users), state's primary use is to pass around a nonce to ensure the request from the oauth service is legitimate, and rather than overwriting the value, the specs direct you to make the value a key whose values are whatever values you wanted to use (ie. in this case, 'registering').

So I can make the app do what I want it to, but am I opening up a big security hole by doing so, and if so is there a safe way to achieve the same effect? (Either way, it seems worth making explicit in the ReadMe)

**Comment by zquestz** [comment]
You should always use a unique state value per request. Otherwise it can be replayed and it doesn't provide any security. You can simply leave out the state in the link and it should do the right thing.
