### ISSUE TITLE
G+ `plus.me` rspec is still exists

### ISSUE THREAD

**Issue by chendanjie** [zquestz/omniauth-google-oauth2#354]
Hey,
first of all: Thanks for this gem!

↓、plus.me`s rspec is still exists、so I wanne know is there reason to leave ↓ testing code
https://github.com/zquestz/omniauth-google-oauth2/blob/a6274326248cd433654fedee21541a06b095beb2/spec/omniauth/strategies/google_oauth2_spec.rb#L180

Best regards

**Comment by zquestz** [comment]
Nope we can remove it. =)

**Comment by TrishaPatel** [comment]
Hi

Is it removed or it is still there?
Because from today google is shutting down this functionality.
And I am not able to do login in my website using google.

**Comment by zquestz** [comment]
Removed.
