### ISSUE TITLE
Migrate from Google+ to Google Sign-In

### ISSUE THREAD

**Issue by VishalTaj** [zquestz/omniauth-google-oauth2#355]
As we all know google plus sign in been deprecated and i believe this gem only support google plus sign-in method at the moment (correct me if i'm wrong) so is there any way i can use this gem for google sign-in also.

References:

[migrate from google plus sign in](https://developers.google.com/identity/sign-in/web/quick-migration-guide)

**Comment by Jory-Jaguar** [comment]
Hey! This was mentioned in issue #340 
and I believe it was fixed here: e3cbdc5

**Comment by VishalTaj** [comment]
> Hey! This was mentioned in issue #340
> and I believe it was fixed here: [e3cbdc5](https://github.com/zquestz/omniauth-google-oauth2/commit/e3cbdc512a020249e201300df01ed4ddde78d176)

Thanks @Jory-Jaguar, appreciate it.

**Comment by zquestz** [comment]
Yep this has been fixed!
