### ISSUE TITLE
Weird Issue on Chrome and Only Android

### ISSUE THREAD

**Issue by jimishjoban** [zquestz/omniauth-google-oauth2#356]
So we have been using this Gem from quite some time in production... Suddenly in last few days, We started getting complaints of Google Login not working...

We were trying to debug and then realized the issue only happens on Chrome + Android devices.

For same Google accounts on Desktop (Chrome) or iPhone (Safari), works fine....

After doing some research, Here's what we found:

**Callback url when login happening via Chrome + Android:**

/auth/google_oauth2/callback?state=14ff350ca41a60d5bb64c81abdf09d494cc5bdc1004051a9&code=xyz&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile

**Callback URL when login happening via Desktop + Chrome:**

/auth/google_oauth2/callback?state=2144385a58fe1ecc7f84cbf6fcb92f2a763bb0d8a6d8fafa&code=xyz&scope=email+profile+https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.profile

(I have masked code to make it easier to read)

The chrome Android one gets redirected eventually to:

/auth/failure?message=csrf_detected&strategy=google_oauth2

Sorry am still trying to find out what exactly have gone wrong with just Chrome + Android

And i can confirm this issue came up on 2 websites.. so its nothing related to implementation on our side, i assume...

omniauth-google-oauth2-0.2.6
Ruby 2.2.3
Rails 4.1.2 and 4.2.1 (2 apps)

**Comment by jimishjoban** [comment]
Something more which we could find out:

1) It works fine on Incognito Android Chrome.
2) It works fine on Chrome with Only one Google login option on Google Auth screen... 

So issue is only when multiple email options are already available on Google Login screen

The /auth/google_oauth2/callback url is getting hit twice by Google on Chrome android (multiple login options) which in turn is triggering csrf_detected ...

Any suggestions or workaround as seems Gem is doing the right things

**Comment by jimishjoban** [comment]
@zquestz - Are you guys facing issues too with Chrome android? Not sure if Google have internally changed something.. but /callback is getting hit twice in almost quick succession.

**Comment by zquestz** [comment]
Seems like a bug on their end. We should probably raise an issue on their github. We don't control how the callbacks work obviously =)

**Comment by zquestz** [comment]
Could be because we are specifying the scope twice, perhaps we should try it with only the scope passed in once?

**Comment by jimishjoban** [comment]
I currently did a quick fix by redirecting /auth/failure to our home page... since first request anyways logs in user... am just making 2nd request more like no-op

Let me try to remove duplicate scope in a fork and try that tomm...

thanks for the reply.

**Comment by zquestz** [comment]
Going to close this. Thanks for the report. Seems the bug is on the google side when the callback is fired. Not much we can do on this end.
