### ISSUE TITLE
img_url is broken

### ISSUE THREAD

**Issue by kuncha20** [zquestz/omniauth-google-oauth2#359]
Some of the img_url's being returned give 404 error. example, `https://lh5.googleusercontent.com/-jRbSSv1i5u4/AAAAAAAAAAI/AAAAAAAADa4/xjWv4J3ywnk/s50/s50-c/photo.jpg`. The pattern I could find is any url which has `/s50-c` appended after `/s50` appears to be broken. Fetching the img_url from omniauth_hash's info["image"] field.

**Comment by 4ndv** [comment]
Maybe related to #329, try to remove "/s50/" from the url

**Comment by kuncha20** [comment]
Looks like its the same issue as #329 , Never realised this was a previously existing issue, is there any way to fix this issue from the gem side and not monkey-patching it.

**Comment by karthickbabuos** [comment]
Image URl construction on image_params method is causing the problem. Can be resolved through strategy.

**Comment by zquestz** [comment]
Would definitely love a PR to fix this if possible.
