### ISSUE TITLE
Returning unverified email address by default can be risky

### ISSUE THREAD

**Issue by davidtaylorhq** [zquestz/omniauth-google-oauth2#362]
Omniauth does not officially specify whether an email address should be verified. However, it has become the norm for `info.email` to be verified. The recent 0.6.1 release of omniauth-google-oauth2 (a **patch** release) deliberately changes this behaviour, making the gem 'insecure by default'. This could have severe security implications for applications.

We use the gem at [Discourse](https://github.com/discourse/discourse), and if we had updated without checking checking the commits & changelog then it could have caused a serious security vulnerability.

There used to be a [similar problem with the omniauth-github gem](https://github.com/omniauth/omniauth-github/issues/36), but this has now been resolved.

Some other notable omniauth gems:

- omniauth-github will return `nil` for unverified emails [(ref)](https://github.com/omniauth/omniauth-github/commit/341254478d6f8c5439b49f1d14006cc8ae50befa)

- omniauth-twitter will not supply unverified emails [(ref)](https://developer.twitter.com/en/docs/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials)

- omniauth-facebook will not supply unverified emails [(unofficial ref, but verified by numerous parties)](https://stackoverflow.com/questions/14280535/is-it-possible-to-check-if-an-email-is-confirmed-on-facebook)

I think the recent change should be reverted, so that the gem remains 'secure by default'. If applications need access to unverified emails, they can access them using raw_info['email'].

**Comment by zquestz** [comment]
This was due to bugs where google was not returning email_verified in the response. This made it so you had no idea if it was verified or not, and caused issues for a number of apps.

I agree that we should be returning verified emails, but without a solid way to know if it was verified due to bugs upstream we changed the behavior...

So our options are:
- Only return an email when it is verified, and if Google doesn't return that flag due to a bug then never return an email at all... 
- Return both the email and verified bool, and let the app decide if that email should be allowed.

I agree that secure by default is a good ideal, unless that means YOU NEVER GET AN EMAIL, since Google was not being reliable.

**Comment by davidtaylorhq** [comment]
For our use case, either of those two options would be fine. It is critical that we do not trust unverified emails. In general, I prefer the second option - it gives apps the power to decide how they want to handle the situation.

**Comment by zquestz** [comment]
The second option is how it is implemented right now. So you are voting no change?

**Comment by davidtaylorhq** [comment]
Ah, my apologies, I should have read it more carefully.

I think the best solution would be to return two variables: `email` and `email_unverified`. Both would be email strings, not Booleans. `email` would only be populated when verified.

That way apps can make the choice for themselves, and existing apps remain "safe by default"

**Comment by zquestz** [comment]
This is a reasonable suggestion. I would be open to a PR for this. =)

**Comment by zquestz** [comment]
Fix has merged.

**Comment by gingerlime** [comment]
Sorry to jump in here, but I'm looking at upgrading our gem and was wondering when/how can Google provide an *unverified* email? I thought (perhaps naively?) that if you have a Google/Gmail account, then the email on that account was always valid... 

Beyond unit testing, I'd be curious to understand how to simulate this condition, or to estimate how common it might be for us to get unverified emails from Google.

**Comment by davidtaylorhq** [comment]
I think you are probably correct. The google signup flow does seem to require email verification before you can login to an account. However, the [google identity platform documentation](https://developers.google.com/identity/protocols/OpenIDConnect#obtainuserinfo) provides no guarantees of that behaviour, so it's safer that we check the email_verified boolean when authenticating.

**Comment by gingerlime** [comment]
@davidtaylorhq thanks a lot for letting me know, and I totally agree following the more secure recommendations. Was more curious about practical implications and whether we can expect to see this "in the wild" :)
