### ISSUE TITLE
Add documentation for alternates to Hybrid Authentication

### ISSUE THREAD

**Issue by michaelhays** [zquestz/omniauth-google-oauth2#365]
Like many, I struggled to get the [Hybrid Authentication](https://github.com/zquestz/omniauth-google-oauth2/tree/8b4d6dafea1e741a34c92d595ffb2e7b99acd874#one-time-code-flow-hybrid-authentication) working with this library, due to several errors, before finally giving up on the `redirect_uri_mismatch` error (relevant issues: [181](https://github.com/zquestz/omniauth-google-oauth2/issues/181), [250](https://github.com/zquestz/omniauth-google-oauth2/issues/250), [281](https://github.com/zquestz/omniauth-google-oauth2/issues/281), and a bunch of StackOverflow posts like [this one](https://stackoverflow.com/q/33807752/3414529) and [this one](https://stackoverflow.com/q/41463685/3414529)).

The proposed solution for most of these was to fix the version of a different gem:

```ruby
'omniauth-oauth2', '~> 1.3.1'
```

This wasn't an option for me, so I dove into the `omniauth-google-oauth2` code and found [this](https://github.com/zquestz/omniauth-google-oauth2/blob/8b4d6dafea1e741a34c92d595ffb2e7b99acd874/lib/omniauth/strategies/google_oauth2.rb#L114):

```ruby
elsif verify_token(request.params['access_token'])
  ::OAuth2::AccessToken.from_hash(client, request.params.dup)
```

Using this, I was able to follow [Google's documentation](https://developers.google.com/identity/sign-in/web/backend-auth) using the `access_token` of a user (instead of a one-time code) and POST that to the `/auth/google/callback` endpoint:

```javascript
const googleAuth = window.gapi.auth2.getAuthInstance();
const googleUser = await googleAuth.signIn();
const { access_token } = googleUser.getAuthResponse();

const data = new FormData();
data.append('access_token', access_token);

api.post('/auth/google/callback', data)
  .then(response => console.log(response));
},
```

This ended up being a lot simpler for me, and I really think it would help other people if this were documented somewhere.

Does this all make sense, and do you agree? If so, I'm happy to write it up and make a pull request with that documentation when I have the time (a bit busy right now).

**Comment by zquestz** [comment]
This would be great to document! If you could add this to an example file or the README it would be awesome.

**Comment by jasperduane77** [comment]
Hello. Do you guys still want to add this to the README? 😄

**Comment by michaelhays** [comment]
Yes! Just made a PR. Thanks for the reminder :)

**Comment by pacarvalho** [comment]
Is the `access_token` referred to here actually the `id_token` (the signed JWT from Google with information on the user)?
