### ISSUE TITLE
ruby-jwt removed support for `iat_leeway`

### ISSUE THREAD

**Issue by venables** [zquestz/omniauth-google-oauth2#366]
I noticed I was getting InvalidIatErrors (as solved by this issue: https://github.com/zquestz/omniauth-google-oauth2/issues/197).  

The documentation makes reference to `leeway` in the JWT library as a means to solve this, but, as of v 2.2.0 of the JWT library, iat leeway was removed:  https://github.com/jwt/ruby-jwt/commit/8384f0cbd163a094a39b25c6f1eaaa625e08c9b8

Confirmed that locking the gem `jwt` to version `2.1.0` re-adds support for leeway and things are working smoothly.

**Comment by zquestz** [comment]
Thanks for the report. Would love if you put up a PR to add this to the README so people have a workaround.

**Comment by zquestz** [comment]
Actually did this myself. Thanks for the report!
