### ISSUE TITLE
ReactJs Web client + Ruby-on-Rails API server - Authentication with google_oauth2 using Devise + OmniAuth

### ISSUE THREAD

**Issue by YassineDM** [zquestz/omniauth-google-oauth2#367]
### Configuration

- Provider Gem: `omniauth-google-oauth2 0.7.0`
- Other Gems: `devise 4.6.2` + `omniauth-facebook 5.0.0`
- Ruby Version: `2.6.2`
- Framework: `rails 6.0.0.rc2`

### Expected Behavior

Authentication to facebook or google_oauth2 should succeed (returning `request.env['omniauth.auth']`).
I followed the Devise guide to integrate with Omniauth ([here](https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview)), taking into account Omniauth's recommendations when integrating into a Rails API ([here](https://github.com/omniauth/omniauth)).

### Actual Behavior

Client-side, I am able to connect to facebook or google_oauth2 with OmniAuth. But server-side,  but I get an Authentication failure!
In the rails console, I have different error messages for Facebook and for Google as I request different authentication strategies, using One-time Code Flow (Hybrid Authentication) with Google.

- For Facebook:
```
ERROR -- omniauth: (facebook) Authentication failure! no_authorization_code: OmniAuth::Strategies::Facebook::NoAuthorizationCodeError, must pass either a `code` (via URL or by an `fbsr_XXX` signed request cookie)
```
- For Google:
```
ERROR -- omniauth: (google_oauth2) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
```
I found kind of a workaround by adding `provider_ignores_state: true` in the Devise initializer but it doesn't seem to be secure...

config/initializers/devise.rb
```ruby
  config.omniauth :google_oauth2, google_app_id, google_app_secret, scope: 'email,public_profile', provider_ignores_state: true
```

### Steps to Reproduce

config/initializers/devise.rb
```ruby
  # ==> OmniAuth
  # Add a new OmniAuth provider. Check the wiki for more information on setting
  # up on your models and hooks.
  facebook_app_id = Rails.application.credentials.apis[:facebook][:oauth2][:app_id]
  facebook_app_secret = Rails.application.credentials.apis[:facebook][:oauth2][:app_secret]
  google_app_id = Rails.application.credentials.apis[:google][:oauth2][:app_id]
  google_app_secret = Rails.application.credentials.apis[:google][:oauth2][:app_secret]

  config.omniauth :facebook, facebook_app_id, facebook_app_secret, scope: 'email,public_profile'
  config.omniauth :google_oauth2, google_app_id, google_app_secret, scope: 'email,public_profile'
````

app/config/application.rb
```ruby
    # To integrate OmniAuth into a Rails API.
    config.session_store :cookie_store, key: '_interslice_session'
    config.middleware.use ActionDispatch::Cookies
    config.middleware.use ActionDispatch::Session::CookieStore, config.session_options
```

app/models/user.rb
```ruby
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]
```

config/routes.rb
```ruby
  devise_for :users,
             only: :omniauth_callbacks,
             controllers: { omniauth_callbacks: 'v1/omniauth_callbacks' }
```

app/controllers/v1/omniauth_callbacks_controller.rb
```ruby
module V1
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      generic_callback
    end

    def google_oauth2
      generic_callback
    end

    private

    def generic_callback
      auth = request.env['omniauth.auth']

      user = User.from_omniauth(auth)

      if user.persisted?
        return serialize_response(
          resource: user,
          options: response_options(user_id: user.id),
          status: :created
        )
      end

      # Raise custom 'Unauthenticated' error message.
      raise Errors::Unauthenticated.new(message: 'Invalid social credentials')
    end
  end
end
```

**Comment by zquestz** [comment]
Thank you for the very thorough report. I am not exactly sure what is causing this, but I am curious if `session['omniauth.state'] ` is set at all when that error is thrown.

There are also a few cases where Rails can mess up the session. You might want to read https://github.com/omniauth/omniauth/wiki/FAQ for more details. Usually the answer is to find the action being called and `skip_before_action :verify_authenticity_token`
