### ISSUE TITLE
How can I refresh Token using omniauth-google-oauth2?

### ISSUE THREAD

**Issue by designium** [zquestz/omniauth-google-oauth2#37]

**Comment by deeTEEcee** [comment]
@aceofspades is that still the case? if so, where/how does that happen or get set up exactly? (im having trouble finding that)

**Comment by braintrustalex** [comment]
Where do you have to save the tokens in the DB for the gem to find them? I cannot find any documentation about this, just generally that I "must get the refresh token and save it somewhere in your database"
