### ISSUE TITLE
403 error getting shown after applying domain restriction in google dev console

### ISSUE THREAD

**Issue by SonaliChavan95** [zquestz/omniauth-google-oauth2#374]
When I set a single domain in `hd`(hd: 'foo.com') param, then on the Google login page, Gmail accounts get filtered by that domain i.e. I will be able to see authenticated accounts with `foo.com` domain and `hd=foo.com` param also gets passed in request URI.

But I want to populate Gmail accounts with multiple domains.
```
  config.omniauth :google_oauth2,
    ENV['GOOGLE_CLIENT_ID'],
    ENV['GOOGLE_CLIENT_SECRET'], {
      scope: "userinfo.email",
      prompt: 'select_account',
      hd: %w(foo.com bar.com)
   }
```
In case of multiple domains, I don't see `hd` param getting passed in request uri.

In my application, I want to force users to enable 2-factor authentication which can be achieved only by setting application type as `internal` from google dev console -> OAuth consent screen. But in this case, for wrong Gmail accounts, it returns 403 error.
Is there a way to handle this error or show a proper error message to users?

![Screen Shot 2019-09-20 at 1 28 26 PM](https://user-images.githubusercontent.com/20966155/65309852-8f808a80-dbaa-11e9-8343-1b7a1474bf9d.png)

**Comment by zquestz** [comment]
Unfortunately I don't see any docs about multiple domains for the hd paramater in Google's oauth docs. https://developers.google.com/identity/protocols/OpenIDConnect#hd-param

That being said, it looks odd that it is sending the `hd[]` param instead of `hd`. Maybe try just setting it to a comma delimited string instead of an array?

**Comment by SonaliChavan95** [comment]
> Maybe try just setting it to a comma delimited string instead of an array?

I tried this one, but it doesn't work. It considers the entire string as a domain. 
Thank you for checking though.
