### ISSUE TITLE
Authenticate with an access_token

### ISSUE THREAD

**Issue by jessicah** [zquestz/omniauth-google-oauth2#378]
I'm using Google Sign-In on Android, and getting a token, but I'm not sure how to POST to the callback API successfully.

I'm currently doing equiv of `POST /auth/google/oauth2/callback with access_token=...`

In logs, I have `(google_oauth2) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected`

Does the user-agent matter? I'm using .net core HttpClient.

I can get a CSRF token from Discourse via `GET /session/csrf`, but not exactly sure what to do with this. Could I just set the state option to this?

For background, I'm trying to login to Discourse, so modifying it would be less preferable, but I could do if absolutely required.

**Comment by jessicah** [comment]
Well, I've been inspecting traffic, the `/session/csrf` returns a token, as well as setting cookies; I send the cookie back as well as setting the `X-CSRF-Token` header, but still doesn't seem to work.

**Comment by jessicah** [comment]
Hmm, testing https://github.com/zquestz/omniauth-google-oauth2/blob/e2ace464ac2025bb287e78f7ac0a1249c73658b1/lib/omniauth/strategies/google_oauth2.rb#L209 doesn't seem to be correct?

A simple GET request in browser to `https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=TOKEN` returns the following JSON:
```{
  "error": "invalid_token",
  "error_description": "Invalid Value"
}```
which I'm now finally seeing in my error logs: `Invalid Value { "error_description": "Invalid Value" }`.

Changing `access_token` to `id_token` returns the proper JSON.

**Comment by zquestz** [comment]
Yes you just need to pass the id_token, as that is what is expected. We look for that value within the gem.
