### ISSUE TITLE
README has a 404 link to Google Documentation

### ISSUE THREAD

**Issue by betelgeuse** [zquestz/omniauth-google-oauth2#381]
https://raw.githubusercontent.com/zquestz/omniauth-google-oauth2/e2ace464ac2025bb287e78f7ac0a1249c73658b1/README.md

```
Google describes the One-time Code Flow [here](https://developers.google.com/+/web/signin/server-side-flow)
```

This url gives a 404.

**Comment by karthickbabuos** [comment]
@zquestz  - Are you referring to this URL in Readme
https://developers.google.com/identity/sign-in/web/server-side-flow

**Comment by jethrodaniel** [comment]
If we _really_ want valid links, we  should be using something like wayback machine to date them.

Here's @karthickbabuos's link via that: https://web.archive.org/web/20200418212726/https://developers.google.com/identity/sign-in/web/server-side-flow

**Comment by zquestz** [comment]
Updated README.
