### ISSUE TITLE
Error: Could not determine client ID from request.

### ISSUE THREAD

**Issue by trojanh** [zquestz/omniauth-google-oauth2#384]
```
E, [2020-03-27T19:15:59.175661 #13072] ERROR -- omniauth: (google_oauth2) Authentication failure! invalid_credentials: OAuth2::Error, invalid_request: Could not determine client ID from request.
19:15:59 web.1       | {
19:15:59 web.1       |   "error": "invalid_request",
19:15:59 web.1       |   "error_description": "Could not determine client ID from request."
19:15:59 web.1       | }
19:15:59 web.1       |   
19:15:59 web.1       | OAuth2::Error (invalid_request: Could not determine client ID from request.
19:15:59 web.1       | {
19:15:59 web.1       |   "error": "invalid_request",
19:15:59 web.1       |   "error_description": "Could not determine client ID from request."
19:15:59 web.1       | }):
19:15:59 web.1       |   
19:15:59 web.1       | oauth2 (1.4.4) lib/oauth2/client.rb:120:in `request'
```

I am using [Hybrid Auth method](https://github.com/zquestz/omniauth-google-oauth2#one-time-code-flow-hybrid-authentication) using the example mentioned in [this file](https://github.com/zquestz/omniauth-google-oauth2/blob/master/lib/omniauth/strategies/google_oauth2.rb), after following all the steps I am getting above error. 

I verified the response from Google Auth on the client and it seems to be working fine.

Any help would be appreciated. 

I have referred https://github.com/zquestz/omniauth-google-oauth2/issues/314 which was closed earlier but didn't find anything to fix this issue.

I am using the following versions:
```
rails: 5.2.4.1
Ruby: 2.5.0
gem 'omniauth', '~> 1.9.1'
gem 'omniauth-google-oauth2', '~> 0.8.0'
gem 'omniauth-oauth2', '~> 1.6.0'
```

**Comment by BKSpurgeon** [comment]
How are you passing in the client id?

Are you able to generate some code which replicates the issue so it can be tested on another machine: that would greatly help.

**Comment by trojanh** [comment]
seems the issue was because the `default` envs were getting overridden by `dev` envs, so to make it more clear this issue occurs when the server-side `google_client_id` and `google_client_secret` are not present or incorrectly set. Make sure to check if your development/stage/prod environments are getting these values correctly if you come across this error.

thanks @BKSpurgeon for looking into this and sorry for the false alarm.

Closing this issue on the same note.
