### ISSUE TITLE
using authenticate_or_request_with_http_basic in front of omniauth-google-oauth2

### ISSUE THREAD

**Issue by patrickdavey** [zquestz/omniauth-google-oauth2#385]
Hi - thanks for the excellent gem!

I had a weird "bug" today which took me a while to track down. I've been using `omniauth-google-oauth2` successfully on development and pushed it up to staging for testing. Staging makes use of rails' `authenticate_or_request_with_http_basic` to have basic auth in front of the app. This caused us to see issues like `csrf_detected` and  after I skipped the state checking `invalid_credentials`.  The odd thing which I don't quite understand is that if I _first went to any other page on the website_ (and filled in the basic auth) _then_ the oauth flow would work fine and no csrf issues would be seen.

## Good flow
1. hit any app page and complete the `basic auth` login
2. visit `my_controller_action` which _automatically redirects the user_ to `/auth/google_oauth2`
3. complete authorization and redirection flow

## Bad flow
1. visit `my_controller_action` which _automatically redirects the user_ to `/auth/google_oauth2` (note, this does also prompt for basic auth before the redirect happens!)
2. complete authorization and redirection flow
3. get `csrf_detected` issue

-----------
I'm happy to make a test site to reproduce if I'm unclear above. I'm also not even sure if this is really a "bug" at all, and if it is, whether it's a bug here or somewhere else!

Thanks for your time & the gem :)

**Comment by zquestz** [comment]
The issue is definitely clear. Seems when it is retrieving the credentials it somehow loses some of the incoming parameters. Can you provide the logs?
