### ISSUE TITLE
Redirect Causing ActionDispatch::Cookies::CookieOverflow in Rails 6.0.3

### ISSUE THREAD

**Issue by cguess** [zquestz/omniauth-google-oauth2#386]
I've been using this gem for quite awhile, and since upgrade to Rails 6.0.3, I'm getting occasional `ActionDispatch::Cookies::CookieOverflow` errors.

This seems to be because I'm using the default cookie store (which most people will be) and the Google redirect URL is blowing  up the 4kb limit for the cookie. One solution is to change from the default to a Memcache or ActiveStorage cookie storage, but that seems to be a big ask just to enable Google OAuth, plus it introduces a bunch of other considerations that have to be taken into account.

This may be unrelated to the Rails upgrade and could be coincidence if Google added new params to their redirect URLs.

Thanks for the great product and let me know if there's more info needed.

**Comment by frooeyzanny** [comment]
Hey @cguess, I have the same error!

Please try:
`session['devise.google_data'] = request.env['omniauth.auth'].except("extra")`
instead of
`session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)`

It works for me :)

**Comment by zquestz** [comment]
Thanks for the report. Does the fix from @frooeyzanny work for you?

**Comment by macfanatic** [comment]
> Hey @cguess, I have the same error!
> 
> Please try:
> `session['devise.google_data'] = request.env['omniauth.auth'].except("extra")`
> instead of
> `session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)`
> 
> It works for me :)

This did resolve the issue for me; I was adding to a new rails 6.0.3 project and haven't used this library before and just followed the README.

**Comment by zquestz** [comment]
I updated the README to reflect this!

**Comment by jcat4** [comment]
Apologies, I know this is closed, but I wanted to ask for clarification. I'm having similar issues, but we're currently just using an Omniauth initializer and devise. There's no code on our end that explicitly sets any session info.

I know the docs [cautioned to not do this](https://github.com/zquestz/omniauth-google-oauth2#devise), and to use devise configs and a new controller instead. 

My question is: does devise do something that persists the contents of the auth hash to the session? Is that why these steps are necessary? Thanks in advance!
