### ISSUE TITLE
OmniAuth v2.0.0rc1

### ISSUE THREAD

**Issue by BobbyMcWho** [zquestz/omniauth-google-oauth2#395]
Hello, maintainer of OmniAuth here. 

I just wanted to make the maintainers of this gem aware of the discussion that I have opened regarding v2.0.0 of OmniAuth. I invite you to join in and voice any concerns you may have here: https://github.com/omniauth/omniauth/discussions/1017

**Comment by zquestz** [comment]
Thanks. We are releasing a version for 2.0.0 today.
