### ISSUE TITLE
Rails CORS won't let me communicate with google oauth

### ISSUE THREAD

**Issue by rockwellll** [zquestz/omniauth-google-oauth2#400]
So, i have configured your amazing package and everything runs smoothly. However, when i click this button 

```
      <%= form_tag user_google_oauth2_omniauth_authorize_path, class: "w-full px-4", method: :post do %>
        <button type="submit" class="rounded-md shadow w-full p-2 font-medium text--darker flex items-center justify-center">
          Sign in with Google
        </button>
      <% end %>

```

i get the following error in Brave console

```
Access to fetch at 'url' (redirected from 'http://localhost:3000/users/auth/google_oauth2') from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```

but when i click the link through google console, it successfully navigates to the google oauth page. Any ideas why this occurs?

I have also enables CORS in my backend

```
    Rails.application.config.middleware.insert_before Warden::Manager, Rack::Cors do
      allow do
        origins '*'
        resource '*', :headers => :any, :methods => [:get, :post, :options, :delete, :put, :patch]
      end
    end
```

**Comment by zquestz** [comment]
Any chance you figured this out? Would be curious if you found a solution!

**Comment by developius** [comment]
Try disabling turbo/turbolinks for the form, YMMV but this has worked for me in the past.

```Ruby

form_tag user_google_oauth2_omniauth_authorize_path, class: "w-full px-4", method: :post, data: { turbo: false, local: true } do

```

**Comment by gizipp** [comment]
> According to the latest README, you're now supposed to use a different `link_to`. See below:
> 
> `link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path, method: :post`


`method: :post, data: { turbo: :false }`

disable turbo work for me.
