### ISSUE TITLE
Sinatra example app doesn't work

### ISSUE THREAD

**Issue by jubishop** [zquestz/omniauth-google-oauth2#408]
have to open a new issue, couldn't find a way to reopen https://github.com/zquestz/omniauth-google-oauth2/issues/405

**Comment by jubishop** [comment]
I believe at the very least you need to add `gem webrick` to the Gemfile in `examples`.  then it does indeed at least launch the web server successfully (puma and thin however still do not work).  in any case, I made it work manually without using this gem.  I suggest not closing tickets before giving the reporter a chance to respond.

**Comment by zquestz** [comment]
Fixed, sorry for the delay. =)
