### ISSUE TITLE
Does Projects using this gem will be afected by increase of the sizes of OAuth 2.0 tokens?

### ISSUE THREAD

**Issue by el-mark** [zquestz/omniauth-google-oauth2#411]
I received a mail from google announcing that they will increase of the sizes of OAuth 2.0 tokens by 2048 bytes. I just wanted to know if this change is contemplated.

The full message is:
"Google Cloud Platform will roll out security and reliability improvements that will increase the sizes of OAuth 2.0 tokens. Please follow the instructions below to use the documented token size limits of 2048 bytes and to remove any logic in your services/code that restricts its ability to process access tokens of certain sizes before August 23, 2021."

**Comment by zquestz** [comment]
We have no limits in the code for this. =)
