### ISSUE TITLE
undefined method `scheme' for "https://oauth2.googleapis.com":String

### ISSUE THREAD

**Issue by khanimdad** [zquestz/omniauth-google-oauth2#412]
`Application Trace | Framework Trace | Full Trace
faraday (0.17.4) lib/faraday/connection.rb:454:in `proxy_from_env'
faraday (0.17.4) lib/faraday/connection.rb:86:in `initialize'
faraday (0.17.4) lib/faraday.rb:69:in `new'
faraday (0.17.4) lib/faraday.rb:69:in `new'
oauth2 (1.4.7) lib/oauth2/client.rb:63:in `connection'
oauth2 (1.4.7) lib/oauth2/client.rb:78:in `authorize_url'
oauth2 (1.4.7) lib/oauth2/strategy/auth_code.rb:18:in `authorize_url'
omniauth-oauth2 (1.7.1) lib/omniauth/strategies/oauth2.rb:59:in `request_phase'
omniauth (1.9.1) lib/omniauth/strategy.rb:226:in `request_call'
omniauth (1.9.1) lib/omniauth/strategy.rb:188:in `call!'
omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.1) lib/omniauth/builder.rb:45:in `call'
bullet (6.1.4) lib/bullet/rack.rb:15:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.1.3.2) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (6.1.3.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.1.3.2) lib/action_dispatch/middleware/cookies.rb:689:in `call'
activerecord (6.1.3.2) lib/active_record/migration.rb:601:in `call'`

**Comment by zquestz** [comment]
This looks like it is looking for a URI object, not sure what is causing that. There is also nothing from this gem in your stack trace.
