### ISSUE TITLE
undefined method bytesize for hash

### ISSUE THREAD

**Issue by chmtt** [zquestz/omniauth-google-oauth2#418]
I am using rails 7 and getting the following error when google redirects to my app:

`ERROR -- omniauth: (google_oauth2) Authentication failure! undefined method "bytesize" for #<Hash:...>: NoMethodError, undefined method "bytesize" for #<Hash:...>`

**Comment by zquestz** [comment]
This is not inside of our gem. We literally don't use that method anywhere in our code. Might be more obvious with a full stack trace.

**Comment by Jory-Jaguar** [comment]
This seems to be related to this issue in the dependency, https://github.com/oauth-xx/oauth2/issues/572
Updating to Oauth2 1.4.9 solved this issue for me.

**Comment by chmtt** [comment]
> Updating to Oauth2 1.4.9 solved this issue for me.

@Jory-Jaguar thank you this fixed the issue for me too 🙏🏻
