### ISSUE TITLE
Image size is not working properly

### ISSUE THREAD

**Issue by silva96** [zquestz/omniauth-google-oauth2#419]
When I request my user, it returns the profile picture in this format (which I believe is not the format this gem expects)

https://lh3.googleusercontent.com/a-/AOh14Girjdxgw0kygBhGCtIpIOgxHuKej3MLf5Ug6vmA=s96-c

Beign s96-c the size.

Currently I'm mannually changing my url  like this,

image.gsub('s96-c', 's128-c')

But I thought it would be useful to fix the bug in the gem

Here is the official documentation: https://developers.google.com/people/image-sizing

**Comment by zquestz** [comment]
Sorry for the extreme delay, but this is now fixed and will be in the 1.2.0 release.

https://github.com/zquestz/omniauth-google-oauth2/commit/452e119f3252f3751030eeb95cb37bcfb550a836
