### ISSUE TITLE
Updating to use OAuth2 v2.x?

### ISSUE THREAD

**Issue by cyrusstoller** [zquestz/omniauth-google-oauth2#425]
Thank you so much for putting this valuable gem together.

Are there plans to update the gemspec to use OAuth2 v2.x? Recently after installing this gem I saw "You have installed oauth2 version 1.4.10, which is EOL."

**Comment by bdunlap** [comment]
FWIW the 1.x branch of oauth2 [will still receive security updates](https://github.com/oauth-xx/oauth2/blob/master/SECURITY.md)

**Comment by zquestz** [comment]
Has been merged. New release is imminent.
