### ISSUE TITLE
How to reset omniauth-google-oauth2 access_token when user account has been removed

### ISSUE THREAD

**Issue by coppermind** [zquestz/omniauth-google-oauth2#43]
We are encountering an issue where if the user's account has been deleted from system after the user already granted access to the application from his google account, the authentication just goes in an endless loop of trying to authenticate the deleted user.

The scenario goes something like:
1. The user authenticates via google and grants access for the application
2. In the callback, our application determines if the user account is valid - deleted, or not created (our system does not support self service registration
3. The user is not authorised (and not signed in) which is correct
4. If the user attempts to sign-in via Google again, to try another account, Google transparently authorizes and redirects the user back to our application without giving the user a chance to change accounts.

The user can actually get out of this loop by logging out of first. But that's not really obvious to the average user so is not an ideal solution.

Ideally, the solution would be to invalidate the access_token or revoke the application authorization in the callback phase so that when the user tries to sign in again they can switch accounts.

**Comment by hundsim** [comment]
That link on SO seems to be a very hacky solution. Isn't there any more straight forward way to revoke access?
