### ISSUE TITLE
JWT::DecodeError, Invalid segment encoding when using access_token 

### ISSUE THREAD

**Issue by duongvancuong** [zquestz/omniauth-google-oauth2#435]
I am using v1.1.1 and am getting such an error message:
`Authentication failure! Invalid segment encoding: JWT::DecodeError, Invalid segment encoding`
But it worked fine before I upgraded to this version. So I checked the difference and noticed that.
https://github.com/zquestz/omniauth-google-oauth2/blob/master/lib/omniauth/strategies/google_oauth2.rb#L128

![Screen Shot 2022-10-04 at 2 18 33 PM](https://user-images.githubusercontent.com/19904857/193758228-7a8cf1a3-b1a5-4ee6-9e91-468bfa1ef51b.png)

When I try to pass the `access_token` params it will fall on line 128, I get an access_token instance that contains the token which is the `access_token` that I gave. It will fail at line 75 with the below code. Because maybe only `id_token` can decode successfully.

![Screen Shot 2022-10-04 at 2 23 39 PM](https://user-images.githubusercontent.com/19904857/193759202-6c4dff90-2444-4e0c-9c2e-2f435fcf6edd.png)

So I wish you could consider [line 74](https://github.com/zquestz/omniauth-google-oauth2/blob/master/lib/omniauth/strategies/google_oauth2.rb#L74) so that it can be skipped in case the `token` is `access_token`. Thank you!

**Comment by zquestz** [comment]
Can't you just pass the `skip_jwt` option?

**Comment by duongvancuong** [comment]
@zquestz 
Yes, I can, but I was wondering if using `skip_jwt` would affect the use case of the `verifier` just above.

**Comment by zquestz** [comment]
Yes, `skip_jwt` should only be used if you are using a token that can't be parsed.

**Comment by zquestz** [comment]
I can look into handling this case better.

**Comment by duongvancuong** [comment]
@zquestz 
Well, currently my application is using both cases where the user can use the `verifier` by `code` or use the `access_token` param.
If using `skip_jwt` with the `verifier` case is there any problem? because if not `skip_jwt` then using `access_token` will show the error message.

**Comment by zquestz** [comment]
There is literally know if they are using an access_token or id_token within the oauth2 gem... Unfortunately this can't be resolved until there is a way to detect if an access token is an id_token or an access token before the jwt verification step.

When I have the token and decode it, it always shows as an access_token, even when initialized as an id_token....

Unless they fix that upstream, there is nothing that can be done in this gem to improve the process.

**Comment by xxx** [comment]
I ran into this earlier today when adding a new provider for google sheets, where we need to request a custom scope. In my case, making sure the `profile` scope is also included resolves it. 

i.e. `scope: 'profile,https://www.googleapis.com/auth/spreadsheets'`

**Comment by mindtonic** [comment]
@xxx Brilliant!
