### ISSUE TITLE
No option for force-reauthentication

### ISSUE THREAD

**Issue by GeorgeHaddad0** [zquestz/omniauth-google-oauth2#439]
No option for already signed in users with google to be forced to enter their google credentials again, once they are logged in with google they automatically be logged in with sso.... I am looking for a way to force them reenter the credentials.

https://github.com/zquestz/omniauth-google-oauth2/issues/436

plesae at least confirm there is no option like that and if that something you are working on

**Comment by zquestz** [comment]
Yes, there is no option for this currently. I do not believe Google has hooks for this, if they do I would be happy to add it.

**Comment by GeorgeHaddad0** [comment]
Thanks

**Comment by HashNuke** [comment]
@zquestz is right. There is no endpoint to force-reauth.

The user that logged in via Google OAuth has to be instructed to remove the app from their account via accounts.google.com. After this, Google will then prompt the user to enter credentials when trying to login to the same app again.
