### ISSUE TITLE
Restore session without prompting user to login again

### ISSUE THREAD

**Issue by esasse** [zquestz/omniauth-google-oauth2#449]
When I restore the user session from a cookie, I need to make sure the Google account is still valid without requesting another login. What's the best way to do that?

Thanks!

**Comment by zquestz** [comment]
You would need to make sure you have a refresh token, and then on login you would need to use that to make a call to check the google account.

**Comment by bzepelini** [comment]
Awesome! I’ll take a closer look and prepare a pull request soon. :)

**Comment by zquestz** [comment]
It could definitely be a different gem, just one that integrates well with this one. =)
