### ISSUE TITLE
If i go back after successful login i get CSRF error

### ISSUE THREAD

**Issue by xhyrom** [zquestz/omniauth-google-oauth2#461]
Hi, i'm facing same issue as described in https://github.com/omniauth/omniauth-oauth2/issues/95. Is there any way to fix it directly in this gem or i have to modify the gems?

**Comment by zquestz** [comment]
Yeah there is no direct way to fix this in this gem.

**Comment by xhyrom** [comment]
Well you could do monkey patching but that's a bit tricky, thanks anyways for your response.
