### ISSUE TITLE
`JWT::Verify` is gone in ruby-jwt v2.9.0

### ISSUE THREAD

**Issue by nov** [zquestz/omniauth-google-oauth2#463]
this code causes `uninitialized constant JWT::Verify`
https://github.com/zquestz/omniauth-google-oauth2/blob/827978dba46af03ca1ea1586bf475228f21b1336/lib/omniauth/strategies/google_oauth2.rb#L79C13-L79C24

**Comment by v-kumar** [comment]
Need to use `Claims.verify`. See https://github.com/jwt/ruby-jwt/commit/e6652b78adcca9bf1f5a1507281b1e451cd45754#diff-22f4e5dc19830d5887625163d445741fb0559bf9207c849e645dacebd77acb08L116

**Comment by zquestz** [comment]
Would definitely take a PR, I doubt claims.verify works in older versions based on this PR, and I don't want to break people using older versions...

**Comment by nov** [comment]
you mean you are not happy with sush changes?
https://github.com/zquestz/omniauth-google-oauth2/pull/464
