### ISSUE TITLE
Why store session upon failure?

### ISSUE THREAD

**Issue by coezbek** [zquestz/omniauth-google-oauth2#466]
The callback controller is storing the data from the request env `omniauth.auth` into the session upon failure:

# app/controllers/users/omniauth_callbacks_controller.rb:

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

This is something I haven't seen other omniauth callbacks do. What is the purpose and shouldn't this just be done when the login succeeded?

I can't find any information on why this is necessary or why we would want to store it in the session.

**Comment by zquestz** [comment]
This is generally used for debugging, and is not required. People tend to have issues with implementation, and if they don't store any session information then they get very little information about why the login failed.

You can safely remove this, and it is not required.

**Comment by coezbek** [comment]
Thank you! If this enabled in production would it be a CVE / vulnerability?

**Comment by zquestz** [comment]
Nope it would not. It would just store the error they got from Google. It doesn't allow them to do anything malicious.

**Comment by zquestz** [comment]
Updated the README to clarify the session storage.
