### ISSUE TITLE
Refresh Token not Returned

### ISSUE THREAD

**Issue by t2** [zquestz/omniauth-google-oauth2#467]
Hello,

When authenticating with the default of `access_type: 'offline'`, I am still not receiving the `refresh_token` in auth credentials. What else could be causing this?

Rails: 7.1.5
omniauth-google-oauth2: 1.2.0

**Comment by zquestz** [comment]
Not sure what is happening for you, but I just tested the example app with the following settings, and it returned the `refresh_token`...

```
provider :google_oauth2, ENV['GOOGLE_KEY'], ENV['GOOGLE_SECRET'], access_type: 'offline', scope: 'email,profile,calendar'
```

When I have `access_type` as `offline` it seems to function as expected... =\

**Comment by zquestz** [comment]
This thread may be useful for you!

https://github.com/googleapis/google-api-python-client/issues/213

**Comment by t2** [comment]
Thanks @zquestz! The fix was to add `prompt: consent` and to deauthorize/reauthorize the app. Not sure what changed along the way since this was working for years but glad to find it. Thanks for the resource and the work you did with this gem.

**Comment by t2** [comment]
Welp, subsequent calls do not return refresh token...
