### ISSUE TITLE
The action 'google_oauth2' could not be found for Users::OmniauthCallbacksController

### ISSUE THREAD

**Issue by kashiftufail** [zquestz/omniauth-google-oauth2#52]
Hi,

I'm using 'omniauth-google-oauth2' for sign in with google and follow all instruction here carefully 

```
    https://github.com/plataformatec/devise/wiki/OmniAuth%3A-Overview
```

but i have error above.

my routes 

  devise_for :users, :controllers => {
      :omniauth_callbacks => "users/omniauth_callbacks"

  }

devise.rb code

 config.omniauth :google_oauth2, "863625299460-420n6c7lvad91dfvko60uamtvtr6huhf.apps.googleusercontent.com", "dcvA2aZRZi27KCQjWTYP30pw", { access_type: "offline", approval_prompt: "" }

omniauth callback controller code

```
        def google_oauth2
        @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
end
```

Can you please help?

see screenshot below

![sss](https://f.cloud.github.com/assets/998374/381433/acbbdabc-a5df-11e2-80da-4f22481cd5ed.png)

**Comment by Shariffintech** [comment]
Can you post your missing route? @zquestz

**Comment by dgandhi570** [comment]
just change your funtion name from **google** to **### google_oauth2** in omniauthcallbackscontroller
