### ISSUE TITLE
request.env["omniauth.auth"] returns nil with google auth

### ISSUE THREAD

**Issue by fahim-patel** [zquestz/omniauth-google-oauth2#90]
Hello,

I am  integrating google calender api. All working fine but in call back "request.env["omniauth.auth"]" returning nil. 

I have configured "omniauth.rb" with below details:-
###### 

provider :google_oauth2, 'client_id','key', {
    access_type: 'offline',
    scope: 'https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/calendar',
    redirect_uri:'http://localhost:3000/auth/google_oauth2/callback'
  }
###### 

Thanks! in advance ...

Best Regards
Fahim Babar Patel

**Comment by shail** [comment]
@dylanz did you ever figure out your issue? I'm having the same problem

**Comment by dylanz** [comment]
@shail:  unfortunately, I don't remember how this ended up working (which it seems like it did... I remember having the correct scopes and everything set up properly about 100 times).  Good luck!  If you figure it out, it would be great if you could post what you did here.

**Comment by jalevin** [comment]
+1
